package pojo.hibernate;
// Generated May 29, 2011 11:33:37 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ErpmItemRateDetails generated by hbm2java
 */
public class ErpmItemRateDetails  implements java.io.Serializable {


     private Integer irdItemRateDetailsId;
     private ErpmItemRate erpmItemRate;
     private Date irdWefDate;
     private Date irdWetDate;
     private BigDecimal irdRate;
     private Set erpmItemRateTaxeses = new HashSet(0);

    public ErpmItemRateDetails() {
    }

	
    public ErpmItemRateDetails(ErpmItemRate erpmItemRate) {
        this.erpmItemRate = erpmItemRate;
    }
    public ErpmItemRateDetails(ErpmItemRate erpmItemRate, Date irdWefDate, Date irdWetDate, BigDecimal irdRate, Set erpmItemRateTaxeses) {
       this.erpmItemRate = erpmItemRate;
       this.irdWefDate = irdWefDate;
       this.irdWetDate = irdWetDate;
       this.irdRate = irdRate;
       this.erpmItemRateTaxeses = erpmItemRateTaxeses;
    }
   
    public Integer getIrdItemRateDetailsId() {
        return this.irdItemRateDetailsId;
    }
    
    public void setIrdItemRateDetailsId(Integer irdItemRateDetailsId) {
        this.irdItemRateDetailsId = irdItemRateDetailsId;
    }
    public ErpmItemRate getErpmItemRate() {
        return this.erpmItemRate;
    }
    
    public void setErpmItemRate(ErpmItemRate erpmItemRate) {
        this.erpmItemRate = erpmItemRate;
    }
    public Date getIrdWefDate() {
        return this.irdWefDate;
    }
    
    public void setIrdWefDate(Date irdWefDate) {
        this.irdWefDate = irdWefDate;
    }
    public Date getIrdWetDate() {
        return this.irdWetDate;
    }
    
    public void setIrdWetDate(Date irdWetDate) {
        this.irdWetDate = irdWetDate;
    }
    public BigDecimal getIrdRate() {
        return this.irdRate;
    }
    
    public void setIrdRate(BigDecimal irdRate) {
        this.irdRate = irdRate;
    }
    public Set getErpmItemRateTaxeses() {
        return this.erpmItemRateTaxeses;
    }
    
    public void setErpmItemRateTaxeses(Set erpmItemRateTaxeses) {
        this.erpmItemRateTaxeses = erpmItemRateTaxeses;
    }




}


