/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package upload;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;


/** 
 * MyEclipse Struts
 * Creation date: 06-27-2009
 * 
 * XDoclet definition:
 * @struts.form name="uploadfileform"
 */
/**
 * This class is a form bean which contains getter and setter of all properties of file
 */
@SuppressWarnings("serial")
public class UploadFileForm extends ActionForm {
	/*
	 * Generated fields
	 */
	/**
	 * for holding file description.
	 */
	private String fdescription;	//for holding file description.
	/**
	 * for holding the project name
	 */
	private String fileName;	//for holding project name.
	/**
	 * for holding the uploaded file
	 */
	private FormFile uploadedFile;	//for holding complete path of uploaded file with file name.
	/**
	 * for holding the file name
	 */
	private String upload;
	/**
	 * for holding the location of a file on server
	 */
	private String size;
	private String owner;
	private String projectName;
	/*
	 * Generated Methods
	 */
	
	/*
	 * The method getFdescription return file description
	 * */
	public String getSize()
	{
		return size;
	}
	
	public void setSize(String size)
	{
		this.size=size;
	}
	
	public String getOwner()
	{
		return owner;
	}
	
	public void setOwner(String owner)
	{
		this.owner=owner;
	}
	
	public String getProjectName()
	{
		return projectName;
	}
	
	public void setProjectName(String projectName)
	{
		this.projectName=projectName;
	}
	
	public UploadFileForm()
	{
		
	}
	
	/**
	 * This constructor sets the values of uploaded file as project name,file name,description etc
	 * @param fileName for project name
	 * @param fdescription for description of a file
	 * @param uploadedFile path of uploaded file
	 */
	public UploadFileForm(String fileName,String fdescription,FormFile uploadedFile) {
		// TODO Auto-generated constructor stub
		this.fdescription=fdescription;
		this.uploadedFile=uploadedFile;
		this.fileName=fileName;
	}
	/**
	 * Another constructor but  the name of File Name 
	 * @param fileName for project name
	 * @param fdescription for description of file
	 * @param upload The name of uploaded file
 	 */ 
	public UploadFileForm(String fileName,String owner,String projectName,String fdescription,String size) {
		// TODO Auto-generated constructor stub
		this.fdescription=fdescription;
		this.projectName=projectName;
		this.fileName=fileName;
		this.owner=owner;
		this.size=size;
	}
	//to normal user
	
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getFdescription() {
		return fdescription;
	}
	/**
	 * The method setFdescription is used for setting file description in variable fdescription 
	 * */
	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}
	/**
	 * The method getfileName return project name
	 * */
	public String getFileName() {
		return fileName;
	}
	/**
	 * The method setfileName is used for setting the project name in a variable fileName
	 * */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	
	/**
	 * The method getUploadedFile return path of uploaded file
	 * */
	public FormFile getUploadedFile()  {
	    return uploadedFile;
	  }
	
	/**
	 * The method setUploadedFile is used for setting complete path of uploaded file
	 * */
	  public void setUploadedFile(FormFile uploadedFile) {
	    this.uploadedFile = uploadedFile;
	  }
	
	  public String getUpload() {
			return upload;
		}
		/**
		 * The method setfileName is used for setting the project name in a variable fileName
		 * */
		public void setUpload(String upload) {
			this.upload = upload;
		}
		
}