CREATE TABLE `staff_perform_stugui_data` ( `spsgd_id` INT(11) NOT NULL AUTO_INCREMENT , `spsgd_empid` INT(11) NOT NULL , `spsgd_sname` VARCHAR(255) NOT NULL , `spsgd_scollege` VARCHAR(255) NOT NULL , `spsgd_sdegree` VARCHAR(255) NOT NULL , `spsgd_sdiscipine` VARCHAR(255) NOT NULL , `spsgd_syear` INT(4) NOT NULL , `spsgd_role` VARCHAR(255) NOT NULL , `spsgd_creator` VARCHAR(255) NOT NULL , `spsgd_creationdate` DATE NOT NULL , `spsgd_modifier` VARCHAR(255) NOT NULL , `spsgd_modidate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`spsgd_id`)) ENGINE = InnoDB; 

CREATE TABLE `staff_perform_stugui_data_archive` ( `spsgda_id` INT(11) NOT NULL AUTO_INCREMENT , `spsgda_spsgdid` INT(11) NOT NULL,`spsgda_empid` INT(11) NOT NULL , `spsgda_sname` VARCHAR(255) NOT NULL , `spsgda_scollege` VARCHAR(255) NOT NULL , `spsgda_sdegree` VARCHAR(255) NOT NULL , `spsgda_sdiscipine` VARCHAR(255) NOT NULL , `spsgda_syear` INT(4) NOT NULL , `spsgda_role` VARCHAR(255) NOT NULL , `spsgda_creator` VARCHAR(255) NOT NULL , `spsgda_creationdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`spsgda_id`)) ENGINE = InnoDB; 

CREATE TABLE `staff_perform_guest_lect_data` ( `spgld_id` INT(11) NOT NULL AUTO_INCREMENT , `spgld_empid` INT(11) NOT NULL , `spgld_gtitle` VARCHAR(255) NOT NULL , `spgld_month` VARCHAR(255) NOT NULL , `spgld_year` INT(4) NOT NULL , `spgld_details` VARCHAR(255) NOT NULL , `spgld_creator` VARCHAR(255) NOT NULL , `spgld_creationdate` DATE NOT NULL , `spgld_modifier` VARCHAR(255) NOT NULL , `spgld_modidate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`spgld_id`)) ENGINE = InnoDB;


CREATE TABLE `staff_perform_guest_lect_data_archive` ( `spglda_id` INT(11) NOT NULL AUTO_INCREMENT , `spglda_spgldid` INT(11) NOT NULL,`spglda_empid` INT(11) NOT NULL , `spglda_gtitle` VARCHAR(255) NOT NULL , `spglda_month` VARCHAR(255) NOT NULL , `spglda_year` INT(4) NOT NULL , `spglda_details` VARCHAR(255) NOT NULL , `spglda_creator` VARCHAR(255) NOT NULL , `spglda_creationdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`spglda_id`)) ENGINE = InnoDB;

CREATE TABLE `staff_pub_data_archive` ( `spbda_id` INT(11) NOT NULL AUTO_INCREMENT ,`spbda_spbdid` INT(11) NOT NULL, `spbda_empid` INT(9) NOT NULL , `spbda_pubtype` VARCHAR(255) NOT NULL , `spbda_title` VARCHAR(255) NOT NULL , `spbda_authors` VARCHAR(255) NOT NULL , `spbda_authortype` VARCHAR(255) NOT NULL , `spbda_journalname` VARCHAR(255) NULL , `spbda_month` VARCHAR(50) NULL , `spbda_year` INT(4) NULL , `spbda_issnno` VARCHAR(255) NULL , `spbda_chapno` INT(3) NULL , `spbda_pageno` INT(3) NULL , `spbda_metrictype` VARCHAR(255) NULL , `spbda_metricvalue` INT(5) NULL , `spbda_publevel` VARCHAR(255) NULL , `spbda_progrmname` VARCHAR(255) NULL , `spbda_progrmvenue` VARCHAR(255) NULL , `spbda_bookname` VARCHAR(255) NULL , `spbda_bookchapternme` VARCHAR(255) NULL , `spbda_publishername` VARCHAR(255) NULL , `spbda_language` VARCHAR(255) NULL , `spbda_creatorname` VARCHAR(255) NOT NULL , `spbda_creationdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`spbda_id`)) ENGINE = InnoDB;

CREATE TABLE `staff_training_attended_archive` ( `staa_id` INT(11) NOT NULL AUTO_INCREMENT , `staa_staid` INT(11) NOT NULL,`staa_empid` INT(11) NOT NULL , `staa_prgtype` VARCHAR(255) NOT NULL , `staa_prgsubtype` VARCHAR(255) NULL , `staa_prglevel` VARCHAR(255) NULL , `staa_prgtitle` VARCHAR(255) NULL , `staa_prgduration` INT(2) NULL , `staa_prgfrmdate` DATE NULL , `staa_prgtodate` DATE NULL , `staa_prgvenue` VARCHAR(255) NULL , `staa_prgorganisedby` VARCHAR(255) NULL , `staa_sponceredby` VARCHAR(255) NULL , `staa_creatorname` VARCHAR(255) NOT NULL , `staa_creationdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`staa_id`)) ENGINE = InnoDB;

CREATE TABLE `staff_training_organised_archive` ( `stoa_id` INT(11) NOT NULL AUTO_INCREMENT , `stoa_stoid` INT(11) NOT NULL,`stoa_empid` INT(11) NOT NULL , `stoa_prgtype` VARCHAR(255) NOT NULL , `stoa_prgsubtype` VARCHAR(255) NULL , `stoa_prglevel` VARCHAR(255) NULL , `stoa_prgtitle` VARCHAR(255) NULL , `stoa_prgduration` INT(2) NULL , `stoa_prgfrmdate` DATE NULL , `stoa_prgtodate` DATE NULL , `stoa_prgvenue` VARCHAR(255) NULL , `stoa_prgorganisedby` VARCHAR(255) NULL , `stoa_sponceredby` VARCHAR(255) NULL ,`stoa_capacity` VARCHAR(255) NULL ,`stoa_participantno` VARCHAR(255) NULL ,`stoa_participantnature` VARCHAR(255) NULL , `stoa_creatorname` VARCHAR(255) NOT NULL , `stoa_creationdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`stoa_id`)) ENGINE = InnoDB;

CREATE TABLE `staff_perform_project_data_archive` ( `sppda_id` INT(11) NOT NULL AUTO_INCREMENT ,`sppda_sppdid` INT(11) NOT NULL , `sppda_empid` INT(11) NOT NULL , `sppda_ptitle` VARCHAR(255) NOT NULL , `sppda_prole` VARCHAR(255) NOT NULL , `sppda_pfundagency` VARCHAR(255) NOT NULL , `sppda_agendytype` VARCHAR(255) NOT NULL , `sppda_budget` FLOAT(10,2) NOT NULL , `sppda_duration` INT(3) NOT NULL , `sppda_fromdate` DATE NOT NULL , `sppda_todate` DATE NOT NULL , `sppda_remark` VARCHAR(255) NOT NULL , `sppda_creatorname` VARCHAR(255) NOT NULL , `sppda_creationdate`  TIMESTAMP NOT NULL , PRIMARY KEY (`sppda_id`)) ENGINE = InnoDB;

CREATE TABLE `staff_perform_award_data_archive` ( `spada_id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT , `spada_spadid` INT(11) NOT NULL ,`spada_empid` INT(11) NOT NULL , `spada_awardtitle` VARCHAR(255) NOT NULL , `spada_awardtype` VARCHAR(255) NOT NULL , `spada_year` INT(4) NOT NULL , `spada_awardby` VARCHAR(255) NOT NULL , `spada_details` VARCHAR(255) NOT NULL , `spada_creatorname` VARCHAR(255) NOT NULL , `spada_creationdate` TIMESTAMP NOT NULL ) ENGINE = InnoDB;
