package com.myapp.struts.hbm;
// Generated May 28, 2011 3:23:31 PM by Hibernate Tools 3.2.1.GA



/**
 * ElectionruleId generated by hbm2java
 */
public class ElectionruleId  implements java.io.Serializable {


     private String ruleId;
     private String electionId;
     private String instituteId;
     private int positionId;

    public ElectionruleId() {
    }

    public ElectionruleId(String ruleId, String electionId, String instituteId,int positionId) {
       this.ruleId = ruleId;
       this.electionId = electionId;
       this.instituteId = instituteId;
        this.positionId = positionId;
    }
   
    public String getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }
    public String getElectionId() {
        return this.electionId;
    }
    
    public void setElectionId(String electionId) {
        this.electionId = electionId;
    }
    public String getInstituteId() {
        return this.instituteId;
    }
    
    public void setInstituteId(String instituteId) {
        this.instituteId = instituteId;
    }

     public int getPositionId() {
        return this.positionId;
    }

    public void setPositionId(int positionId) {
        this.positionId = positionId;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ElectionruleId) ) return false;
		 ElectionruleId castOther = ( ElectionruleId ) other; 
         
		 return ( (this.getRuleId()==castOther.getRuleId()) || ( this.getRuleId()!=null && castOther.getRuleId()!=null && this.getRuleId().equals(castOther.getRuleId()) ) )
 && ( (this.getElectionId()==castOther.getElectionId()) || ( this.getElectionId()!=null && castOther.getElectionId()!=null && this.getElectionId().equals(castOther.getElectionId()) ) )
 && ( (this.getInstituteId()==castOther.getInstituteId()) || ( this.getInstituteId()!=null && castOther.getInstituteId()!=null && this.getInstituteId().equals(castOther.getInstituteId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRuleId() == null ? 0 : this.getRuleId().hashCode() );
         result = 37 * result + ( getElectionId() == null ? 0 : this.getElectionId().hashCode() );
         result = 37 * result + ( getInstituteId() == null ? 0 : this.getInstituteId().hashCode() );
         return result;
   }   


}


