package com.myapp.struts.hbm;
// Generated Feb 3, 2012 11:38:42 PM by Hibernate Tools 3.2.1.GA



/**
 * ElectionManagerMigrateId generated by hbm2java
 */
public class ElectionManagerMigrateId  implements java.io.Serializable {


     private String electionId;
     private String instituteId;

    public ElectionManagerMigrateId() {
    }

    public ElectionManagerMigrateId(String electionId, String instituteId) {
       this.electionId = electionId;
       this.instituteId = instituteId;
    }
   
    public String getElectionId() {
        return this.electionId;
    }
    
    public void setElectionId(String electionId) {
        this.electionId = electionId;
    }
    public String getInstituteId() {
        return this.instituteId;
    }
    
    public void setInstituteId(String instituteId) {
        this.instituteId = instituteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ElectionManagerMigrateId) ) return false;
		 ElectionManagerMigrateId castOther = ( ElectionManagerMigrateId ) other; 
         
		 return ( (this.getElectionId()==castOther.getElectionId()) || ( this.getElectionId()!=null && castOther.getElectionId()!=null && this.getElectionId().equals(castOther.getElectionId()) ) )
 && ( (this.getInstituteId()==castOther.getInstituteId()) || ( this.getInstituteId()!=null && castOther.getInstituteId()!=null && this.getInstituteId().equals(castOther.getInstituteId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getElectionId() == null ? 0 : this.getElectionId().hashCode() );
         result = 37 * result + ( getInstituteId() == null ? 0 : this.getInstituteId().hashCode() );
         return result;
   }   


}


