package com.myapp.struts.hbm;
// Generated Jun 13, 2011 4:40:01 PM by Hibernate Tools 3.2.1.GA



/**
 * Eligibility generated by hbm2java
 */
public class Eligibility  implements java.io.Serializable {


     private EligibilityId id;
     private String eligibility;
     private String department;
     private String marks;
     private String attendence;
     private String backlog;
     private String criminallog;
     private String indiscipline;

    public Eligibility() {
    }

	
    public Eligibility(EligibilityId id) {
        this.id = id;
    }
    public Eligibility(EligibilityId id, String eligibility, String department, String marks, String attendence, String backlog, String criminallog, String indiscipline) {
       this.id = id;
       this.eligibility = eligibility;
       this.department = department;
       this.marks = marks;
       this.attendence = attendence;
       this.backlog = backlog;
       this.criminallog = criminallog;
       this.indiscipline = indiscipline;
    }
   
    public EligibilityId getId() {
        return this.id;
    }
    
    public void setId(EligibilityId id) {
        this.id = id;
    }
    public String getEligibility() {
        return this.eligibility;
    }
    
    public void setEligibility(String eligibility) {
        this.eligibility = eligibility;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getMarks() {
        return this.marks;
    }
    
    public void setMarks(String marks) {
        this.marks = marks;
    }
    public String getAttendence() {
        return this.attendence;
    }
    
    public void setAttendence(String attendence) {
        this.attendence = attendence;
    }
    public String getBacklog() {
        return this.backlog;
    }
    
    public void setBacklog(String backlog) {
        this.backlog = backlog;
    }
    public String getCriminallog() {
        return this.criminallog;
    }
    
    public void setCriminallog(String criminallog) {
        this.criminallog = criminallog;
    }
    public String getIndiscipline() {
        return this.indiscipline;
    }
    
    public void setIndiscipline(String indiscipline) {
        this.indiscipline = indiscipline;
    }




}


