package com.myapp.struts.hbm;
// Generated Feb 2, 2012 11:01:16 PM by Hibernate Tools 3.2.1.GA



/**
 * VoterRegistration generated by hbm2java
 */
public class VoterRegistration  implements java.io.Serializable {


     private VoterRegistrationId id;
     private String department;
     private String course;
     private String year;
     private String courseDuration;
     private String currentSession;
     private String joiningDate;
     private String voterName;
     private String gender;
     private String birthdate;
     private String mobileNumber;
     private String CAddress;
     private String city;
     private String state;
     private String zipCode;
     private String country;
     private String PAddress;
     private String city1;
     private String state1;
     private String zipCode1;
     private String country1;
     private String email;
     private String image;
     private String status;
     private String FName;
     private String MName;
     private String setVoter;
     private String alternateMail;

    public String getAlternateMail() {
        return alternateMail;
    }

    public void setAlternateMail(String alternateMail) {
        this.alternateMail = alternateMail;
    }

    public VoterRegistration() {
    }

	
    public VoterRegistration(VoterRegistrationId id) {
        this.id = id;
    }
    public VoterRegistration(VoterRegistrationId id, String department, String course, String year, String courseDuration, String currentSession, String joiningDate, String voterName, String gender, String birthdate, String mobileNumber, String CAddress, String city, String state, String zipCode, String country, String PAddress, String city1, String state1, String zipCode1, String country1, String email, String image, String status, String FName, String MName, String setVoter) {
       this.id = id;
       this.department = department;
       this.course = course;
       this.year = year;
       this.courseDuration = courseDuration;
       this.currentSession = currentSession;
       this.joiningDate = joiningDate;
       this.voterName = voterName;
       this.gender = gender;
       this.birthdate = birthdate;
       this.mobileNumber = mobileNumber;
       this.CAddress = CAddress;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
       this.country = country;
       this.PAddress = PAddress;
       this.city1 = city1;
       this.state1 = state1;
       this.zipCode1 = zipCode1;
       this.country1 = country1;
       this.email = email;
       this.image = image;
       this.status = status;
       this.FName = FName;
       this.MName = MName;
       this.setVoter = setVoter;
    }
   
    public VoterRegistrationId getId() {
        return this.id;
    }
    
    public void setId(VoterRegistrationId id) {
        this.id = id;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public String getCourseDuration() {
        return this.courseDuration;
    }
    
    public void setCourseDuration(String courseDuration) {
        this.courseDuration = courseDuration;
    }
    public String getCurrentSession() {
        return this.currentSession;
    }
    
    public void setCurrentSession(String currentSession) {
        this.currentSession = currentSession;
    }
    public String getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(String joiningDate) {
        this.joiningDate = joiningDate;
    }
    public String getVoterName() {
        return this.voterName;
    }
    
    public void setVoterName(String voterName) {
        this.voterName = voterName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getCAddress() {
        return this.CAddress;
    }
    
    public void setCAddress(String CAddress) {
        this.CAddress = CAddress;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPAddress() {
        return this.PAddress;
    }
    
    public void setPAddress(String PAddress) {
        this.PAddress = PAddress;
    }
    public String getCity1() {
        return this.city1;
    }
    
    public void setCity1(String city1) {
        this.city1 = city1;
    }
    public String getState1() {
        return this.state1;
    }
    
    public void setState1(String state1) {
        this.state1 = state1;
    }
    public String getZipCode1() {
        return this.zipCode1;
    }
    
    public void setZipCode1(String zipCode1) {
        this.zipCode1 = zipCode1;
    }
    public String getCountry1() {
        return this.country1;
    }
    
    public void setCountry1(String country1) {
        this.country1 = country1;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getMName() {
        return this.MName;
    }
    
    public void setMName(String MName) {
        this.MName = MName;
    }
    public String getSetVoter() {
        return this.setVoter;
    }
    
    public void setSetVoter(String setVoter) {
        this.setVoter = setVoter;
    }




}


