package com.myapp.struts.hbm;
// Generated Jun 16, 2011 5:12:32 PM by Hibernate Tools 3.2.1.GA



/**
 * VotingBallot generated by hbm2java
 */
public class VotingBallot  implements java.io.Serializable {


     private VotingBallotId id;

    public VotingBallot() {
    }

    public VotingBallot(VotingBallotId id) {
       this.id = id;
    }
   
    public VotingBallotId getId() {
        return this.id;
    }
    
    public void setId(VotingBallotId id) {
        this.id = id;
    }




}


