package in.ac.dei.edrp.pms.updation;

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="edittaskform"
 */
public class EditTaskForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** fields property */
//	private String taskId=null;
//	private String taskName=null;//for holding the task name
	private String taskStartDate=null;//for holding the schedule start date of task
	private String actualStartDate=null;//for holding the actual start date of task
	private String actualEndDate=null;//for holding the actual end date of task
	private String gantt_chart_color=null;//for holding the gantt chart colour
	private String status=null;//for holding the status of task
	private String remark=null;//for holding the remark of task
	private String taskDependency=null;//for holding the task dependency
	private String task_percentage_completion=null;//for holding the % completion of task
//	private String projAStartDate;
//	private String projAEndDate;
	private String project_code;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		
		}

//
//	public String getProjAEndDate() {
//		return projAEndDate;
//	}
//
//
//	public void setProjAEndDate(String projAEndDate) {
//		this.projAEndDate = projAEndDate;
//	}
//
//
//	public String getProjAStartDate() {
//		return projAStartDate;
//	}
//
//
//	public void setProjAStartDate(String projAStartDate) {
//		this.projAStartDate = projAStartDate;
//	}



	public String getTaskStartDate() {
		return taskStartDate;
	}


	public void setTaskStartDate(String taskStartDate) {
		this.taskStartDate = taskStartDate;
	}


	public String getActualStartDate() {
		return actualStartDate;
	}


	public void setActualStartDate(String actualStartDate) {
		this.actualStartDate = actualStartDate;
	}


	public String getActualEndDate() {
		return actualEndDate;
	}


	public void setActualEndDate(String actualEndDate) {
		this.actualEndDate = actualEndDate;
	}


	public String getGantt_chart_color() {
		return gantt_chart_color;
	}


	public void setGantt_chart_color(String gantt_chart_color) {
		this.gantt_chart_color = gantt_chart_color;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	public String getTaskDependency() {
		return taskDependency;
	}


	public void setTaskDependency(String taskDependency) {
		this.taskDependency = taskDependency;
	}


	public String getTask_percentage_completion() {
		return task_percentage_completion;
	}


	public void setTask_percentage_completion(String task_percentage_completion) {
		this.task_percentage_completion = task_percentage_completion;
	}


	public String getProject_code() {
		return project_code;
	}


	public void setProject_code(String project_code) {
		this.project_code = project_code;
	}


	public static long getSerialVersionUID() {
		return serialVersionUID;
	}
	

}