package com.myapp.struts.hbm;
// Generated Mar 18, 2011 7:00:13 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AcqBibliography generated by hbm2java
 */
public class AcqBibliography  implements java.io.Serializable {


     private AcqBibliographyId id;
     private String docType;
     private String title;
     private String publisherName;
     private String author;
     private String lccNo;
     private String series;
     private String subAuthor;
     private String subAuthor0;
     private String subAuthor1;
     private String subAuthor2;
     private String publishingYr;
     private String publishingPlace;
     private String edition;
     private String volume_no;


    public String getVolume_no() {
        return volume_no;
    }

    public void setVolume_no(String volume_no) {
        this.volume_no = volume_no;
    }
     private String isbn;
     private Set acqBibliographyDetailses = new HashSet(0);

    public AcqBibliography() {
    }

	
    public AcqBibliography(AcqBibliographyId id) {
        this.id = id;
    }
    public AcqBibliography(AcqBibliographyId id, String docType, String title, String publisherName, String author, String lccNo, String series, String subAuthor, String publishingYr, String publishingPlace, String edition, String isbn, Set acqBibliographyDetailses) {
       this.id = id;
       this.docType = docType;
       this.title = title;
       this.publisherName = publisherName;
       this.author = author;
       this.lccNo = lccNo;
       this.series = series;
       this.subAuthor = subAuthor;
       this.publishingYr = publishingYr;
       this.publishingPlace = publishingPlace;
       this.edition = edition;
       this.isbn = isbn;
       this.acqBibliographyDetailses = acqBibliographyDetailses;
    }
   
    public AcqBibliographyId getId() {
        return this.id;
    }
    
    public void setId(AcqBibliographyId id) {
        this.id = id;
    }
    public String getDocType() {
        return this.docType;
    }
    
    public void setDocType(String docType) {
        this.docType = docType;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublisherName() {
        return this.publisherName;
    }
    
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

      public String getSubAuthor0() {
        return subAuthor0;
    }

    public void setSubAuthor0(String subAuthor0) {
        this.subAuthor0 = subAuthor0;
    }

    public String getSubAuthor1() {
        return subAuthor1;
    }

    public void setSubAuthor1(String subAuthor1) {
        this.subAuthor1 = subAuthor1;
    }

    public String getSubAuthor2() {
        return subAuthor2;
    }

    public void setSubAuthor2(String subAuthor2) {
        this.subAuthor2 = subAuthor2;
    }


    public String getLccNo() {
        return this.lccNo;
    }
    
    public void setLccNo(String lccNo) {
        this.lccNo = lccNo;
    }
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
    public String getSubAuthor() {
        return this.subAuthor;
    }
    
    public void setSubAuthor(String subAuthor) {
        this.subAuthor = subAuthor;
    }
    public String getPublishingYr() {
        return this.publishingYr;
    }
    
    public void setPublishingYr(String publishingYr) {
        this.publishingYr = publishingYr;
    }
    public String getPublishingPlace() {
        return this.publishingPlace;
    }
    
    public void setPublishingPlace(String publishingPlace) {
        this.publishingPlace = publishingPlace;
    }
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public Set getAcqBibliographyDetailses() {
        return this.acqBibliographyDetailses;
    }
    
    public void setAcqBibliographyDetailses(Set acqBibliographyDetailses) {
        this.acqBibliographyDetailses = acqBibliographyDetailses;
    }




}


