package com.myapp.struts.hbm;
// Generated Jun 22, 2012 6:05:49 PM by Hibernate Tools 3.2.1.GA



/**
 * AcqRequestpaymentDetails generated by hbm2java
 */
public class AcqRequestpaymentDetails  implements java.io.Serializable {


     private AcqRequestpaymentDetailsId id;
     private String vendorId;
     private String totalAmt;
     private String status;
     private String orderNo;
     private String paymentUpdateDate;
     private String accessionStatus;
    public AcqRequestpaymentDetails() {
    }

	
    public AcqRequestpaymentDetails(AcqRequestpaymentDetailsId id) {
        this.id = id;
    }
    public AcqRequestpaymentDetails(AcqRequestpaymentDetailsId id, String vendorId, String totalAmt, String status,String orderNo,String paymentUpdateDate,String accessionStatus) {
       this.id = id;
       this.vendorId = vendorId;
       this.totalAmt = totalAmt;
       this.status = status;
       this.orderNo = orderNo;
       this.paymentUpdateDate = paymentUpdateDate;
       this.accessionStatus=accessionStatus;
    }
   
    public AcqRequestpaymentDetailsId getId() {
        return this.id;
    }
    
    public void setId(AcqRequestpaymentDetailsId id) {
        this.id = id;
    }
    public String getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(String vendorId) {
        this.vendorId = vendorId;
    }
    public String getTotalAmt() {
        return this.totalAmt;
    }
    
    public void setTotalAmt(String totalAmt) {
        this.totalAmt = totalAmt;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getPaymentUpdateDate() {
        return paymentUpdateDate;
    }

    public void setPaymentUpdateDate(String paymentUpdateDate) {
        this.paymentUpdateDate = paymentUpdateDate;
    }

    public String getAccessionStatus() {
        return accessionStatus;
    }

    public void setAccessionStatus(String accessionStatus) {
        this.accessionStatus = accessionStatus;
    }

    


}


