package com.myapp.struts.hbm;
// Generated 8 Aug, 2011 11:27:34 AM by Hibernate Tools 3.2.1.GA



/**
 * AcqRecievingHeaderId generated by hbm2java
 */
public class AcqRecievingHeaderId  implements java.io.Serializable {


     private String libraryId;
     private String subLibraryId;
     private String recievingNo;

    public AcqRecievingHeaderId() {
    }

    public AcqRecievingHeaderId(String libraryId, String subLibraryId, String recievingNo) {
       this.libraryId = libraryId;
       this.subLibraryId = subLibraryId;
       this.recievingNo = recievingNo;
    }
   
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public String getSubLibraryId() {
        return this.subLibraryId;
    }
    
    public void setSubLibraryId(String subLibraryId) {
        this.subLibraryId = subLibraryId;
    }
    public String getRecievingNo() {
        return this.recievingNo;
    }
    
    public void setRecievingNo(String recievingNo) {
        this.recievingNo = recievingNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AcqRecievingHeaderId) ) return false;
		 AcqRecievingHeaderId castOther = ( AcqRecievingHeaderId ) other; 
         
		 return ( (this.getLibraryId()==castOther.getLibraryId()) || ( this.getLibraryId()!=null && castOther.getLibraryId()!=null && this.getLibraryId().equals(castOther.getLibraryId()) ) )
 && ( (this.getSubLibraryId()==castOther.getSubLibraryId()) || ( this.getSubLibraryId()!=null && castOther.getSubLibraryId()!=null && this.getSubLibraryId().equals(castOther.getSubLibraryId()) ) )
 && ( (this.getRecievingNo()==castOther.getRecievingNo()) || ( this.getRecievingNo()!=null && castOther.getRecievingNo()!=null && this.getRecievingNo().equals(castOther.getRecievingNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLibraryId() == null ? 0 : this.getLibraryId().hashCode() );
         result = 37 * result + ( getSubLibraryId() == null ? 0 : this.getSubLibraryId().hashCode() );
         result = 37 * result + ( getRecievingNo() == null ? 0 : this.getRecievingNo().hashCode() );
         return result;
   }   


}


