package com.myapp.struts.hbm;
// Generated Apr 19, 2011 4:03:37 PM by Hibernate Tools 3.2.1.GA



/**
 * Biblio generated by hbm2java
 */
public class Biblio  implements java.io.Serializable {


     private BiblioId id;
     private String sublibraryId;
     private Character indicator1;
     private Character indicator2;
     private String $a;
     private String $b;
     private String $c;
     private String $d;
     private String $e;
     private String $f;
     private String $g;
     private String $h;
     private String $i;
     private String $j;
     private String $k;
     private String $l;
     private String $m;
     private String $n;
     private String $o;
     private String $p;
     private String $q;
     private String $r;
     private String $s;
     private String $t;
     private String $u;
     private String $v;
     private String $w;
     private String $x;
     private String $y;
     private String $z;
     private String $0;
     private String $1;
     private String $2;
     private String $3;
     private String $4;
     private String $5;
     private String $6;
     private String $7;
     private String $8;
     private String $9;

    public Biblio() {
    }

	
    public Biblio(BiblioId id, String sublibraryId) {
        this.id = id;
        this.sublibraryId = sublibraryId;
    }
    public Biblio(BiblioId id, String sublibraryId, Character indicator1, Character indicator2, String $a, String $b, String $c, String $d, String $e, String $f, String $g, String $h, String $i, String $j, String $k, String $l, String $m, String $n, String $o, String $p, String $q, String $r, String $s, String $t, String $u, String $v, String $w, String $x, String $y, String $z, String $0, String $1, String $2, String $3, String $4, String $5, String $6, String $7, String $8, String $9) {
       this.id = id;
       this.sublibraryId = sublibraryId;
       this.indicator1 = indicator1;
       this.indicator2 = indicator2;
       this.$a = $a;
       this.$b = $b;
       this.$c = $c;
       this.$d = $d;
       this.$e = $e;
       this.$f = $f;
       this.$g = $g;
       this.$h = $h;
       this.$i = $i;
       this.$j = $j;
       this.$k = $k;
       this.$l = $l;
       this.$m = $m;
       this.$n = $n;
       this.$o = $o;
       this.$p = $p;
       this.$q = $q;
       this.$r = $r;
       this.$s = $s;
       this.$t = $t;
       this.$u = $u;
       this.$v = $v;
       this.$w = $w;
       this.$x = $x;
       this.$y = $y;
       this.$z = $z;
       this.$0 = $0;
       this.$1 = $1;
       this.$2 = $2;
       this.$3 = $3;
       this.$4 = $4;
       this.$5 = $5;
       this.$6 = $6;
       this.$7 = $7;
       this.$8 = $8;
       this.$9 = $9;
    }
   
    public BiblioId getId() {
        return this.id;
    }
    
    public void setId(BiblioId id) {
        this.id = id;
    }
    public String getSublibraryId() {
        return this.sublibraryId;
    }
    
    public void setSublibraryId(String sublibraryId) {
        this.sublibraryId = sublibraryId;
    }
    public Character getIndicator1() {
        return this.indicator1;
    }
    
    public void setIndicator1(Character indicator1) {
        this.indicator1 = indicator1;
    }
    public Character getIndicator2() {
        return this.indicator2;
    }
    
    public void setIndicator2(Character indicator2) {
        this.indicator2 = indicator2;
    }
    public String get$a() {
        return this.$a;
    }
    
    public void set$a(String $a) {
        this.$a = $a;
    }
    public String get$b() {
        return this.$b;
    }
    
    public void set$b(String $b) {
        this.$b = $b;
    }
    public String get$c() {
        return this.$c;
    }
    
    public void set$c(String $c) {
        this.$c = $c;
    }
    public String get$d() {
        return this.$d;
    }
    
    public void set$d(String $d) {
        this.$d = $d;
    }
    public String get$e() {
        return this.$e;
    }
    
    public void set$e(String $e) {
        this.$e = $e;
    }
    public String get$f() {
        return this.$f;
    }
    
    public void set$f(String $f) {
        this.$f = $f;
    }
    public String get$g() {
        return this.$g;
    }
    
    public void set$g(String $g) {
        this.$g = $g;
    }
    public String get$h() {
        return this.$h;
    }
    
    public void set$h(String $h) {
        this.$h = $h;
    }
    public String get$i() {
        return this.$i;
    }
    
    public void set$i(String $i) {
        this.$i = $i;
    }
    public String get$j() {
        return this.$j;
    }
    
    public void set$j(String $j) {
        this.$j = $j;
    }
    public String get$k() {
        return this.$k;
    }
    
    public void set$k(String $k) {
        this.$k = $k;
    }
    public String get$l() {
        return this.$l;
    }
    
    public void set$l(String $l) {
        this.$l = $l;
    }
    public String get$m() {
        return this.$m;
    }
    
    public void set$m(String $m) {
        this.$m = $m;
    }
    public String get$n() {
        return this.$n;
    }
    
    public void set$n(String $n) {
        this.$n = $n;
    }
    public String get$o() {
        return this.$o;
    }
    
    public void set$o(String $o) {
        this.$o = $o;
    }
    public String get$p() {
        return this.$p;
    }
    
    public void set$p(String $p) {
        this.$p = $p;
    }
    public String get$q() {
        return this.$q;
    }
    
    public void set$q(String $q) {
        this.$q = $q;
    }
    public String get$r() {
        return this.$r;
    }
    
    public void set$r(String $r) {
        this.$r = $r;
    }
    public String get$s() {
        return this.$s;
    }
    
    public void set$s(String $s) {
        this.$s = $s;
    }
    public String get$t() {
        return this.$t;
    }
    
    public void set$t(String $t) {
        this.$t = $t;
    }
    public String get$u() {
        return this.$u;
    }
    
    public void set$u(String $u) {
        this.$u = $u;
    }
    public String get$v() {
        return this.$v;
    }
    
    public void set$v(String $v) {
        this.$v = $v;
    }
    public String get$w() {
        return this.$w;
    }
    
    public void set$w(String $w) {
        this.$w = $w;
    }
    public String get$x() {
        return this.$x;
    }
    
    public void set$x(String $x) {
        this.$x = $x;
    }
    public String get$y() {
        return this.$y;
    }
    
    public void set$y(String $y) {
        this.$y = $y;
    }
    public String get$z() {
        return this.$z;
    }
    
    public void set$z(String $z) {
        this.$z = $z;
    }
    public String get$0() {
        return this.$0;
    }
    
    public void set$0(String $0) {
        this.$0 = $0;
    }
    public String get$1() {
        return this.$1;
    }
    
    public void set$1(String $1) {
        this.$1 = $1;
    }
    public String get$2() {
        return this.$2;
    }
    
    public void set$2(String $2) {
        this.$2 = $2;
    }
    public String get$3() {
        return this.$3;
    }
    
    public void set$3(String $3) {
        this.$3 = $3;
    }
    public String get$4() {
        return this.$4;
    }
    
    public void set$4(String $4) {
        this.$4 = $4;
    }
    public String get$5() {
        return this.$5;
    }
    
    public void set$5(String $5) {
        this.$5 = $5;
    }
    public String get$6() {
        return this.$6;
    }
    
    public void set$6(String $6) {
        this.$6 = $6;
    }
    public String get$7() {
        return this.$7;
    }
    
    public void set$7(String $7) {
        this.$7 = $7;
    }
    public String get$8() {
        return this.$8;
    }
    
    public void set$8(String $8) {
        this.$8 = $8;
    }
    public String get$9() {
        return this.$9;
    }
    
    public void set$9(String $9) {
        this.$9 = $9;
    }




}


