package com.myapp.struts.hbm;
// Generated May 2, 2011 12:00:18 PM by Hibernate Tools 3.2.1.GA



/**
 * CirCheckinId generated by hbm2java
 */
public class CirCheckinId  implements java.io.Serializable {


     private String checkinId;
     private String libraryId;
     private String sublibraryId;

    public CirCheckinId() {
    }

    public CirCheckinId(String checkinId, String libraryId, String sublibraryId) {
       this.checkinId = checkinId;
       this.libraryId = libraryId;
       this.sublibraryId = sublibraryId;
    }
   
    public String getCheckinId() {
        return this.checkinId;
    }
    
    public void setCheckinId(String checkinId) {
        this.checkinId = checkinId;
    }
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public String getSublibraryId() {
        return this.sublibraryId;
    }
    
    public void setSublibraryId(String sublibraryId) {
        this.sublibraryId = sublibraryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CirCheckinId) ) return false;
		 CirCheckinId castOther = ( CirCheckinId ) other; 
         
		 return ( (this.getCheckinId()==castOther.getCheckinId()) || ( this.getCheckinId()!=null && castOther.getCheckinId()!=null && this.getCheckinId().equals(castOther.getCheckinId()) ) )
 && ( (this.getLibraryId()==castOther.getLibraryId()) || ( this.getLibraryId()!=null && castOther.getLibraryId()!=null && this.getLibraryId().equals(castOther.getLibraryId()) ) )
 && ( (this.getSublibraryId()==castOther.getSublibraryId()) || ( this.getSublibraryId()!=null && castOther.getSublibraryId()!=null && this.getSublibraryId().equals(castOther.getSublibraryId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCheckinId() == null ? 0 : this.getCheckinId().hashCode() );
         result = 37 * result + ( getLibraryId() == null ? 0 : this.getLibraryId().hashCode() );
         result = 37 * result + ( getSublibraryId() == null ? 0 : this.getSublibraryId().hashCode() );
         return result;
   }   


}


