package com.myapp.struts.hbm;
// Generated May 2, 2011 12:00:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;

/**
 * CirMemberDetail generated by hbm2java
 */
public class CirMemberDetail  implements java.io.Serializable {


     private CirMemberDetailId id;
       private String college;
     private String collAddress;
     private String tempStatus;

    public String getCollAddress() {
        return collAddress;
    }

    public void setCollAddress(String collAddress) {
        this.collAddress = collAddress;
    }

    public String getCollege() {
        return college;
    }

    public void setCollege(String college) {
        this.college = college;
    }

    public String getTempStatus() {
        return tempStatus;
    }

    public void setTempStatus(String tempStatus) {
        this.tempStatus = tempStatus;
    }

     private Library library;
     private String fname;
     private String mname;
     private String lname;
     private String address1;
     private String address2;
     private String city1;
     private String state1;
     private String pin1;
     private String country1;
     private String city2;
     private String state2;
     private String pin2;
     private String country2;
     private String email;
     private String fax;
     private String phone1;
     private String phone2;
     private String location;
     private byte[] image;
     private java.awt.image.BufferedImage image1;
     private String createdBy;
     private Set cirOpacRequests = new HashSet(0);
     private Set cirMemberAccounts = new HashSet(0);

    public CirMemberDetail() {
    }

	
    public CirMemberDetail(CirMemberDetailId id, Library library) {
        this.id = id;
        this.library = library;
    }
    public CirMemberDetail(CirMemberDetailId id, Library library, String fname, String mname, String lname, String address1, String address2, String city1, String state1, String pin1, String country1, String city2, String state2, String pin2, String country2, String email, String fax, String phone1, String phone2, String location, byte[] image, String createdBy, Set cirOpacRequests, Set cirMemberAccounts) {
       this.id = id;
       this.library = library;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.address1 = address1;
       this.address2 = address2;
       this.city1 = city1;
       this.state1 = state1;
       this.pin1 = pin1;
       this.country1 = country1;
       this.city2 = city2;
       this.state2 = state2;
       this.pin2 = pin2;
       this.country2 = country2;
       this.email = email;
       this.fax = fax;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.location = location;
       this.image = image;
       this.createdBy = createdBy;
       this.cirOpacRequests = cirOpacRequests;
       this.cirMemberAccounts = cirMemberAccounts;
    }

    public BufferedImage getImage1() {
        InputStream in = new ByteArrayInputStream(this.image);
	try{
        image1 = ImageIO.read(in);
        }catch(Exception e){}

        return image1;
    }

    public void setImage1(BufferedImage image1) {
        this.image1 = image1;
    }

    public CirMemberDetailId getId() {
        return this.id;
    }
    
    public void setId(CirMemberDetailId id) {
        this.id = id;
    }
    public Library getLibrary() {
        return this.library;
    }
    
    public void setLibrary(Library library) {
        this.library = library;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity1() {
        return this.city1;
    }
    
    public void setCity1(String city1) {
        this.city1 = city1;
    }
    public String getState1() {
        return this.state1;
    }
    
    public void setState1(String state1) {
        this.state1 = state1;
    }
    public String getPin1() {
        return this.pin1;
    }
    
    public void setPin1(String pin1) {
        this.pin1 = pin1;
    }
    public String getCountry1() {
        return this.country1;
    }
    
    public void setCountry1(String country1) {
        this.country1 = country1;
    }
    public String getCity2() {
        return this.city2;
    }
    
    public void setCity2(String city2) {
        this.city2 = city2;
    }
    public String getState2() {
        return this.state2;
    }
    
    public void setState2(String state2) {
        this.state2 = state2;
    }
    public String getPin2() {
        return this.pin2;
    }
    
    public void setPin2(String pin2) {
        this.pin2 = pin2;
    }
    public String getCountry2() {
        return this.country2;
    }
    
    public void setCountry2(String country2) {
        this.country2 = country2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Set getCirOpacRequests() {
        return this.cirOpacRequests;
    }
    
    public void setCirOpacRequests(Set cirOpacRequests) {
        this.cirOpacRequests = cirOpacRequests;
    }
    public Set getCirMemberAccounts() {
        return this.cirMemberAccounts;
    }
    
    public void setCirMemberAccounts(Set cirMemberAccounts) {
        this.cirMemberAccounts = cirMemberAccounts;
    }




}


