package com.myapp.struts.hbm;
// Generated May 2, 2011 12:00:18 PM by Hibernate Tools 3.2.1.GA



/**
 * CirPrivilege generated by hbm2java
 */
public class CirPrivilege  implements java.io.Serializable {


     private CirPrivilegeId id;
     private StaffDetail staffDetail;
     private String sublibraryId;
     private String cir301;
     private String cir302;
     private String cir303;
     private String cir304;
     private String cir305;
     private String cir306;
     private String cir307;
     private String cir308;
     private String cir309;
     private String cir310;
     private String cir311;
     private String cir312;
     private String cir313;
     private String cir314;
     private String cir315;
     private String cir316;
     private String cir317;
     private String cir318;
     private String cir319;
     private String cir320;
     private String cir321;
     private String cir322;
     private String cir323;
     private String cir324;
     private String cir325;
     private String cir326;
     private String cir327;
     private String cir328;
     private String cir329;
     private String cir330;
     private String cir331;
     private String cir332;
     private String cir333;
     private String cir334;
     private String cir335;
     private String cir336;
     private String cir337;
     private String cir338;
     private String cir339;
     private String cir340;
     private String cir341;
     private String cir342;
     private String cir343;
     private String cir344;
     private String cir345;
     private String cir346;
     private String cir347;
     private String cir348;
     private String cir349;
     private String cir350;
     private String cir351;
     private String cir352;
     private String cir353;
     private String cir354;
     private String cir355;
     private String cir356;
     private String cir357;
     private String cir358;
     private String cir359;
     private String cir360;
     private String cir361;
     private String cir362;
     private String cir363;
     private String cir364;
     private String cir365;
     private String cir366;
     private String cir367;
     private String cir368;
     private String cir369;
     private String cir370;
     private String cir371;
     private String cir372;
     private String cir373;
     private String cir374;
     private String cir375;
     private String cir376;
     private String cir377;
     private String cir378;
     private String cir379;
     private String cir380;
     private String cir381;
     private String cir382;
     private String cir383;
     private String cir384;
     private String cir385;
     private String cir386;
     private String cir387;
     private String cir388;
     private String cir389;
     private String cir390;
     private String cir391;
     private String cir392;
     private String cir393;
     private String cir394;
     private String cir395;
     private String cir396;
     private String cir397;
     private String cir398;
     private String cir399;

    public CirPrivilege() {
    }

	
    public CirPrivilege(CirPrivilegeId id, StaffDetail staffDetail, String sublibraryId) {
        this.id = id;
        this.staffDetail = staffDetail;
        this.sublibraryId = sublibraryId;
    }
    public CirPrivilege(CirPrivilegeId id, StaffDetail staffDetail, String sublibraryId, String cir301, String cir302, String cir303, String cir304, String cir305, String cir306, String cir307, String cir308, String cir309, String cir310, String cir311, String cir312, String cir313, String cir314, String cir315, String cir316, String cir317, String cir318, String cir319, String cir320, String cir321, String cir322, String cir323, String cir324, String cir325, String cir326, String cir327, String cir328, String cir329, String cir330, String cir331, String cir332, String cir333, String cir334, String cir335, String cir336, String cir337, String cir338, String cir339, String cir340, String cir341, String cir342, String cir343, String cir344, String cir345, String cir346, String cir347, String cir348, String cir349, String cir350, String cir351, String cir352, String cir353, String cir354, String cir355, String cir356, String cir357, String cir358, String cir359, String cir360, String cir361, String cir362, String cir363, String cir364, String cir365, String cir366, String cir367, String cir368, String cir369, String cir370, String cir371, String cir372, String cir373, String cir374, String cir375, String cir376, String cir377, String cir378, String cir379, String cir380, String cir381, String cir382, String cir383, String cir384, String cir385, String cir386, String cir387, String cir388, String cir389, String cir390, String cir391, String cir392, String cir393, String cir394, String cir395, String cir396, String cir397, String cir398, String cir399) {
       this.id = id;
       this.staffDetail = staffDetail;
       this.sublibraryId = sublibraryId;
       this.cir301 = cir301;
       this.cir302 = cir302;
       this.cir303 = cir303;
       this.cir304 = cir304;
       this.cir305 = cir305;
       this.cir306 = cir306;
       this.cir307 = cir307;
       this.cir308 = cir308;
       this.cir309 = cir309;
       this.cir310 = cir310;
       this.cir311 = cir311;
       this.cir312 = cir312;
       this.cir313 = cir313;
       this.cir314 = cir314;
       this.cir315 = cir315;
       this.cir316 = cir316;
       this.cir317 = cir317;
       this.cir318 = cir318;
       this.cir319 = cir319;
       this.cir320 = cir320;
       this.cir321 = cir321;
       this.cir322 = cir322;
       this.cir323 = cir323;
       this.cir324 = cir324;
       this.cir325 = cir325;
       this.cir326 = cir326;
       this.cir327 = cir327;
       this.cir328 = cir328;
       this.cir329 = cir329;
       this.cir330 = cir330;
       this.cir331 = cir331;
       this.cir332 = cir332;
       this.cir333 = cir333;
       this.cir334 = cir334;
       this.cir335 = cir335;
       this.cir336 = cir336;
       this.cir337 = cir337;
       this.cir338 = cir338;
       this.cir339 = cir339;
       this.cir340 = cir340;
       this.cir341 = cir341;
       this.cir342 = cir342;
       this.cir343 = cir343;
       this.cir344 = cir344;
       this.cir345 = cir345;
       this.cir346 = cir346;
       this.cir347 = cir347;
       this.cir348 = cir348;
       this.cir349 = cir349;
       this.cir350 = cir350;
       this.cir351 = cir351;
       this.cir352 = cir352;
       this.cir353 = cir353;
       this.cir354 = cir354;
       this.cir355 = cir355;
       this.cir356 = cir356;
       this.cir357 = cir357;
       this.cir358 = cir358;
       this.cir359 = cir359;
       this.cir360 = cir360;
       this.cir361 = cir361;
       this.cir362 = cir362;
       this.cir363 = cir363;
       this.cir364 = cir364;
       this.cir365 = cir365;
       this.cir366 = cir366;
       this.cir367 = cir367;
       this.cir368 = cir368;
       this.cir369 = cir369;
       this.cir370 = cir370;
       this.cir371 = cir371;
       this.cir372 = cir372;
       this.cir373 = cir373;
       this.cir374 = cir374;
       this.cir375 = cir375;
       this.cir376 = cir376;
       this.cir377 = cir377;
       this.cir378 = cir378;
       this.cir379 = cir379;
       this.cir380 = cir380;
       this.cir381 = cir381;
       this.cir382 = cir382;
       this.cir383 = cir383;
       this.cir384 = cir384;
       this.cir385 = cir385;
       this.cir386 = cir386;
       this.cir387 = cir387;
       this.cir388 = cir388;
       this.cir389 = cir389;
       this.cir390 = cir390;
       this.cir391 = cir391;
       this.cir392 = cir392;
       this.cir393 = cir393;
       this.cir394 = cir394;
       this.cir395 = cir395;
       this.cir396 = cir396;
       this.cir397 = cir397;
       this.cir398 = cir398;
       this.cir399 = cir399;
    }
   
    public CirPrivilegeId getId() {
        return this.id;
    }
    
    public void setId(CirPrivilegeId id) {
        this.id = id;
    }
    public StaffDetail getStaffDetail() {
        return this.staffDetail;
    }
    
    public void setStaffDetail(StaffDetail staffDetail) {
        this.staffDetail = staffDetail;
    }
    public String getSublibraryId() {
        return this.sublibraryId;
    }
    
    public void setSublibraryId(String sublibraryId) {
        this.sublibraryId = sublibraryId;
    }
    public String getCir301() {
        return this.cir301;
    }
    
    public void setCir301(String cir301) {
        this.cir301 = cir301;
    }
    public String getCir302() {
        return this.cir302;
    }
    
    public void setCir302(String cir302) {
        this.cir302 = cir302;
    }
    public String getCir303() {
        return this.cir303;
    }
    
    public void setCir303(String cir303) {
        this.cir303 = cir303;
    }
    public String getCir304() {
        return this.cir304;
    }
    
    public void setCir304(String cir304) {
        this.cir304 = cir304;
    }
    public String getCir305() {
        return this.cir305;
    }
    
    public void setCir305(String cir305) {
        this.cir305 = cir305;
    }
    public String getCir306() {
        return this.cir306;
    }
    
    public void setCir306(String cir306) {
        this.cir306 = cir306;
    }
    public String getCir307() {
        return this.cir307;
    }
    
    public void setCir307(String cir307) {
        this.cir307 = cir307;
    }
    public String getCir308() {
        return this.cir308;
    }
    
    public void setCir308(String cir308) {
        this.cir308 = cir308;
    }
    public String getCir309() {
        return this.cir309;
    }
    
    public void setCir309(String cir309) {
        this.cir309 = cir309;
    }
    public String getCir310() {
        return this.cir310;
    }
    
    public void setCir310(String cir310) {
        this.cir310 = cir310;
    }
    public String getCir311() {
        return this.cir311;
    }
    
    public void setCir311(String cir311) {
        this.cir311 = cir311;
    }
    public String getCir312() {
        return this.cir312;
    }
    
    public void setCir312(String cir312) {
        this.cir312 = cir312;
    }
    public String getCir313() {
        return this.cir313;
    }
    
    public void setCir313(String cir313) {
        this.cir313 = cir313;
    }
    public String getCir314() {
        return this.cir314;
    }
    
    public void setCir314(String cir314) {
        this.cir314 = cir314;
    }
    public String getCir315() {
        return this.cir315;
    }
    
    public void setCir315(String cir315) {
        this.cir315 = cir315;
    }
    public String getCir316() {
        return this.cir316;
    }
    
    public void setCir316(String cir316) {
        this.cir316 = cir316;
    }
    public String getCir317() {
        return this.cir317;
    }
    
    public void setCir317(String cir317) {
        this.cir317 = cir317;
    }
    public String getCir318() {
        return this.cir318;
    }
    
    public void setCir318(String cir318) {
        this.cir318 = cir318;
    }
    public String getCir319() {
        return this.cir319;
    }
    
    public void setCir319(String cir319) {
        this.cir319 = cir319;
    }
    public String getCir320() {
        return this.cir320;
    }
    
    public void setCir320(String cir320) {
        this.cir320 = cir320;
    }
    public String getCir321() {
        return this.cir321;
    }
    
    public void setCir321(String cir321) {
        this.cir321 = cir321;
    }
    public String getCir322() {
        return this.cir322;
    }
    
    public void setCir322(String cir322) {
        this.cir322 = cir322;
    }
    public String getCir323() {
        return this.cir323;
    }
    
    public void setCir323(String cir323) {
        this.cir323 = cir323;
    }
    public String getCir324() {
        return this.cir324;
    }
    
    public void setCir324(String cir324) {
        this.cir324 = cir324;
    }
    public String getCir325() {
        return this.cir325;
    }
    
    public void setCir325(String cir325) {
        this.cir325 = cir325;
    }
    public String getCir326() {
        return this.cir326;
    }
    
    public void setCir326(String cir326) {
        this.cir326 = cir326;
    }
    public String getCir327() {
        return this.cir327;
    }
    
    public void setCir327(String cir327) {
        this.cir327 = cir327;
    }
    public String getCir328() {
        return this.cir328;
    }
    
    public void setCir328(String cir328) {
        this.cir328 = cir328;
    }
    public String getCir329() {
        return this.cir329;
    }
    
    public void setCir329(String cir329) {
        this.cir329 = cir329;
    }
    public String getCir330() {
        return this.cir330;
    }
    
    public void setCir330(String cir330) {
        this.cir330 = cir330;
    }
    public String getCir331() {
        return this.cir331;
    }
    
    public void setCir331(String cir331) {
        this.cir331 = cir331;
    }
    public String getCir332() {
        return this.cir332;
    }
    
    public void setCir332(String cir332) {
        this.cir332 = cir332;
    }
    public String getCir333() {
        return this.cir333;
    }
    
    public void setCir333(String cir333) {
        this.cir333 = cir333;
    }
    public String getCir334() {
        return this.cir334;
    }
    
    public void setCir334(String cir334) {
        this.cir334 = cir334;
    }
    public String getCir335() {
        return this.cir335;
    }
    
    public void setCir335(String cir335) {
        this.cir335 = cir335;
    }
    public String getCir336() {
        return this.cir336;
    }
    
    public void setCir336(String cir336) {
        this.cir336 = cir336;
    }
    public String getCir337() {
        return this.cir337;
    }
    
    public void setCir337(String cir337) {
        this.cir337 = cir337;
    }
    public String getCir338() {
        return this.cir338;
    }
    
    public void setCir338(String cir338) {
        this.cir338 = cir338;
    }
    public String getCir339() {
        return this.cir339;
    }
    
    public void setCir339(String cir339) {
        this.cir339 = cir339;
    }
    public String getCir340() {
        return this.cir340;
    }
    
    public void setCir340(String cir340) {
        this.cir340 = cir340;
    }
    public String getCir341() {
        return this.cir341;
    }
    
    public void setCir341(String cir341) {
        this.cir341 = cir341;
    }
    public String getCir342() {
        return this.cir342;
    }
    
    public void setCir342(String cir342) {
        this.cir342 = cir342;
    }
    public String getCir343() {
        return this.cir343;
    }
    
    public void setCir343(String cir343) {
        this.cir343 = cir343;
    }
    public String getCir344() {
        return this.cir344;
    }
    
    public void setCir344(String cir344) {
        this.cir344 = cir344;
    }
    public String getCir345() {
        return this.cir345;
    }
    
    public void setCir345(String cir345) {
        this.cir345 = cir345;
    }
    public String getCir346() {
        return this.cir346;
    }
    
    public void setCir346(String cir346) {
        this.cir346 = cir346;
    }
    public String getCir347() {
        return this.cir347;
    }
    
    public void setCir347(String cir347) {
        this.cir347 = cir347;
    }
    public String getCir348() {
        return this.cir348;
    }
    
    public void setCir348(String cir348) {
        this.cir348 = cir348;
    }
    public String getCir349() {
        return this.cir349;
    }
    
    public void setCir349(String cir349) {
        this.cir349 = cir349;
    }
    public String getCir350() {
        return this.cir350;
    }
    
    public void setCir350(String cir350) {
        this.cir350 = cir350;
    }
    public String getCir351() {
        return this.cir351;
    }
    
    public void setCir351(String cir351) {
        this.cir351 = cir351;
    }
    public String getCir352() {
        return this.cir352;
    }
    
    public void setCir352(String cir352) {
        this.cir352 = cir352;
    }
    public String getCir353() {
        return this.cir353;
    }
    
    public void setCir353(String cir353) {
        this.cir353 = cir353;
    }
    public String getCir354() {
        return this.cir354;
    }
    
    public void setCir354(String cir354) {
        this.cir354 = cir354;
    }
    public String getCir355() {
        return this.cir355;
    }
    
    public void setCir355(String cir355) {
        this.cir355 = cir355;
    }
    public String getCir356() {
        return this.cir356;
    }
    
    public void setCir356(String cir356) {
        this.cir356 = cir356;
    }
    public String getCir357() {
        return this.cir357;
    }
    
    public void setCir357(String cir357) {
        this.cir357 = cir357;
    }
    public String getCir358() {
        return this.cir358;
    }
    
    public void setCir358(String cir358) {
        this.cir358 = cir358;
    }
    public String getCir359() {
        return this.cir359;
    }
    
    public void setCir359(String cir359) {
        this.cir359 = cir359;
    }
    public String getCir360() {
        return this.cir360;
    }
    
    public void setCir360(String cir360) {
        this.cir360 = cir360;
    }
    public String getCir361() {
        return this.cir361;
    }
    
    public void setCir361(String cir361) {
        this.cir361 = cir361;
    }
    public String getCir362() {
        return this.cir362;
    }
    
    public void setCir362(String cir362) {
        this.cir362 = cir362;
    }
    public String getCir363() {
        return this.cir363;
    }
    
    public void setCir363(String cir363) {
        this.cir363 = cir363;
    }
    public String getCir364() {
        return this.cir364;
    }
    
    public void setCir364(String cir364) {
        this.cir364 = cir364;
    }
    public String getCir365() {
        return this.cir365;
    }
    
    public void setCir365(String cir365) {
        this.cir365 = cir365;
    }
    public String getCir366() {
        return this.cir366;
    }
    
    public void setCir366(String cir366) {
        this.cir366 = cir366;
    }
    public String getCir367() {
        return this.cir367;
    }
    
    public void setCir367(String cir367) {
        this.cir367 = cir367;
    }
    public String getCir368() {
        return this.cir368;
    }
    
    public void setCir368(String cir368) {
        this.cir368 = cir368;
    }
    public String getCir369() {
        return this.cir369;
    }
    
    public void setCir369(String cir369) {
        this.cir369 = cir369;
    }
    public String getCir370() {
        return this.cir370;
    }
    
    public void setCir370(String cir370) {
        this.cir370 = cir370;
    }
    public String getCir371() {
        return this.cir371;
    }
    
    public void setCir371(String cir371) {
        this.cir371 = cir371;
    }
    public String getCir372() {
        return this.cir372;
    }
    
    public void setCir372(String cir372) {
        this.cir372 = cir372;
    }
    public String getCir373() {
        return this.cir373;
    }
    
    public void setCir373(String cir373) {
        this.cir373 = cir373;
    }
    public String getCir374() {
        return this.cir374;
    }
    
    public void setCir374(String cir374) {
        this.cir374 = cir374;
    }
    public String getCir375() {
        return this.cir375;
    }
    
    public void setCir375(String cir375) {
        this.cir375 = cir375;
    }
    public String getCir376() {
        return this.cir376;
    }
    
    public void setCir376(String cir376) {
        this.cir376 = cir376;
    }
    public String getCir377() {
        return this.cir377;
    }
    
    public void setCir377(String cir377) {
        this.cir377 = cir377;
    }
    public String getCir378() {
        return this.cir378;
    }
    
    public void setCir378(String cir378) {
        this.cir378 = cir378;
    }
    public String getCir379() {
        return this.cir379;
    }
    
    public void setCir379(String cir379) {
        this.cir379 = cir379;
    }
    public String getCir380() {
        return this.cir380;
    }
    
    public void setCir380(String cir380) {
        this.cir380 = cir380;
    }
    public String getCir381() {
        return this.cir381;
    }
    
    public void setCir381(String cir381) {
        this.cir381 = cir381;
    }
    public String getCir382() {
        return this.cir382;
    }
    
    public void setCir382(String cir382) {
        this.cir382 = cir382;
    }
    public String getCir383() {
        return this.cir383;
    }
    
    public void setCir383(String cir383) {
        this.cir383 = cir383;
    }
    public String getCir384() {
        return this.cir384;
    }
    
    public void setCir384(String cir384) {
        this.cir384 = cir384;
    }
    public String getCir385() {
        return this.cir385;
    }
    
    public void setCir385(String cir385) {
        this.cir385 = cir385;
    }
    public String getCir386() {
        return this.cir386;
    }
    
    public void setCir386(String cir386) {
        this.cir386 = cir386;
    }
    public String getCir387() {
        return this.cir387;
    }
    
    public void setCir387(String cir387) {
        this.cir387 = cir387;
    }
    public String getCir388() {
        return this.cir388;
    }
    
    public void setCir388(String cir388) {
        this.cir388 = cir388;
    }
    public String getCir389() {
        return this.cir389;
    }
    
    public void setCir389(String cir389) {
        this.cir389 = cir389;
    }
    public String getCir390() {
        return this.cir390;
    }
    
    public void setCir390(String cir390) {
        this.cir390 = cir390;
    }
    public String getCir391() {
        return this.cir391;
    }
    
    public void setCir391(String cir391) {
        this.cir391 = cir391;
    }
    public String getCir392() {
        return this.cir392;
    }
    
    public void setCir392(String cir392) {
        this.cir392 = cir392;
    }
    public String getCir393() {
        return this.cir393;
    }
    
    public void setCir393(String cir393) {
        this.cir393 = cir393;
    }
    public String getCir394() {
        return this.cir394;
    }
    
    public void setCir394(String cir394) {
        this.cir394 = cir394;
    }
    public String getCir395() {
        return this.cir395;
    }
    
    public void setCir395(String cir395) {
        this.cir395 = cir395;
    }
    public String getCir396() {
        return this.cir396;
    }
    
    public void setCir396(String cir396) {
        this.cir396 = cir396;
    }
    public String getCir397() {
        return this.cir397;
    }
    
    public void setCir397(String cir397) {
        this.cir397 = cir397;
    }
    public String getCir398() {
        return this.cir398;
    }
    
    public void setCir398(String cir398) {
        this.cir398 = cir398;
    }
    public String getCir399() {
        return this.cir399;
    }
    
    public void setCir399(String cir399) {
        this.cir399 = cir399;
    }




}


