package com.myapp.struts.hbm;
// Generated Jun 27, 2011 3:30:26 PM by Hibernate Tools 3.2.1.GA



/**
 * CustomizedbiblioId generated by hbm2java
 */
public class CustomizedbiblioId  implements java.io.Serializable {


     private String libraryId;
     private int bibId;
     private String marctag;

    public CustomizedbiblioId() {
    }

    public CustomizedbiblioId(String libraryId, int bibId, String marctag) {
       this.libraryId = libraryId;
       this.bibId = bibId;
       this.marctag = marctag;
    }
   
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public int getBibId() {
        return this.bibId;
    }
    
    public void setBibId(int bibId) {
        this.bibId = bibId;
    }
    public String getMarctag() {
        return this.marctag;
    }
    
    public void setMarctag(String marctag) {
        this.marctag = marctag;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomizedbiblioId) ) return false;
		 CustomizedbiblioId castOther = ( CustomizedbiblioId ) other; 
         
		 return ( (this.getLibraryId()==castOther.getLibraryId()) || ( this.getLibraryId()!=null && castOther.getLibraryId()!=null && this.getLibraryId().equals(castOther.getLibraryId()) ) )
 && (this.getBibId()==castOther.getBibId())
 && ( (this.getMarctag()==castOther.getMarctag()) || ( this.getMarctag()!=null && castOther.getMarctag()!=null && this.getMarctag().equals(castOther.getMarctag()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLibraryId() == null ? 0 : this.getLibraryId().hashCode() );
         result = 37 * result + this.getBibId();
         result = 37 * result + ( getMarctag() == null ? 0 : this.getMarctag().hashCode() );
         return result;
   }   


}


