package com.myapp.struts.hbm;
// Generated May 2, 2011 12:00:18 PM by Hibernate Tools 3.2.1.GA



/**
 * DocumentCategoryId generated by hbm2java
 */
public class DocumentCategoryId  implements java.io.Serializable {


     private String documentCategoryId;
     private String libraryId;
     private String sublibraryId;

    public DocumentCategoryId() {
    }

    public DocumentCategoryId(String documentCategoryId, String libraryId, String sublibraryId) {
       this.documentCategoryId = documentCategoryId;
       this.libraryId = libraryId;
       this.sublibraryId = sublibraryId;
    }
   
    public String getDocumentCategoryId() {
        return this.documentCategoryId;
    }
    
    public void setDocumentCategoryId(String documentCategoryId) {
        this.documentCategoryId = documentCategoryId;
    }
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public String getSublibraryId() {
        return this.sublibraryId;
    }
    
    public void setSublibraryId(String sublibraryId) {
        this.sublibraryId = sublibraryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocumentCategoryId) ) return false;
		 DocumentCategoryId castOther = ( DocumentCategoryId ) other; 
         
		 return ( (this.getDocumentCategoryId()==castOther.getDocumentCategoryId()) || ( this.getDocumentCategoryId()!=null && castOther.getDocumentCategoryId()!=null && this.getDocumentCategoryId().equals(castOther.getDocumentCategoryId()) ) )
 && ( (this.getLibraryId()==castOther.getLibraryId()) || ( this.getLibraryId()!=null && castOther.getLibraryId()!=null && this.getLibraryId().equals(castOther.getLibraryId()) ) )
 && ( (this.getSublibraryId()==castOther.getSublibraryId()) || ( this.getSublibraryId()!=null && castOther.getSublibraryId()!=null && this.getSublibraryId().equals(castOther.getSublibraryId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDocumentCategoryId() == null ? 0 : this.getDocumentCategoryId().hashCode() );
         result = 37 * result + ( getLibraryId() == null ? 0 : this.getLibraryId().hashCode() );
         result = 37 * result + ( getSublibraryId() == null ? 0 : this.getSublibraryId().hashCode() );
         return result;
   }   


}


