package com.myapp.struts.hbm;
// Generated May 2, 2011 12:00:18 PM by Hibernate Tools 3.2.1.GA



/**
 * EmployeeTypeId generated by hbm2java
 */
public class EmployeeTypeId  implements java.io.Serializable {


     private String libraryId;
     private String emptypeId;

    public EmployeeTypeId() {
    }

    public EmployeeTypeId(String libraryId, String emptypeId) {
       this.libraryId = libraryId;
       this.emptypeId = emptypeId;
    }
   
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public String getEmptypeId() {
        return this.emptypeId;
    }
    
    public void setEmptypeId(String emptypeId) {
        this.emptypeId = emptypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployeeTypeId) ) return false;
		 EmployeeTypeId castOther = ( EmployeeTypeId ) other; 
         
		 return ( (this.getLibraryId()==castOther.getLibraryId()) || ( this.getLibraryId()!=null && castOther.getLibraryId()!=null && this.getLibraryId().equals(castOther.getLibraryId()) ) )
 && ( (this.getEmptypeId()==castOther.getEmptypeId()) || ( this.getEmptypeId()!=null && castOther.getEmptypeId()!=null && this.getEmptypeId().equals(castOther.getEmptypeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLibraryId() == null ? 0 : this.getLibraryId().hashCode() );
         result = 37 * result + ( getEmptypeId() == null ? 0 : this.getEmptypeId().hashCode() );
         return result;
   }   


}


