package com.myapp.struts.hbm;
// Generated May 2, 2011 12:00:18 PM by Hibernate Tools 3.2.1.GA



/**
 * FacultyId generated by hbm2java
 */
public class FacultyId  implements java.io.Serializable {


     private String libraryId;
     private String facultyId;

    public FacultyId() {
    }

    public FacultyId(String libraryId, String facultyId) {
       this.libraryId = libraryId;
       this.facultyId = facultyId;
    }
   
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public String getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(String facultyId) {
        this.facultyId = facultyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacultyId) ) return false;
		 FacultyId castOther = ( FacultyId ) other; 
         
		 return ( (this.getLibraryId()==castOther.getLibraryId()) || ( this.getLibraryId()!=null && castOther.getLibraryId()!=null && this.getLibraryId().equals(castOther.getLibraryId()) ) )
 && ( (this.getFacultyId()==castOther.getFacultyId()) || ( this.getFacultyId()!=null && castOther.getFacultyId()!=null && this.getFacultyId().equals(castOther.getFacultyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLibraryId() == null ? 0 : this.getLibraryId().hashCode() );
         result = 37 * result + ( getFacultyId() == null ? 0 : this.getFacultyId().hashCode() );
         return result;
   }   


}


