package com.myapp.struts.hbm;
// Generated May 2, 2011 12:00:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private FacultyId id;
     private Library library;
     private String facultyName;
     private Set departments = new HashSet(0);

    public Faculty() {
    }

	
    public Faculty(FacultyId id, Library library) {
        this.id = id;
        this.library = library;
    }
    public Faculty(FacultyId id, Library library, String facultyName, Set departments) {
       this.id = id;
       this.library = library;
       this.facultyName = facultyName;
       this.departments = departments;
    }
   
    public FacultyId getId() {
        return this.id;
    }
    
    public void setId(FacultyId id) {
        this.id = id;
    }
    public Library getLibrary() {
        return this.library;
    }
    
    public void setLibrary(Library library) {
        this.library = library;
    }
    public String getFacultyName() {
        return this.facultyName;
    }
    
    public void setFacultyName(String facultyName) {
        this.facultyName = facultyName;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }




}


