package com.myapp.struts.hbm;
// Generated Jun 12, 2012 4:17:47 PM by Hibernate Tools 3.2.1.GA



/**
 * FineDetailsId generated by hbm2java
 */
public class FineDetailsId  implements java.io.Serializable {


     
     private String libraryId;
     private String sublibraryId;
     private String memid;
     private String slipno;

    public FineDetailsId() {
    }

    public FineDetailsId( String libraryId, String sublibraryId, String memid,String slipno) {
       
       this.libraryId = libraryId;
       this.sublibraryId = sublibraryId;
       this.memid = memid;
       this.slipno=slipno;
    }
   
    
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public String getSublibraryId() {
        return this.sublibraryId;
    }
    
    public void setSublibraryId(String sublibraryId) {
        this.sublibraryId = sublibraryId;
    }
    public String getMemid() {
        return this.memid;
    }
    
    public void setMemid(String memid) {
        this.memid = memid;
    }

    public String getSlipno() {
        return slipno;
    }

    public void setSlipno(String slipno) {
        this.slipno = slipno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FineDetailsId) ) return false;
		 FineDetailsId castOther = ( FineDetailsId ) other; 
         
		 return 
  ( (this.getLibraryId()==castOther.getLibraryId()) || ( this.getLibraryId()!=null && castOther.getLibraryId()!=null && this.getLibraryId().equals(castOther.getLibraryId()) ) )
 && ( (this.getSublibraryId()==castOther.getSublibraryId()) || ( this.getSublibraryId()!=null && castOther.getSublibraryId()!=null && this.getSublibraryId().equals(castOther.getSublibraryId()) ) )
 && ( (this.getMemid()==castOther.getMemid()) || ( this.getMemid()!=null && castOther.getMemid()!=null && this.getMemid().equals(castOther.getMemid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        
         result = 37 * result + ( getLibraryId() == null ? 0 : this.getLibraryId().hashCode() );
         result = 37 * result + ( getSublibraryId() == null ? 0 : this.getSublibraryId().hashCode() );
         result = 37 * result + ( getMemid() == null ? 0 : this.getMemid().hashCode() );
         return result;
   }   


}


