package com.myapp.struts.hbm;
// Generated 16 Nov, 2011 3:38:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Library generated by hbm2java
 */
public class Library  implements java.io.Serializable {


     private String libraryId;
     private Integer registrationId;
     private String libraryName;
     private String staffId;
     private String workingStatus;
     private Set serNewEntries = new HashSet(0);

    public Library() {
    }

	
    public Library(String libraryId, String workingStatus) {
        this.libraryId = libraryId;
        this.workingStatus = workingStatus;
    }
    public Library(String libraryId, Integer registrationId, String libraryName, String staffId, String workingStatus, Set serNewEntries) {
       this.libraryId = libraryId;
       this.registrationId = registrationId;
       this.libraryName = libraryName;
       this.staffId = staffId;
       this.workingStatus = workingStatus;
       this.serNewEntries = serNewEntries;
    }
   
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public Integer getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(Integer registrationId) {
        this.registrationId = registrationId;
    }
    public String getLibraryName() {
        return this.libraryName;
    }
    
    public void setLibraryName(String libraryName) {
        this.libraryName = libraryName;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public String getWorkingStatus() {
        return this.workingStatus;
    }
    
    public void setWorkingStatus(String workingStatus) {
        this.workingStatus = workingStatus;
    }
    public Set getSerNewEntries() {
        return this.serNewEntries;
    }
    
    public void setSerNewEntries(Set serNewEntries) {
        this.serNewEntries = serNewEntries;
    }




}


