package com.myapp.struts.hbm;
// Generated Apr 24, 2012 4:16:11 PM by Hibernate Tools 3.2.1.GA



/**
 * TempExcellImport generated by hbm2java
 */
public class TempExcellImport  implements java.io.Serializable {


     private Integer sno;
     private String libraryId;
     private String sublibraryId;
     private String documentCategory;
     private String bookType;
     private String dateAcquired;
     private String title;
     private String subtitle;
     private String altTitle;
     private String statementResponsibility;
     private String mainEntry;
     private String addedEntry;
     private String addedEntry1;
     private String addedEntry2;
     private String addedEntry3;
     private String publisherName;
     private String publicationPlace;
     private String publishingYear;
     private String callNo;
     private String subject;
     private String subject1;
     private String subject2;
     private String entryLanguage;
     private String isbn10;
     private String isbn13;
     private String lccNo;
     private String edition;
     private String noOfCopies;
     private String collation1;
     private String notes;
     private String abstract_;
     private String series;
     private String accessionNo;
     private String volumeNo;
     private String location;
     private String shelvingLocation;
     private String indexNo;
     private String noOfPages;
     private String bindType;
     private String refNo;

    public String getAbstract1() {
        return abstract1;
    }

    public void setAbstract1(String abstract1) {
        this.abstract1 = abstract1;
    }

    public String getAddedEntry11() {
        return addedEntry11;
    }

    public void setAddedEntry11(String addedEntry11) {
        this.addedEntry11 = addedEntry11;
    }

    public String getAddedEntry21() {
        return addedEntry21;
    }

    public void setAddedEntry21(String addedEntry21) {
        this.addedEntry21 = addedEntry21;
    }

    public String getAddedEntry31() {
        return addedEntry31;
    }

    public void setAddedEntry31(String addedEntry31) {
        this.addedEntry31 = addedEntry31;
    }

    public String getAddedEntrymli() {
        return addedEntrymli;
    }

    public void setAddedEntrymli(String addedEntrymli) {
        this.addedEntrymli = addedEntrymli;
    }

    public String getAltTitle1() {
        return altTitle1;
    }

    public void setAltTitle1(String altTitle1) {
        this.altTitle1 = altTitle1;
    }

    public String getBindType1() {
        return bindType1;
    }

    public void setBindType1(String bindType1) {
        this.bindType1 = bindType1;
    }

    public String getCollation11() {
        return collation11;
    }

    public void setCollation11(String collation11) {
        this.collation11 = collation11;
    }

    public String getDocumentCategory() {
        return documentCategory;
    }

    public void setDocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory;
    }

    public String getEdition1() {
        return edition1;
    }

    public void setEdition1(String edition1) {
        this.edition1 = edition1;
    }

    public String getIndexNo1() {
        return indexNo1;
    }

    public void setIndexNo1(String indexNo1) {
        this.indexNo1 = indexNo1;
    }

    public String getLocation1() {
        return location1;
    }

    public void setLocation1(String location1) {
        this.location1 = location1;
    }

    public String getMainEntry1() {
        return mainEntry1;
    }

    public void setMainEntry1(String mainEntry1) {
        this.mainEntry1 = mainEntry1;
    }

    public String getNoOfCopies1() {
        return noOfCopies1;
    }

    public void setNoOfCopies1(String noOfCopies1) {
        this.noOfCopies1 = noOfCopies1;
    }

    public String getNoOfPages1() {
        return noOfPages1;
    }

    public void setNoOfPages1(String noOfPages1) {
        this.noOfPages1 = noOfPages1;
    }

    public String getNotes1() {
        return notes1;
    }

    public void setNotes1(String notes1) {
        this.notes1 = notes1;
    }

    public String getPublicationPlace1() {
        return publicationPlace1;
    }

    public void setPublicationPlace1(String publicationPlace1) {
        this.publicationPlace1 = publicationPlace1;
    }

    public String getPublisherName1() {
        return publisherName1;
    }

    public void setPublisherName1(String publisherName1) {
        this.publisherName1 = publisherName1;
    }

    public String getPublishingYear1() {
        return publishingYear1;
    }

    public void setPublishingYear1(String publishingYear1) {
        this.publishingYear1 = publishingYear1;
    }

    public String getSeries1() {
        return series1;
    }

    public void setSeries1(String series1) {
        this.series1 = series1;
    }

    public String getShelvingLocation1() {
        return shelvingLocation1;
    }

    public void setShelvingLocation1(String shelvingLocation1) {
        this.shelvingLocation1 = shelvingLocation1;
    }

    public String getStatementResponsibility1() {
        return statementResponsibility1;
    }

    public void setStatementResponsibility1(String statementResponsibility1) {
        this.statementResponsibility1 = statementResponsibility1;
    }

    public String getSubtitle1() {
        return subtitle1;
    }

    public void setSubtitle1(String subtitle1) {
        this.subtitle1 = subtitle1;
    }

    public String getVolumeNo1() {
        return volumeNo1;
    }

    public void setVolumeNo1(String volumeNo1) {
        this.volumeNo1 = volumeNo1;
    }


     private String subtitle1;
     private String altTitle1;
     private String statementResponsibility1;
     private String mainEntry1;
     private String addedEntrymli;
     private String addedEntry11;
     private String addedEntry21;
     private String addedEntry31;
     private String publisherName1;
     private String publicationPlace1;
     private String publishingYear1;
     private String edition1;
     private String noOfCopies1;
     private String collation11;
     private String notes1;
     private String abstract1;
     private String series1;
     private String volumeNo1;
     private String location1;
     private String shelvingLocation1;
     private String indexNo1;
     private String noOfPages1;
     private String bindType1;



    public String getTitle1() {
        return title1;
    }

    public void setTitle1(String title1) {
        this.title1 = title1;
    }
     private String title1;

    public TempExcellImport() {
    }

	
    public TempExcellImport(String libraryId, String sublibraryId) {
        this.libraryId = libraryId;
        this.sublibraryId = sublibraryId;
    }
    public TempExcellImport(String libraryId, String sublibraryId, String documentCategory, String bookType, String dateAcquired, String title, String subtitle, String altTitle, String statementResponsibility, String mainEntry, String addedEntry, String addedEntry1, String addedEntry2, String addedEntry3, String publisherName, String publicationPlace, String publishingYear, String callNo, String subject, String subject1, String subject2, String entryLanguage, String isbn10, String isbn13, String lccNo, String edition, String noOfCopies, String collation1, String notes, String abstract_, String series, String accessionNo, String volumeNo, String location, String shelvingLocation, String indexNo, String noOfPages, String bindType, String refNo) {
       this.libraryId = libraryId;
       this.sublibraryId = sublibraryId;
       this.documentCategory = documentCategory;
       this.bookType = bookType;
       this.dateAcquired = dateAcquired;
       this.title = title;
       this.subtitle = subtitle;
       this.altTitle = altTitle;
       this.statementResponsibility = statementResponsibility;
       this.mainEntry = mainEntry;
       this.addedEntry = addedEntry;
       this.addedEntry1 = addedEntry1;
       this.addedEntry2 = addedEntry2;
       this.addedEntry3 = addedEntry3;
       this.publisherName = publisherName;
       this.publicationPlace = publicationPlace;
       this.publishingYear = publishingYear;
       this.callNo = callNo;
       this.subject = subject;
       this.subject1 = subject1;
       this.subject2 = subject2;
       this.entryLanguage = entryLanguage;
       this.isbn10 = isbn10;
       this.isbn13 = isbn13;
       this.lccNo = lccNo;
       this.edition = edition;
       this.noOfCopies = noOfCopies;
       this.collation1 = collation1;
       this.notes = notes;
       this.abstract_ = abstract_;
       this.series = series;
       this.accessionNo = accessionNo;
       this.volumeNo = volumeNo;
       this.location = location;
       this.shelvingLocation = shelvingLocation;
       this.indexNo = indexNo;
       this.noOfPages = noOfPages;
       this.bindType = bindType;
       this.refNo = refNo;
    }
   
    public Integer getSno() {
        return this.sno;
    }
    
    public void setSno(Integer sno) {
        this.sno = sno;
    }
    public String getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(String libraryId) {
        this.libraryId = libraryId;
    }
    public String getSublibraryId() {
        return this.sublibraryId;
    }
    
    public void setSublibraryId(String sublibraryId) {
        this.sublibraryId = sublibraryId;
    }
    public String getdocumentCategory() {
        return this.documentCategory;
    }
    
    public void setdocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory;
    }
    public String getBookType() {
        return this.bookType;
    }
    
    public void setBookType(String bookType) {
        this.bookType = bookType;
    }
    public String getDateAcquired() {
        return this.dateAcquired;
    }
    
    public void setDateAcquired(String dateAcquired) {
        this.dateAcquired = dateAcquired;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSubtitle() {
        return this.subtitle;
    }
    
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }
    public String getAltTitle() {
        return this.altTitle;
    }
    
    public void setAltTitle(String altTitle) {
        this.altTitle = altTitle;
    }
    public String getStatementResponsibility() {
        return this.statementResponsibility;
    }
    
    public void setStatementResponsibility(String statementResponsibility) {
        this.statementResponsibility = statementResponsibility;
    }
    public String getMainEntry() {
        return this.mainEntry;
    }
    
    public void setMainEntry(String mainEntry) {
        this.mainEntry = mainEntry;
    }
    public String getAddedEntry() {
        return this.addedEntry;
    }
    
    public void setAddedEntry(String addedEntry) {
        this.addedEntry = addedEntry;
    }
    public String getAddedEntry1() {
        return this.addedEntry1;
    }
    
    public void setAddedEntry1(String addedEntry1) {
        this.addedEntry1 = addedEntry1;
    }
    public String getAddedEntry2() {
        return this.addedEntry2;
    }
    
    public void setAddedEntry2(String addedEntry2) {
        this.addedEntry2 = addedEntry2;
    }
    public String getAddedEntry3() {
        return this.addedEntry3;
    }
    
    public void setAddedEntry3(String addedEntry3) {
        this.addedEntry3 = addedEntry3;
    }
    public String getPublisherName() {
        return this.publisherName;
    }
    
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }
    public String getPublicationPlace() {
        return this.publicationPlace;
    }
    
    public void setPublicationPlace(String publicationPlace) {
        this.publicationPlace = publicationPlace;
    }
    public String getPublishingYear() {
        return this.publishingYear;
    }
    
    public void setPublishingYear(String publishingYear) {
        this.publishingYear = publishingYear;
    }
    public String getCallNo() {
        return this.callNo;
    }
    
    public void setCallNo(String callNo) {
        this.callNo = callNo;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getSubject1() {
        return this.subject1;
    }
    
    public void setSubject1(String subject1) {
        this.subject1 = subject1;
    }
    public String getSubject2() {
        return this.subject2;
    }
    
    public void setSubject2(String subject2) {
        this.subject2 = subject2;
    }
    public String getEntryLanguage() {
        return this.entryLanguage;
    }
    
    public void setEntryLanguage(String entryLanguage) {
        this.entryLanguage = entryLanguage;
    }
    public String getIsbn10() {
        return this.isbn10;
    }
    
    public void setIsbn10(String isbn10) {
        this.isbn10 = isbn10;
    }
    public String getIsbn13() {
        return this.isbn13;
    }
    
    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13;
    }
    public String getLccNo() {
        return this.lccNo;
    }
    
    public void setLccNo(String lccNo) {
        this.lccNo = lccNo;
    }
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }
    public String getNoOfCopies() {
        return this.noOfCopies;
    }
    
    public void setNoOfCopies(String noOfCopies) {
        this.noOfCopies = noOfCopies;
    }
    public String getCollation1() {
        return this.collation1;
    }
    
    public void setCollation1(String collation1) {
        this.collation1 = collation1;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getAbstract_() {
        return this.abstract_;
    }
    
    public void setAbstract_(String abstract_) {
        this.abstract_ = abstract_;
    }
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
    public String getAccessionNo() {
        return this.accessionNo;
    }
    
    public void setAccessionNo(String accessionNo) {
        this.accessionNo = accessionNo;
    }
    public String getVolumeNo() {
        return this.volumeNo;
    }
    
    public void setVolumeNo(String volumeNo) {
        this.volumeNo = volumeNo;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getShelvingLocation() {
        return this.shelvingLocation;
    }
    
    public void setShelvingLocation(String shelvingLocation) {
        this.shelvingLocation = shelvingLocation;
    }
    public String getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(String indexNo) {
        this.indexNo = indexNo;
    }
    public String getNoOfPages() {
        return this.noOfPages;
    }
    
    public void setNoOfPages(String noOfPages) {
        this.noOfPages = noOfPages;
    }
    public String getBindType() {
        return this.bindType;
    }
    
    public void setBindType(String bindType) {
        this.bindType = bindType;
    }
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }




}


