/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.edrp.pms.peoplesearch;

import in.ac.dei.edrp.pms.member.MemberList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-01-2010
 * 
 * XDoclet definition:
 * @struts.action path="/searchaction" name="peoplesearchform" scope="request" validate="true"
 * @struts.action-forward name="success" path="page.peoplesuccess"
 */
public class PeopleSearchResultAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PeopleSearchForm peoplesearchform = (PeopleSearchForm) form;// TODO Auto-generated method stub
		//System.out.println(peoplesearchform.getKeySearch()+" and searched by "+peoplesearchform.getSearchOption());
		request.setAttribute("memberList", new MemberList(peoplesearchform.getKeySearch(),peoplesearchform.getSearchOption()));
		return mapping.findForward("success");
	}
}