/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.edrp.pms.peoplesearch;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-01-2010
 * 
 * XDoclet definition:
 * @struts.form name="peoplesearchform"
 */
public class PeopleSearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** keySearch property */
	private String keySearch;
	
	private String searchOption="User eMail";

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the keySearch.
	 * @return String
	 */
	public String getKeySearch() {
		return keySearch;
	}

	/** 
	 * Set the keySearch.
	 * @param keySearch The keySearch to set
	 */
	public void setKeySearch(String keySearch) {
		this.keySearch = keySearch;
	}
	
	public String getSearchOption() {
		return searchOption;
	}

	/** 
	 * Set the keySearch.
	 * @param keySearch The keySearch to set
	 */
	public void setSearchOption(String searchOption) {
		this.searchOption = searchOption;
	}
}