/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.MyProfile.Model;
// Generated Sep 2, 2011 10:53:42 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * ProfileBasic generated by hbm2java
 * @author Vinay
 */
@Entity
@Table(name = "profile_basic")
public class ProfileBasic  implements Serializable {
    private static final long serialVersionUID = 1L;


     @Id
     private long basicInfoId;
     @Column(name ="user_id")
     private String userId;
     @Column(name ="fName")
     private String fname;
     @Column(name ="mName")
     private String mname;
     @Column(name ="lName")
     private String lname;
     @Column(name ="gender")
     private String gender;
     @Column(name ="date_of_birth")
     private String dateOfBirth;
     @Column(name ="pBirth")
     private String pbirth;
     @Column(name ="mStatus")
     private String mstatus;
     @Column(name ="aboutMe")
     private String aboutMe;

    public ProfileBasic() {
    }

	
    public ProfileBasic(long basicInfoId) {
        this.basicInfoId = basicInfoId;
    }
    public ProfileBasic(long basicInfoId, String userId, String fname, String mname, String lname, String gender, String dateOfBirth, String pbirth, String mstatus, String aboutMe) {
       this.basicInfoId = basicInfoId;
       this.userId = userId;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.pbirth = pbirth;
       this.mstatus = mstatus;
       this.aboutMe = aboutMe;
    }
   
    public long getBasicInfoId() {
        return this.basicInfoId;
    }
    
    public void setBasicInfoId(long basicInfoId) {
        this.basicInfoId = basicInfoId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getPbirth() {
        return this.pbirth;
    }
    
    public void setPbirth(String pbirth) {
        this.pbirth = pbirth;
    }
    public String getMstatus() {
        return this.mstatus;
    }
    
    public void setMstatus(String mstatus) {
        this.mstatus = mstatus;
    }
    public String getAboutMe() {
        return this.aboutMe;
    }
    
    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }




}


