/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.MyProfile.Model;
// Generated Sep 12, 2011 5:13:18 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Id;


/**
 * ProfileAcademic generated by hbm2java
 * @author Vinay
 */
public class ProfileAcademic implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    private long academicInfoId;
    @Column(name="user_id")
    private String userId;
    @Column(name="degree")
    private String degree;
    @Column(name="university")
    private String university;
    @Column(name="location")
    private String location;
    @Column(name="fStudy")
    private String fstudy;
    @Column(name="pYear")
    private String pyear;
    @Column(name="percentage")
    private Integer percentage;
    @Column(name="division")
    private String division;

    public ProfileAcademic() {
    }

    public ProfileAcademic(long academicInfoId) {
        this.academicInfoId = academicInfoId;
    }

    public ProfileAcademic(long academicInfoId, String userId, String degree, String university, String location, String fstudy, String pyear, Integer percentage, String division) {
        this.academicInfoId = academicInfoId;
        this.userId = userId;
        this.degree = degree;
        this.university = university;
        this.location = location;
        this.fstudy = fstudy;
        this.pyear = pyear;
        this.percentage = percentage;
        this.division = division;
    }

    public long getAcademicInfoId() {
        return this.academicInfoId;
    }

    public void setAcademicInfoId(long academicInfoId) {
        this.academicInfoId = academicInfoId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getDegree() {
        return this.degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getUniversity() {
        return this.university;
    }

    public void setUniversity(String university) {
        this.university = university;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getFstudy() {
        return this.fstudy;
    }

    public void setFstudy(String fstudy) {
        this.fstudy = fstudy;
    }

    public String getPyear() {
        return this.pyear;
    }

    public void setPyear(String pyear) {
        this.pyear = pyear;
    }

    public Integer getPercentage() {
        return this.percentage;
    }

    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }

    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }
}
