/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.MyProfile.Model;
// Generated Sep 2, 2011 10:12:05 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * ProfileContact generated by hbm2java
 * @author Vinay
 */
@Entity
@Table(name = "profile_contact")
public class ProfileContact  implements Serializable {
    private static final long serialVersionUID = 1L;
    
     @Id
     private long contactInfoId;
     @Column(name ="user_id")
     private String userId;
     @Column(name ="address1")
     private String address1;
     @Column(name ="address2")
     private String address2;
     @Column(name ="city")
     private String city;
     @Column(name ="state")
     private String state;
     @Column(name ="country")
     private String country;
     @Column(name ="pin")
     private Integer pin;
     @Column(name ="hTelephone")
     private Long htelephone;
     @Column(name ="oTelephone")
     private Long otelephone;
     @Column(name ="mobile")
     private Long mobile;
     @Column(name ="fax")
     private Long fax;
     @Column(name ="email1")
     private String email1;
     @Column(name ="email2")
     private String email2;
     @Column(name ="email3")
     private String email3;
     @Column(name ="oWebsite")
     private String owebsite;
     @Column(name ="pWebsite")
     private String pwebsite;

    public ProfileContact() {
    }

	
    public ProfileContact(long contactInfoId) {
        this.contactInfoId = contactInfoId;
    }
    public ProfileContact(long contactInfoId, String userId, String address1, String address2, String city, String state, String country, Integer pin, Long htelephone, Long otelephone, Long mobile, Long fax, String email1, String email2, String email3, String owebsite, String pwebsite) {
       this.contactInfoId = contactInfoId;
       this.userId = userId;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pin = pin;
       this.htelephone = htelephone;
       this.otelephone = otelephone;
       this.mobile = mobile;
       this.fax = fax;
       this.email1 = email1;
       this.email2 = email2;
       this.email3 = email3;
       this.owebsite = owebsite;
       this.pwebsite = pwebsite;
    }
   
    public long getContactInfoId() {
        return this.contactInfoId;
    }
    
    public void setContactInfoId(long contactInfoId) {
        this.contactInfoId = contactInfoId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getPin() {
        return this.pin;
    }
    
    public void setPin(Integer pin) {
        this.pin = pin;
    }
    public Long getHtelephone() {
        return this.htelephone;
    }
    
    public void setHtelephone(Long htelephone) {
        this.htelephone = htelephone;
    }
    public Long getOtelephone() {
        return this.otelephone;
    }
    
    public void setOtelephone(Long otelephone) {
        this.otelephone = otelephone;
    }
    public Long getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }
    public Long getFax() {
        return this.fax;
    }
    
    public void setFax(Long fax) {
        this.fax = fax;
    }
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }
    public String getEmail3() {
        return this.email3;
    }
    
    public void setEmail3(String email3) {
        this.email3 = email3;
    }
    public String getOwebsite() {
        return this.owebsite;
    }
    
    public void setOwebsite(String owebsite) {
        this.owebsite = owebsite;
    }
    public String getPwebsite() {
        return this.pwebsite;
    }
    
    public void setPwebsite(String pwebsite) {
        this.pwebsite = pwebsite;
    }




}


