/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.MyProfile.Model;
// Generated Sep 14, 2011 4:19:20 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;

/**
 * ProfilePublication generated by hbm2java
 * @author Vinay
 */
public class ProfilePublication implements Serializable {

    private static final long serialVersionUID = 1L;
    private long publicationId;
    private String userId;
    private String pubTitle;
    private String publisher;
    private String pubDate;
    private String pubUrl;
    private String auther1;
    private String auther2;
    private String auther3;
    private String auther4;
    private String summary;

    public ProfilePublication() {
    }

    public ProfilePublication(long publicationId) {
        this.publicationId = publicationId;
    }

    public ProfilePublication(long publicationId, String userId, String pubTitle, String publisher, String pubDate, String pubUrl, String auther1, String auther2, String auther3, String auther4, String summary) {
        this.publicationId = publicationId;
        this.userId = userId;
        this.pubTitle = pubTitle;
        this.publisher = publisher;
        this.pubDate = pubDate;
        this.pubUrl = pubUrl;
        this.auther1 = auther1;
        this.auther2 = auther2;
        this.auther3 = auther3;
        this.auther4 = auther4;
        this.summary = summary;
    }

    public long getPublicationId() {
        return this.publicationId;
    }

    public void setPublicationId(long publicationId) {
        this.publicationId = publicationId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getPubTitle() {
        return this.pubTitle;
    }

    public void setPubTitle(String pubTitle) {
        this.pubTitle = pubTitle;
    }

    public String getPublisher() {
        return this.publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getPubDate() {
        return this.pubDate;
    }

    public void setPubDate(String pubDate) {
        this.pubDate = pubDate;
    }

    public String getPubUrl() {
        return this.pubUrl;
    }

    public void setPubUrl(String pubUrl) {
        this.pubUrl = pubUrl;
    }

    public String getAuther1() {
        return this.auther1;
    }

    public void setAuther1(String auther1) {
        this.auther1 = auther1;
    }

    public String getAuther2() {
        return this.auther2;
    }

    public void setAuther2(String auther2) {
        this.auther2 = auther2;
    }

    public String getAuther3() {
        return this.auther3;
    }

    public void setAuther3(String auther3) {
        this.auther3 = auther3;
    }

    public String getAuther4() {
        return this.auther4;
    }

    public void setAuther4(String auther4) {
        this.auther4 = auther4;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }
}
