/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.MyProfile.Model;
// Generated Sep 2, 2011 10:12:05 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * ProfilePersonal generated by hbm2java
 * @author Vinay
 */
@Entity
@Table(name = "profile_personal")
public class ProfilePersonal  implements Serializable {
    private static final long serialVersionUID = 1L;


     @Id
     private long personalInfo;
     @Column(name ="user_id")
     private String userId;
     @Column(name ="fBook")
     private String fbook;
     @Column(name ="fTVShow")
     private String ftvshow;
     @Column(name ="fMovie")
     private String fmovie;
     @Column(name ="fQuote")
     private String fquote;
     @Column(name ="oInfo")
     private String oinfo;

    public ProfilePersonal() {
    }

	
    public ProfilePersonal(long personalInfo) {
        this.personalInfo = personalInfo;
    }
    public ProfilePersonal(long personalInfo, String userId, String fbook, String ftvshow, String fmovie, String fquote, String oinfo) {
       this.personalInfo = personalInfo;
       this.userId = userId;
       this.fbook = fbook;
       this.ftvshow = ftvshow;
       this.fmovie = fmovie;
       this.fquote = fquote;
       this.oinfo = oinfo;
    }
   
    public long getPersonalInfo() {
        return this.personalInfo;
    }
    
    public void setPersonalInfo(long personalInfo) {
        this.personalInfo = personalInfo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getFbook() {
        return this.fbook;
    }
    
    public void setFbook(String fbook) {
        this.fbook = fbook;
    }
    public String getFtvshow() {
        return this.ftvshow;
    }
    
    public void setFtvshow(String ftvshow) {
        this.ftvshow = ftvshow;
    }
    public String getFmovie() {
        return this.fmovie;
    }
    
    public void setFmovie(String fmovie) {
        this.fmovie = fmovie;
    }
    public String getFquote() {
        return this.fquote;
    }
    
    public void setFquote(String fquote) {
        this.fquote = fquote;
    }
    public String getOinfo() {
        return this.oinfo;
    }
    
    public void setOinfo(String oinfo) {
        this.oinfo = oinfo;
    }




}


