<?php

        setlocale(LC_MONETARY, 'en_IN');
        $this->load->library('reportlist1');
        $this->load->library('session');
        $date1 = $this->session->userdata('date1');
        $date2 = $this->session->userdata('date2');
        $fy_start=explode("-",$date1);
        $fy_end=explode("-",$date2);
        $curr_year = '('.$fy_start[0] ."-" .$fy_end[0] .')';
        $prev_year = '(' . ($fy_start[0]-1) ."-" . ($fy_end[0]-1) .')';

        $net_dr = 0.00;
        $net_opening_bal = 0.00;
        $net_cr = 0.00;
        $net_total = 0.00;
        $net_current_year = 0.00;
        $net_previous_year = 0.00;
        echo "<table border=0 class=\"simple-table balance-sheet-table\" width=\"98%\">";
        echo "<thead><tr><th></th><th align=\"center\" colspan=\"5\">GROSS BLOCK</th><th align=\"center\" colspan=\"4\">DEPRECIATION FOR THE YEAR</th><th align=\"center\" colspan=\"2\">NET BLOCK</th></tr></thead>";

        echo "<tr>";
                echo "<td>S. No.</td>";
                echo "<td>Assets Heads</td>";
                echo "<td>Op Balance 01.04....</td>";
                echo "<td>Addition</td>";
                echo "<td>Deductions</td>";
                echo "<td>CI Balance</td>";
                echo "<td>Dep Opening <br> Balance </td>";
                echo "<td>Depreciation <br> for the Year</td>";
		echo "<td> Deductions/ <br> Adjustment</td>";
                echo "<td> Total <br> Depreciation</td>";
                echo "<td> 31.03..... </td>";
                echo "<td> 31.03..... </td>";
        echo "</tr>";
        $object = new Reportlist1();
	$object->Fixed_Asset_Others('20010119','4D');
	$op_bal1 = $object->opening_balance1;
	$dr_total1 = $object->debit_total1;
	$cr_total1 = $object->credit_total1;
	$cl_bal1 = $object->closing_balance1;
	$depreciation_opbal1 = $object->dep_opening_balance1;
	$current_dep_value1 = $object->current_depreciation_amount1;
	$total_depreciation1 = $object->total_depreciation1;
	$current_year_value1 = $object->curr_amount1;

//        $object->Fixed_Sub_Schedule('2001',4);
        echo "</table>";
        echo "<br>";
        echo "<table border=0 class=\"simple-table balance-sheet-table\" width=\"98%\">";

        echo "<tr class=\"tr-group\">";
                echo "<td class=\"td-group\" align=\"center\" width=\"280\">";
                echo "<strong>TOTAL</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($op_bal1) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc(+$dr_total1) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc(-$cr_total1) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($cl_bal1) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($depreciation_opbal1) . "</strong>";
		echo "</td>";
		echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($current_dep_value1) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc(0) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($total_depreciation1) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($current_year_value1) . "</strong>";
                echo "</td>";
		echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc(0) . "</strong>";
                echo "</td>";

		echo "</tr>";

        echo "</table>";
        echo "<br>";
        echo "<table border=0 class=\"simple-table balance-sheet-table\" width=\"98%\">";
        $object = new Reportlist1();
  	$object->FixedAsset_B('2001','4D','NULL',"view");
	$op_bal2 = $object->opening_balance;
        $dr_total2 = $object->debit_total;
        $cr_total2 = $object->credit_total;
        $cl_bal2 = $object->closing_balance;
        $depreciation_opbal2 = $object->dep_opening_balance;
        $current_dep_value2 = $object->current_depreciation_amount;
        $total_depreciation2 = $object->total_depreciation;
	$current_year_value2 = $object->curr_amount;

        echo "</table>";
	   echo "<br>";
                echo "<table border=0 class=\"simple-table balance-sheet-table\" width=\"98%\">";
                echo "<tr class=\"tr-group\">";
                echo "<td align=\"center\" class=\"td-group\" width=\"280\">";
                echo "<strong>GRAND TOTAL</strong>";
                echo "</td>";
		
		$total_opening_balance = ($op_bal1 + $op_bal2);
		$total_debit_total = ($dr_total1 + $dr_total2);
		$total_credit_total = ($cr_total1 + $cr_total2);
		$total_closing_balance = ($cl_bal1 + $cl_bal2);
		$total_dep_opening_balance = ($depreciation_opbal1 + $depreciation_opbal2);
		$total_current_depreciation_amount = ($current_dep_value1 + $current_dep_value2);
		$grand_total_depreciation = ($total_depreciation1 + $total_depreciation2);
		$grand_current_year = ($current_year_value1 + $current_year_value2);
		

                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($total_opening_balance) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($total_debit_total) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($total_credit_total) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($total_closing_balance) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($total_dep_opening_balance) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($total_current_depreciation_amount) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc(0) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc($grand_total_depreciation) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
		echo "<strong>" . convert_amount_dc($grand_current_year) . "</strong>";
                echo "</td>";
                echo "<td align=\"right\">";
                echo "<strong>" . convert_amount_dc(0) . "</strong>";
                echo "</td>";
                echo "</tr>";
                echo "</table>";
?>

