/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.MyConnection.Model;
// Generated Oct 13, 2011 10:57:40 AM by Hibernate Tools 3.2.1.GA



/**
 * ProfileSocial generated by hbm2java
 */
public class ProfileSocial  implements java.io.Serializable {


     private long socialInfoId;
     private String userId;
     private String gtalk;
     private String skype;
     private String msn;
     private String aim;
     private String yahoo;
     private String facebook;
     private String orkut;
     private String twitter;
     private String blog;

    public ProfileSocial() {
    }

	
    public ProfileSocial(long socialInfoId) {
        this.socialInfoId = socialInfoId;
    }
    public ProfileSocial(long socialInfoId, String userId, String gtalk, String skype, String msn, String aim, String yahoo, String facebook, String orkut, String twitter, String blog) {
       this.socialInfoId = socialInfoId;
       this.userId = userId;
       this.gtalk = gtalk;
       this.skype = skype;
       this.msn = msn;
       this.aim = aim;
       this.yahoo = yahoo;
       this.facebook = facebook;
       this.orkut = orkut;
       this.twitter = twitter;
       this.blog = blog;
    }
   
    public long getSocialInfoId() {
        return this.socialInfoId;
    }
    
    public void setSocialInfoId(long socialInfoId) {
        this.socialInfoId = socialInfoId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getGtalk() {
        return this.gtalk;
    }
    
    public void setGtalk(String gtalk) {
        this.gtalk = gtalk;
    }
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }
    public String getMsn() {
        return this.msn;
    }
    
    public void setMsn(String msn) {
        this.msn = msn;
    }
    public String getAim() {
        return this.aim;
    }
    
    public void setAim(String aim) {
        this.aim = aim;
    }
    public String getYahoo() {
        return this.yahoo;
    }
    
    public void setYahoo(String yahoo) {
        this.yahoo = yahoo;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getOrkut() {
        return this.orkut;
    }
    
    public void setOrkut(String orkut) {
        this.orkut = orkut;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getBlog() {
        return this.blog;
    }
    
    public void setBlog(String blog) {
        this.blog = blog;
    }




}


