use brihaspati;

ALTER TABLE STUDENT_ROLLNO ADD EXPIRY_DATE TIMESTAMP not null DEFAULT 0;
ALTER TABLE STUDENT_ROLLNO MODIFY PROGRAM varchar(255) not null;
ALTER TABLE STUDENT_ROLLNO MODIFY INSTITUTE_ID varchar(255) not null;

ALTER TABLE COURSE_PROGRAM change STUDENT_ID EMAIL_ID varchar(255) NOT NULL;
ALTER TABLE COURSE_PROGRAM change PROGRAM PROGRAM_CODE varchar(255) NOT NULL;
