use brihaspati;

ALTER TABLE CAL_INFORMATION ADD EXPIRY_DATE DATE NOT NULL;
ALTER TABLE DB_SEND ADD EXPIRY_DATE DATE NOT NULL;
ALTER TABLE NEWS ADD EXPIRY_DATE DATE NOT NULL;
ALTER TABLE NOTICE_SEND ADD EXPIRY_DATE DATE NOT NULL;
ALTER TABLE TASK ADD EXPIRY_DATE DATE NOT NULL;
ALTER TABLE TASK ADD EXPIRY INTEGER NOT NULL;

ALTER TABLE CAL_INFORMATION CHANGE DATE P_DATE DATE NOT NULL;
ALTER TABLE SYSTEM CHANGE CLEAN_DATE CLEAN_DATE DATE NOT NULL;
