use brihaspati;

ALTER TABLE   STUDENT_ROLLNO   DROP INDEX  ROLL_NO;
ALTER TABLE   STUDENT_ROLLNO   DROP INDEX  ROLL_NO_2;
ALTER TABLE   STUDENT_ROLLNO   DROP INDEX  ROLL_NO_3;
alter table STUDENT_ROLLNO add unique (ROLL_NO,PROGRAM,INSTITUTE_ID);
