/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.dei.edrp.pms.login;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="loginform"
 */
@SuppressWarnings("serial")
/**
 * This class contains the setter getter methods related with login.
 */
public class LoginForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	private String uid=null; //for holding user id.
	private String pass=null; //for holding user password.
	private String authority; //for holding the authority, but this time it is not using.
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
				ActionErrors errors = new ActionErrors();
				if((uid == null) || (uid.length() < 1))
					errors.add("uid", new
					ActionMessage("login.uid.required"));
					if((pass == null) || (pass.length() < 1))
					errors.add("pass", new
					ActionMessage("login.password.required"));
					return errors;
				
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.uid=null;
	}
/**
 * The method getUid return user id.
 * */
	public String getUid() {
		return this.uid;
	}
	
/**
 * The method setUid is used for setting the user id in the variable uid.
 * */	
	public void setUid(String uid) {
		this.uid = uid;
	}
	
	/**
	 * The method getUid return user id.
	 * */
		public String getPass() {
			return this.pass;
		}
		
	/**
	 * The method setUid is used for setting the user id in the variable uid.
	 * */	
		public void setPass(String pass) {
			this.pass = pass;
		}

	public String getAuthority() {
		return authority;
	}
	public void setAuthority(String authority) {
		this.authority = authority;
	}
}