
/* Seed data for GMS release 3.0 */

INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn)VALUES  (78, 0, 'Y', 'superAdmin', NOW(), 'default.University.label', NULL,'superAdmin', NOW(), 'University',-1,15,'Y');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn)VALUES   (79, 0, 'Y', 'superAdmin', NOW(), 'default.UniversityMaster.label','universityMaster/create',  'superAdmin', NOW(), 'Create University Master',78,1,'Y');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn)VALUES   (80, 0, 'Y', 'superAdmin', NOW(),'default.UniversityInstitutionMap.label','universityMaster/institutionMap',  'superAdmin', NOW(), 'University Institution Map',78,2,'Y');


INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 78, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SUPERADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 79, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SUPERADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 80, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SUPERADMIN') FROM menu_role_map;


INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn)VALUES   (81, 0, 'Y', 'superAdmin', NOW(), 'default.SubAccountHeads.label','accountHeads/subAccountHeadsCreate','superAdmin', NOW(),'Sub Account Head',20,13,'N');


INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn)VALUES   (82, 0, 'Y', 'superAdmin', NOW(),'default.ProposalFilter.label', 'notification/proposalFilter','superAdmin', NOW(), 'Proposal Filter',20,12,'Y');

INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 82, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SUPERADMIN') FROM menu_role_map;

INSERT INTO gms_settings(`id`,`version`,`created_by`,`created_date`,`modified_by`,`modified_date`,`name`,`value`,`active_yes_no`) VALUES ( NULL,'',NULL,NULL,NULL,NULL,'limit_days',15,'N');




ALTER TABLE menu ADD COLUMN `menu_alignment` VARCHAR(255) NULL AFTER `parent_id`;

UPDATE menu SET menu.menu_alignment='V' WHERE id BETWEEN 1 AND 82;

INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(83, 0, 'Y', 'superAdmin', NOW(), 'default.projects.projectDetails.head', NULL,'superAdmin', NOW(), 'Project Details',-1,16,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(84, 0, 'Y', 'superAdmin', NOW(), 'default.ProjectInfo.label', 'grantAllocation/projectDash','superAdmin', NOW(), 'Project Info',83,1,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(85, 0, 'Y', 'superAdmin', NOW(),'default.ProjectHome.label', 'projects/edit',  'superAdmin',NOW(), 'ProjectHome',83,2,'N','H');
                                      
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(86, 0, 'Y', 'superAdmin', NOW(),'default.Co-PIAddition.label', 'projectsPIMap/addCoPi',  'superAdmin',NOW(), 'Map PI to Project',83,3,'N','H');                                   
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(87, 0, 'Y', 'superAdmin', NOW(),'default.DepartmentAddition.label', 'projectDepartmentMap/create',  'superAdmin',NOW(), 'Map department to Project',83,4,'N','H');                                 
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(88, 0, 'Y', 'superAdmin', NOW(),'default.FundAllocation.label', 'grantAllocation/fundAllot',  'superAdmin',NOW(), 'Fund Allocation',83,5,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(89, 0, 'Y', 'superAdmin', NOW(), 'default.Allocation.label', NULL,'superAdmin', NOW(), 'Allocation',-1,17,'N','H');

INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(90, 0, 'Y', 'superAdmin', NOW(),'default.HeadwiseAllocationByGranter.label', 'grantAllocationSplit/list',  'superAdmin',NOW(), 'Disburse/View Fund Allocation',89,1,'N','H');

INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(91, 0, 'Y', 'superAdmin', NOW(),'default.SuballocateProject.label', 'grantAllocation/subGrantAllot',  'superAdmin',NOW(), 'Project Sub-Allocation',89,2,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(92, 0, 'Y', 'superAdmin', NOW(),'default.ExternalFundAllocation.label', 'externalFundAllocation/agencyCreate',  'superAdmin',NOW(), 'External Fund Allocation',89,3,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(93, 0, 'Y', 'superAdmin', NOW(), 'default.Expenses.label', NULL,'superAdmin', NOW(), 'Expenses',-1,18,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(94, 0, 'Y', 'superAdmin', NOW(),'default.GrantReceipt.label', 'grantReceipt/create',  'superAdmin',NOW(), 'Fund Receipt',93,1,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(95, 0, 'Y', 'superAdmin', NOW(),'default.RecordExpenses.label', 'grantExpense/create',  'superAdmin',NOW(), 'Expense Entry',93,2,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(96, 0, 'Y', 'superAdmin', NOW(),'default.FundAdvance.label', 'fundAdvance/create',  'superAdmin',NOW(), 'Fund Receipt',93,3,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(97, 0, 'Y', 'superAdmin', NOW(), 'default.ProjectClosure.label',' projectTracking/create','superAdmin', NOW(), 'Project Closure',-1,19,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(98, 0, 'Y', 'superAdmin', NOW(), 'default.ProjectPersonnel.label', 'projectEmployee/create','superAdmin', NOW(), 'Project Personnel',-1,20,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(99, 0, 'Y', 'superAdmin', NOW(), 'default.Asset.label', 'itemPurchase/create','superAdmin', NOW(), 'Asset',-1,21,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(100, 0, 'Y', 'superAdmin', NOW(), 'default.Reports.label', NULL,'superAdmin', NOW(), 'Reports',-1,22,'N','H');

INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(101, 0, 'Y', 'superAdmin', NOW(), 'default.Submitutilizationcertificate.label', 'utilization/create','superAdmin', NOW(), 'Utilization Reports',100,1,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(102, 0, 'Y', 'superAdmin', NOW(), 'default.AssetReports.label', 'projectEmployee/hrassetReports','superAdmin', NOW(), 'HRAsset Reports',100,2,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(103, 0, 'Y', 'superAdmin', NOW(), 'default.ViewExpenseForaPeriod.label', 'grantExpense/listExpenses','superAdmin', NOW(), 'View Expense For a Period',100,3,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(104, 0, 'Y', 'superAdmin', NOW(), 'default.ViewExpensesHeadwise.label', 'grantExpense/listSummaryExpenses','superAdmin', NOW(), 'View Headwise Expenses',100,4,'N','H');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(105, 0, 'Y', 'superAdmin', NOW(), 'default.ProposalManagement.label', NULL,'superAdmin', NOW(), 'Notification Details',-1,23,'N','VH');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(106, 0, 'Y', 'superAdmin', NOW(), 'default.NotificationList.label', 'notification/list','superAdmin', NOW(), ' Notification Create',105,1,'N','VH');
INSERT INTO menu (id,VERSION,active_yes_no,created_by,created_date,menu_name,menu_path,modified_by,modified_date,menu_description,parent_id,menu_order,lockedyn,menu_alignment)VALUES(107, 0, 'Y', 'superAdmin', NOW(), 'default.NewNotification.label', 'notification/create','superAdmin', NOW(), ' Notification Create',105,2,'N','VH');

INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 83, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 84, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 85, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 86, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 87, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 88, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 89, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 90, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 91, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 92, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 93, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 94, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 95, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 96, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 97, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 98, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 99, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 100, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 101, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 102, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 103, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 104, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 105, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 106, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 107, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_SITEADMIN') FROM menu_role_map;

INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 83, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 84, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 85, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 86, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 87, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 88, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 89, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 90, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 91, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 92, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 93, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 94, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 95, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 96, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 97, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 98, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 99, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 100, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 101, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 102, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 103, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 104, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 105, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 106, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 107, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PI') FROM menu_role_map;


INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 83, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 84, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 85, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 86, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 87, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 88, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 89, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 90, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 91, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 92, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 93, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 94, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 95, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 96, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 97, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 98, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 99, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 100, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 101, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 102, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 103, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 104, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 105, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 106, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 107, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_REVIEWER') FROM menu_role_map;


INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 83, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 84, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 85, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 86, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 87, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 88, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 89, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 90, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 91, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 92, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 93, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 94, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 95, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 96, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 97, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 98, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 99, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 100, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 101, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 102, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 103, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 104, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 105, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 106, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 107, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_STAFF') FROM menu_role_map;

insert into authority values(31,0,"Y","ROLE_PROPOSALADMIN","Proposal Admin");

INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 83, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 84, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 85, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 86, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 87, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 88, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 89, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 90, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 91, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 92, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 93, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 94, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 95, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 96, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 97, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 98, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 99, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 100, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 101, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 102, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 103, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 104, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 105, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 106, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;
INSERT INTO menu_role_map (`id`,`version`, `active_yes_no`, `created_by`, `created_date`, `menu_id`, `modified_by`, `modified_date`, `role_id`)SELECT IFNULL(MAX(id), 0)+1, 0, 'Y', 'SuperAdmin', NOW(), 107, 'SuperAdmin', NOW(), (SELECT a.id FROM authority a WHERE authority='ROLE_PROPOSALADMIN') FROM menu_role_map;




/* Release Script for GMS release 3.0 */


UPDATE gms_settings SET value='Thank you for registering with the Grant Management System (GMS).\r\n GMS an open source, enterprise wide grants management system developed under the ERP project of NMEICT.\r\nGMS helps manage complete grant life cycle from call for proposal to award to closure including monitoring of project to ensure compliance with funding agency regulations and automatic generation of compliance reports.\n\nA GMS user account has been created with following details.' WHERE name='MailContent';

UPDATE gms_settings SET value ='Please visit http://sakshat.amrita.ac.in/erp/gms where you will more\r\ninformation about GMS including documentation. If you have any questions you\r\nmay write to us at amritaerp@gmail.com\n\nWelcome to the ERP Project!\n\nRegards,\r\nYour ERP Team at Amrita' WHERE name='MailFooter';

ALTER TABLE project_department_map  ADD COLUMN `comments` VARCHAR(255) NULL AFTER `active_yes_no`;

