use brihaspati;

drop table if exists INSTITUTE_ADMIN_REGISTRATION;

CREATE TABLE INSTITUTE_ADMIN_REGISTRATION
(
	INSTITUTE_ID INTEGER NOT NULL,
        INSTITUTE_NAME VARCHAR (255) NOT NULL,
        INSTIUTE_ADDRESS VARCHAR (255) NOT NULL,
        CITY VARCHAR (255) NOT NULL,
	PINCODE INTEGER NOT NULL,
        STATE VARCHAR (255) NOT NULL,
        LANDLINE_NO INTEGER (255) NOT NULL,
        INSTITUTE_DOMAIN VARCHAR (255) NOT NULL,
        TYPE_OF_INSTITUTION VARCHAR (255),
        AFFILIATION VARCHAR (255),
        INSTITUTE_WEBSITE VARCHAR (255),
        ADMIN_FNAME VARCHAR (255) NOT NULL,
        ADMIN_LNAME VARCHAR (255) NOT NULL,
        ADMIN_EMAIL VARCHAR (255) NOT NULL,
        ADMIN_DESIGNATION VARCHAR (255) NOT NULL,
        ADMIN_UNAME VARCHAR (32) NOT NULL,
        ADMIN_PASSWORD VARCHAR (32) NOT NULL,
        INSTITUTE_STATUS INTEGER (1) default 0 NOT NULL,
    	PRIMARY KEY(INSTITUTE_ID)
); 

insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (130, 'INSTITUTE_ADMIN_REGISTRATION', 1000, 10);	
