use brihaspati;

ALTER TABLE STUDENT_EXPIRY MODIFY CID VARCHAR(255);
ALTER TABLE STUDENT_EXPIRY MODIFY EXPIRY_DATE TIMESTAMP DEFAULT '0000-00-00 00:00:00';
ALTER TABLE STUDENT_EXPIRY DROP COLUMN EMAIL;
ALTER TABLE STUDENT_EXPIRY DROP COLUMN ROLL_NO;
ALTER TABLE STUDENT_EXPIRY DROP COLUMN EXPIRY_DAYS;


