use brihaspati;
ALTER TABLE INSTITUTE_ADMIN_REGISTRATION ADD REGISTRATION_DATE TIMESTAMP NOT NULL default '20100120';
ALTER TABLE INSTITUTE_ADMIN_REGISTRATION ADD EXPIRY_DATE TIMESTAMP NOT NULL default '20120120';

