/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.mhrd.omr;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-05-2010
 * @author Anshul
 * XDoclet definition:
 * @struts.form name="delQues"
 */
public class DelQuesForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** qno property */
	private String qno;
	
	private String testName;

	/*
	 * Generated Methods
	 */

	public String getTestName() {
		return testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the qno.
	 * @return String
	 */
	public String getQno() {
		return qno;
	}

	/** 
	 * Set the qno.
	 * @param qno The qno to set
	 */
	public void setQno(String qno) {
		this.qno = qno;
	}
}