/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.mhrd.omr;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import in.ac.dei.mhrd.omr.LogInterfaceForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-04-2010
 * @author Anshul Agarwal
 * XDoclet definition:
 * @struts.action path="/logInter" name="logInterfaceForm" input="/Menu.jsp" scope="request" validate="true"
 * 
 * This class determines the log table to be displayed based on the 
 * selections made by the user 
 * 
 */
public class LogInterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LogInterfaceForm logInterfaceForm = (LogInterfaceForm) form;// TODO Auto-generated method stub
		System.out.println("inside Log Action");
		String testName="";
	     testName= logInterfaceForm.getTestName();
	     int testId = SelectTestId.getTestId(testName);
		String selectedLog=logInterfaceForm.getLog();
		request.setAttribute("TestName", testName);
		request.setAttribute("testid", testId);
		/*
		 * if user opt to view the error log
		 */
		
		if(selectedLog.equalsIgnoreCase("E")){
		request.setAttribute("tableName", "log");
		}
		else{
			/*
			 * If user opt to view the test log
			 */
			System.out.println("inside else");
			request.setAttribute("tableName", "testlog");
		}
			return mapping.findForward("erroLog");
		

		
	}
}