/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.mhrd.omr;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-27-2010
 * 
 * XDoclet definition:
 * @struts.form name="sectionForm"
 */
public class SectionForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** negMarks property */
	private String negMarks;

	/** noOfQues property */
	private String noOfQues;

	/** marksOfEachQues property */
	private String marksOfEachQues;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the negMarks.
	 * @return String
	 */
	public String getNegMarks() {
		return negMarks;
	}

	/** 
	 * Set the negMarks.
	 * @param negMarks The negMarks to set
	 */
	public void setNegMarks(String negMarks) {
		this.negMarks = negMarks;
	}

	/** 
	 * Returns the noOfQues.
	 * @return String
	 */
	public String getNoOfQues() {
		return noOfQues;
	}

	/** 
	 * Set the noOfQues.
	 * @param noOfQues The noOfQues to set
	 */
	public void setNoOfQues(String noOfQues) {
		this.noOfQues = noOfQues;
	}

	/** 
	 * Returns the marksOfEachQues.
	 * @return String
	 */
	public String getMarksOfEachQues() {
		return marksOfEachQues;
	}

	/** 
	 * Set the marksOfEachQues.
	 * @param marksOfEachQues The marksOfEachQues to set
	 */
	public void setMarksOfEachQues(String marksOfEachQues) {
		this.marksOfEachQues = marksOfEachQues;
	}
}