/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.mhrd.omr;

import in.ac.dei.mhrd.omr.img.*;

import java.sql.*;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.Resources;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.apache.log4j.xml.DOMConfigurator;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2010
 * @author Anshul Agarwal
 * XDoclet definition:
 * @struts.action path="/wrong" name="wrongQuesForm" input="/WrongQues.jsp" validate="true"
 * 
 * This class fetches information from the misprinted Question UI and inserts into the table WrongQuestion table in the database
 */
public class WrongQuesAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	private static Logger log = Logger.getLogger(WrongQuesAction.class);

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WrongQuesForm wrongQuesForm = (WrongQuesForm) form;// TODO Auto-generated method stub
		
		//get Test Id of the selected test name
		int testid = SelectTestId.getTestId(wrongQuesForm.getTestName());
		
				try {
					//getting connection from the database
            Connection con = Connect.prepareConnection();
            con.setAutoCommit(false);
            //insert data into wromgQuestion table
                        PreparedStatement  psWrongQues=con.prepareStatement("insert into wrongquestion(TestId, WrongQuestionNo, status) values(?,?,?)");
                   psWrongQues.setInt(1, testid);
                   psWrongQues.setInt(2,Integer.parseInt(wrongQuesForm.getQno()));
                   psWrongQues.setString(3, wrongQuesForm.getStatus());
                 int i=  psWrongQues.executeUpdate();
            	 con.commit();
                  //check if wrong question inserted successfully
                 if(i==1){
                	 request.setAttribute("wrongmsg", " Question Added Successfully!! ");
                	 log.info("Wrong Question inserted successfully");
                 }
       		//closing database connection
     con.close();
		}catch(Exception e){
           log.error("Error in inerting Wrong Question");     
}
       
		
		
		return mapping.findForward("WrongQ");
		
	}
}