package pojo.hibernate;
// Generated 26 Mar, 2012 3:25:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Committeemaster generated by hbm2java
 */
public class Committeemaster  implements java.io.Serializable {


     private Integer committeeId;
     private Subinstitutionmaster subinstitutionmaster;
     private Departmentmaster departmentmaster;
     private ErpmGenMaster erpmGenMaster;
     private Institutionmaster institutionmaster;
     private String committeeName;
     private String commmitteePurpose;
     private Character committeeActive;
     private String committeeConvener;
     private Character committeeLevel;
     private Set workflowdetailsForWfdDestinationCommittee = new HashSet(0);
     private Set workflowtransactionsForWftDestinationId = new HashSet(0);
     private Set workflowtransactionsForWftSourceId = new HashSet(0);
     private Set workflowdetailsForWfdSourceCommittee = new HashSet(0);

    public Committeemaster() {
    }

	
    public Committeemaster(String committeeName, String committeeConvener) {
        this.committeeName = committeeName;
        this.committeeConvener = committeeConvener;
    }
    public Committeemaster(Subinstitutionmaster subinstitutionmaster, Departmentmaster departmentmaster, ErpmGenMaster erpmGenMaster, Institutionmaster institutionmaster, String committeeName, String commmitteePurpose, Character committeeActive, String committeeConvener, Character committeeLevel, Set workflowdetailsForWfdDestinationCommittee, Set workflowtransactionsForWftDestinationId, Set workflowtransactionsForWftSourceId, Set workflowdetailsForWfdSourceCommittee) {
       this.subinstitutionmaster = subinstitutionmaster;
       this.departmentmaster = departmentmaster;
       this.erpmGenMaster = erpmGenMaster;
       this.institutionmaster = institutionmaster;
       this.committeeName = committeeName;
       this.commmitteePurpose = commmitteePurpose;
       this.committeeActive = committeeActive;
       this.committeeConvener = committeeConvener;
       this.committeeLevel = committeeLevel;
       this.workflowdetailsForWfdDestinationCommittee = workflowdetailsForWfdDestinationCommittee;
       this.workflowtransactionsForWftDestinationId = workflowtransactionsForWftDestinationId;
       this.workflowtransactionsForWftSourceId = workflowtransactionsForWftSourceId;
       this.workflowdetailsForWfdSourceCommittee = workflowdetailsForWfdSourceCommittee;
    }
   
    public Integer getCommitteeId() {
        return this.committeeId;
    }
    
    public void setCommitteeId(Integer committeeId) {
        this.committeeId = committeeId;
    }
    public Subinstitutionmaster getSubinstitutionmaster() {
        return this.subinstitutionmaster;
    }
    
    public void setSubinstitutionmaster(Subinstitutionmaster subinstitutionmaster) {
        this.subinstitutionmaster = subinstitutionmaster;
    }
    public Departmentmaster getDepartmentmaster() {
        return this.departmentmaster;
    }
    
    public void setDepartmentmaster(Departmentmaster departmentmaster) {
        this.departmentmaster = departmentmaster;
    }
    public ErpmGenMaster getErpmGenMaster() {
        return this.erpmGenMaster;
    }
    
    public void setErpmGenMaster(ErpmGenMaster erpmGenMaster) {
        this.erpmGenMaster = erpmGenMaster;
    }
    public Institutionmaster getInstitutionmaster() {
        return this.institutionmaster;
    }
    
    public void setInstitutionmaster(Institutionmaster institutionmaster) {
        this.institutionmaster = institutionmaster;
    }
    public String getCommitteeName() {
        return this.committeeName;
    }
    
    public void setCommitteeName(String committeeName) {
        this.committeeName = committeeName;
    }
    public String getCommmitteePurpose() {
        return this.commmitteePurpose;
    }
    
    public void setCommmitteePurpose(String commmitteePurpose) {
        this.commmitteePurpose = commmitteePurpose;
    }
    public Character getCommitteeActive() {
        return this.committeeActive;
    }
    
    public void setCommitteeActive(Character committeeActive) {
        this.committeeActive = committeeActive;
    }
    public String getCommitteeConvener() {
        return this.committeeConvener;
    }
    
    public void setCommitteeConvener(String committeeConvener) {
        this.committeeConvener = committeeConvener;
    }
    public Character getCommitteeLevel() {
        return this.committeeLevel;
    }
    
    public void setCommitteeLevel(Character committeeLevel) {
        this.committeeLevel = committeeLevel;
    }
    public Set getWorkflowdetailsForWfdDestinationCommittee() {
        return this.workflowdetailsForWfdDestinationCommittee;
    }
    
    public void setWorkflowdetailsForWfdDestinationCommittee(Set workflowdetailsForWfdDestinationCommittee) {
        this.workflowdetailsForWfdDestinationCommittee = workflowdetailsForWfdDestinationCommittee;
    }
    public Set getWorkflowtransactionsForWftDestinationId() {
        return this.workflowtransactionsForWftDestinationId;
    }
    
    public void setWorkflowtransactionsForWftDestinationId(Set workflowtransactionsForWftDestinationId) {
        this.workflowtransactionsForWftDestinationId = workflowtransactionsForWftDestinationId;
    }
    public Set getWorkflowtransactionsForWftSourceId() {
        return this.workflowtransactionsForWftSourceId;
    }
    
    public void setWorkflowtransactionsForWftSourceId(Set workflowtransactionsForWftSourceId) {
        this.workflowtransactionsForWftSourceId = workflowtransactionsForWftSourceId;
    }
    public Set getWorkflowdetailsForWfdSourceCommittee() {
        return this.workflowdetailsForWfdSourceCommittee;
    }
    
    public void setWorkflowdetailsForWfdSourceCommittee(Set workflowdetailsForWfdSourceCommittee) {
        this.workflowdetailsForWfdSourceCommittee = workflowdetailsForWfdSourceCommittee;
    }




}


