package pojo.hibernate;
// Generated 26 Mar, 2012 3:25:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employeemaster generated by hbm2java
 */
public class Employeemaster  implements java.io.Serializable {


     private Integer empId;
     private ErpmGenMaster erpmGenMaster;
     private Institutionmaster institutionmaster;
     private Departmentmaster departmentmaster;
     private Subinstitutionmaster subinstitutionmaster;
     private String empFname;
     private String empMname;
     private String empLname;
     private String empEmail;
     private String empMobile;
     private String empLandLine;
     private Date empDob;
     private Date empDoj;
     private String empGender;
     private Set institutionmasters = new HashSet(0);
     private Set departmentmasters = new HashSet(0);
     private Set subinstitutionmasters = new HashSet(0);

    public Employeemaster() {
    }

	
    public Employeemaster(Institutionmaster institutionmaster, Departmentmaster departmentmaster, Subinstitutionmaster subinstitutionmaster, String empFname, String empMname, String empLname) {
        this.institutionmaster = institutionmaster;
        this.departmentmaster = departmentmaster;
        this.subinstitutionmaster = subinstitutionmaster;
        this.empFname = empFname;
        this.empMname = empMname;
        this.empLname = empLname;
    }
    public Employeemaster(ErpmGenMaster erpmGenMaster, Institutionmaster institutionmaster, Departmentmaster departmentmaster, Subinstitutionmaster subinstitutionmaster, String empFname, String empMname, String empLname, String empEmail, String empMobile, String empLandLine, Date empDob, Date empDoj, String empGender, Set institutionmasters, Set departmentmasters, Set subinstitutionmasters) {
       this.erpmGenMaster = erpmGenMaster;
       this.institutionmaster = institutionmaster;
       this.departmentmaster = departmentmaster;
       this.subinstitutionmaster = subinstitutionmaster;
       this.empFname = empFname;
       this.empMname = empMname;
       this.empLname = empLname;
       this.empEmail = empEmail;
       this.empMobile = empMobile;
       this.empLandLine = empLandLine;
       this.empDob = empDob;
       this.empDoj = empDoj;
       this.empGender = empGender;
       this.institutionmasters = institutionmasters;
       this.departmentmasters = departmentmasters;
       this.subinstitutionmasters = subinstitutionmasters;
    }
   
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    public ErpmGenMaster getErpmGenMaster() {
        return this.erpmGenMaster;
    }
    
    public void setErpmGenMaster(ErpmGenMaster erpmGenMaster) {
        this.erpmGenMaster = erpmGenMaster;
    }
    public Institutionmaster getInstitutionmaster() {
        return this.institutionmaster;
    }
    
    public void setInstitutionmaster(Institutionmaster institutionmaster) {
        this.institutionmaster = institutionmaster;
    }
    public Departmentmaster getDepartmentmaster() {
        return this.departmentmaster;
    }
    
    public void setDepartmentmaster(Departmentmaster departmentmaster) {
        this.departmentmaster = departmentmaster;
    }
    public Subinstitutionmaster getSubinstitutionmaster() {
        return this.subinstitutionmaster;
    }
    
    public void setSubinstitutionmaster(Subinstitutionmaster subinstitutionmaster) {
        this.subinstitutionmaster = subinstitutionmaster;
    }
    public String getEmpFname() {
        return this.empFname;
    }
    
    public void setEmpFname(String empFname) {
        this.empFname = empFname;
    }
    public String getEmpMname() {
        return this.empMname;
    }
    
    public void setEmpMname(String empMname) {
        this.empMname = empMname;
    }
    public String getEmpLname() {
        return this.empLname;
    }
    
    public void setEmpLname(String empLname) {
        this.empLname = empLname;
    }
    public String getEmpEmail() {
        return this.empEmail;
    }
    
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }
    public String getEmpMobile() {
        return this.empMobile;
    }
    
    public void setEmpMobile(String empMobile) {
        this.empMobile = empMobile;
    }
    public String getEmpLandLine() {
        return this.empLandLine;
    }
    
    public void setEmpLandLine(String empLandLine) {
        this.empLandLine = empLandLine;
    }
    public Date getEmpDob() {
        return this.empDob;
    }
    
    public void setEmpDob(Date empDob) {
        this.empDob = empDob;
    }
    public Date getEmpDoj() {
        return this.empDoj;
    }
    
    public void setEmpDoj(Date empDoj) {
        this.empDoj = empDoj;
    }
    public String getEmpGender() {
        return this.empGender;
    }
    
    public void setEmpGender(String empGender) {
        this.empGender = empGender;
    }
    public Set getInstitutionmasters() {
        return this.institutionmasters;
    }
    
    public void setInstitutionmasters(Set institutionmasters) {
        this.institutionmasters = institutionmasters;
    }
    public Set getDepartmentmasters() {
        return this.departmentmasters;
    }
    
    public void setDepartmentmasters(Set departmentmasters) {
        this.departmentmasters = departmentmasters;
    }
    public Set getSubinstitutionmasters() {
        return this.subinstitutionmasters;
    }
    
    public void setSubinstitutionmasters(Set subinstitutionmasters) {
        this.subinstitutionmasters = subinstitutionmasters;
    }




}


