package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Erpmusers generated by hbm2java
 */
public class Erpmusers  implements java.io.Serializable {


     private Integer erpmuId;
     private String erpmuName;
     private String erpmuPassword;
     //private Date erpmuDob;
     private String erpmuActive;
     private String erpmuVerifiedBy;
     //private String erpmuSecretQuestion;
     //private String erpmuSecretAnswer;
     private String erpmuFullName;
     private Set erpmIndentMasters = new HashSet(0);
     private Set userMessagesForUmFromErpmuId = new HashSet(0);
     private Set fileMasters = new HashSet(0);
     private Set fileDetails = new HashSet(0);
     private Set erpmNewses = new HashSet(0);
     private Set erpmPurchasechallanMasters = new HashSet(0);
     private Set erpmPurchaseinvoiceMasters = new HashSet(0);
     private Set erpmuserroles = new HashSet(0);
     private Set erpmPoMastersForPomUserId = new HashSet(0);
     private Set erpmPoMastersForPomApprovedById = new HashSet(0);
     private Set userMessagesForUmToErpmuId = new HashSet(0);

    public Erpmusers() {
    }

	
    //public Erpmusers(String erpmuName, String erpmuPassword, Date erpmuDob, String erpmuActive, String erpmuFullName) {
    public Erpmusers(String erpmuName, String erpmuPassword, String erpmuActive, String erpmuFullName) {
        this.erpmuName = erpmuName;
        this.erpmuPassword = erpmuPassword;
        //this.erpmuDob = erpmuDob;
        this.erpmuActive = erpmuActive;
        this.erpmuFullName = erpmuFullName;
    }
    //public Erpmusers(String erpmuName, String erpmuPassword, Date erpmuDob, String erpmuActive, String erpmuVerifiedBy, String erpmuSecretQuestion, String erpmuSecretAnswer, String erpmuFullName, Set erpmIndentMasters, Set userMessagesForUmFromErpmuId, Set fileMasters, Set fileDetails, Set erpmNewses, Set erpmPurchasechallanMasters, Set erpmPurchaseinvoiceMasters, Set erpmuserroles, Set erpmPoMastersForPomUserId, Set erpmPoMastersForPomApprovedById, Set userMessagesForUmToErpmuId) {
    public Erpmusers(String erpmuName, String erpmuPassword, String erpmuActive, String erpmuVerifiedBy, String erpmuFullName, Set erpmIndentMasters, Set userMessagesForUmFromErpmuId, Set fileMasters, Set fileDetails, Set erpmNewses, Set erpmPurchasechallanMasters, Set erpmPurchaseinvoiceMasters, Set erpmuserroles, Set erpmPoMastersForPomUserId, Set erpmPoMastersForPomApprovedById, Set userMessagesForUmToErpmuId) {
       this.erpmuName = erpmuName;
       this.erpmuPassword = erpmuPassword;
       //this.erpmuDob = erpmuDob;
       this.erpmuActive = erpmuActive;
       this.erpmuVerifiedBy = erpmuVerifiedBy;
       //this.erpmuSecretQuestion = erpmuSecretQuestion;
       //this.erpmuSecretAnswer = erpmuSecretAnswer;
       this.erpmuFullName = erpmuFullName;
       this.erpmIndentMasters = erpmIndentMasters;
       this.userMessagesForUmFromErpmuId = userMessagesForUmFromErpmuId;
       this.fileMasters = fileMasters;
       this.fileDetails = fileDetails;
       this.erpmNewses = erpmNewses;
       this.erpmPurchasechallanMasters = erpmPurchasechallanMasters;
       this.erpmPurchaseinvoiceMasters = erpmPurchaseinvoiceMasters;
       this.erpmuserroles = erpmuserroles;
       this.erpmPoMastersForPomUserId = erpmPoMastersForPomUserId;
       this.erpmPoMastersForPomApprovedById = erpmPoMastersForPomApprovedById;
       this.userMessagesForUmToErpmuId = userMessagesForUmToErpmuId;
    }
   
    public Integer getErpmuId() {
        return this.erpmuId;
    }
    
    public void setErpmuId(Integer erpmuId) {
        this.erpmuId = erpmuId;
    }
    public String getErpmuName() {
        return this.erpmuName;
    }
    
    public void setErpmuName(String erpmuName) {
        this.erpmuName = erpmuName;
    }
    public String getErpmuPassword() {
        return this.erpmuPassword;
    }
    
    public void setErpmuPassword(String erpmuPassword) {
        this.erpmuPassword = erpmuPassword;
    }
   /* public Date getErpmuDob() {
        return this.erpmuDob;
    }
    
    public void setErpmuDob(Date erpmuDob) {
        this.erpmuDob = erpmuDob;
    }*/
    public String getErpmuActive() {
        return this.erpmuActive;
    }
    
    public void setErpmuActive(String erpmuActive) {
        this.erpmuActive = erpmuActive;
    }
    public String getErpmuVerifiedBy() {
        return this.erpmuVerifiedBy;
    }
    
    public void setErpmuVerifiedBy(String erpmuVerifiedBy) {
        this.erpmuVerifiedBy = erpmuVerifiedBy;
    }
   /* public String getErpmuSecretQuestion() {
        return this.erpmuSecretQuestion;
    }
    
    public void setErpmuSecretQuestion(String erpmuSecretQuestion) {
        this.erpmuSecretQuestion = erpmuSecretQuestion;
    }
    public String getErpmuSecretAnswer() {
        return this.erpmuSecretAnswer;
    }
    
    public void setErpmuSecretAnswer(String erpmuSecretAnswer) {
        this.erpmuSecretAnswer = erpmuSecretAnswer;
    }*/
    public String getErpmuFullName() {
        return this.erpmuFullName;
    }
    
    public void setErpmuFullName(String erpmuFullName) {
        this.erpmuFullName = erpmuFullName;
    }
    public Set getErpmIndentMasters() {
        return this.erpmIndentMasters;
    }
    
    public void setErpmIndentMasters(Set erpmIndentMasters) {
        this.erpmIndentMasters = erpmIndentMasters;
    }
    public Set getUserMessagesForUmFromErpmuId() {
        return this.userMessagesForUmFromErpmuId;
    }
    
    public void setUserMessagesForUmFromErpmuId(Set userMessagesForUmFromErpmuId) {
        this.userMessagesForUmFromErpmuId = userMessagesForUmFromErpmuId;
    }
    public Set getFileMasters() {
        return this.fileMasters;
    }
    
    public void setFileMasters(Set fileMasters) {
        this.fileMasters = fileMasters;
    }
    public Set getFileDetails() {
        return this.fileDetails;
    }
    
    public void setFileDetails(Set fileDetails) {
        this.fileDetails = fileDetails;
    }
    public Set getErpmNewses() {
        return this.erpmNewses;
    }
    
    public void setErpmNewses(Set erpmNewses) {
        this.erpmNewses = erpmNewses;
    }
    public Set getErpmPurchasechallanMasters() {
        return this.erpmPurchasechallanMasters;
    }
    
    public void setErpmPurchasechallanMasters(Set erpmPurchasechallanMasters) {
        this.erpmPurchasechallanMasters = erpmPurchasechallanMasters;
    }
    public Set getErpmPurchaseinvoiceMasters() {
        return this.erpmPurchaseinvoiceMasters;
    }
    
    public void setErpmPurchaseinvoiceMasters(Set erpmPurchaseinvoiceMasters) {
        this.erpmPurchaseinvoiceMasters = erpmPurchaseinvoiceMasters;
    }
    public Set getErpmuserroles() {
        return this.erpmuserroles;
    }
    
    public void setErpmuserroles(Set erpmuserroles) {
        this.erpmuserroles = erpmuserroles;
    }
    public Set getErpmPoMastersForPomUserId() {
        return this.erpmPoMastersForPomUserId;
    }
    
    public void setErpmPoMastersForPomUserId(Set erpmPoMastersForPomUserId) {
        this.erpmPoMastersForPomUserId = erpmPoMastersForPomUserId;
    }
    public Set getErpmPoMastersForPomApprovedById() {
        return this.erpmPoMastersForPomApprovedById;
    }
    
    public void setErpmPoMastersForPomApprovedById(Set erpmPoMastersForPomApprovedById) {
        this.erpmPoMastersForPomApprovedById = erpmPoMastersForPomApprovedById;
    }
    public Set getUserMessagesForUmToErpmuId() {
        return this.userMessagesForUmToErpmuId;
    }
    
    public void setUserMessagesForUmToErpmuId(Set userMessagesForUmToErpmuId) {
        this.userMessagesForUmToErpmuId = userMessagesForUmToErpmuId;
    }




}


