package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA



/**
 * Erpmuserprofile generated by hbm2java
 */
public class Erpmuserprofile  implements java.io.Serializable {


     private int erpmuId;
     private short imId;
     private String imShortName;
     private int simId;
     private String simShortName;
     private int dmId;
     private String dmShortName;

    public Erpmuserprofile() {
    }

	
    public Erpmuserprofile(int erpmuId, short imId, int simId, int dmId) {
        this.erpmuId = erpmuId;
        this.imId = imId;
        this.simId = simId;
        this.dmId = dmId;
    }
    public Erpmuserprofile(int erpmuId, short imId, String imShortName, int simId, String simShortName, int dmId, String dmShortName) {
       this.erpmuId = erpmuId;
       this.imId = imId;
       this.imShortName = imShortName;
       this.simId = simId;
       this.simShortName = simShortName;
       this.dmId = dmId;
       this.dmShortName = dmShortName;
    }
   
    public int getErpmuId() {
        return this.erpmuId;
    }
    
    public void setErpmuId(int erpmuId) {
        this.erpmuId = erpmuId;
    }
    public short getImId() {
        return this.imId;
    }
    
    public void setImId(short imId) {
        this.imId = imId;
    }
    public String getImShortName() {
        return this.imShortName;
    }
    
    public void setImShortName(String imShortName) {
        this.imShortName = imShortName;
    }
    public int getSimId() {
        return this.simId;
    }
    
    public void setSimId(int simId) {
        this.simId = simId;
    }
    public String getSimShortName() {
        return this.simShortName;
    }
    
    public void setSimShortName(String simShortName) {
        this.simShortName = simShortName;
    }
    public int getDmId() {
        return this.dmId;
    }
    
    public void setDmId(int dmId) {
        this.dmId = dmId;
    }
    public String getDmShortName() {
        return this.dmShortName;
    }
    
    public void setDmShortName(String dmShortName) {
        this.dmShortName = dmShortName;
    }




}


