package pojo.hibernate;
// Generated 26 Mar, 2012 3:25:11 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ErpmPoDetails generated by hbm2java
 */
public class ErpmPoDetails  implements java.io.Serializable {


     private Integer podPodetailsId;
     private ErpmItemMaster erpmItemMaster;
     private ErpmIndentDetail erpmIndentDetail;
     private ErpmPoMaster erpmPoMaster;
     private BigDecimal podQuantity;
     private BigDecimal podDiscount;
     private String podWarrantyTerms;
     private String podSchedule;
     private BigDecimal podRate;
     private Set erpmPoTaxeses = new HashSet(0);

    public ErpmPoDetails() {
    }

	
    public ErpmPoDetails(ErpmItemMaster erpmItemMaster, ErpmPoMaster erpmPoMaster) {
        this.erpmItemMaster = erpmItemMaster;
        this.erpmPoMaster = erpmPoMaster;
    }
    public ErpmPoDetails(ErpmItemMaster erpmItemMaster, ErpmIndentDetail erpmIndentDetail, ErpmPoMaster erpmPoMaster, BigDecimal podQuantity, BigDecimal podDiscount, String podWarrantyTerms, String podSchedule, BigDecimal podRate, Set erpmPoTaxeses) {
       this.erpmItemMaster = erpmItemMaster;
       this.erpmIndentDetail = erpmIndentDetail;
       this.erpmPoMaster = erpmPoMaster;
       this.podQuantity = podQuantity;
       this.podDiscount = podDiscount;
       this.podWarrantyTerms = podWarrantyTerms;
       this.podSchedule = podSchedule;
       this.podRate = podRate;
       this.erpmPoTaxeses = erpmPoTaxeses;
    }
   
    public Integer getPodPodetailsId() {
        return this.podPodetailsId;
    }
    
    public void setPodPodetailsId(Integer podPodetailsId) {
        this.podPodetailsId = podPodetailsId;
    }
    public ErpmItemMaster getErpmItemMaster() {
        return this.erpmItemMaster;
    }
    
    public void setErpmItemMaster(ErpmItemMaster erpmItemMaster) {
        this.erpmItemMaster = erpmItemMaster;
    }
    public ErpmIndentDetail getErpmIndentDetail() {
        return this.erpmIndentDetail;
    }
    
    public void setErpmIndentDetail(ErpmIndentDetail erpmIndentDetail) {
        this.erpmIndentDetail = erpmIndentDetail;
    }
    public ErpmPoMaster getErpmPoMaster() {
        return this.erpmPoMaster;
    }
    
    public void setErpmPoMaster(ErpmPoMaster erpmPoMaster) {
        this.erpmPoMaster = erpmPoMaster;
    }
    public BigDecimal getPodQuantity() {
        return this.podQuantity;
    }
    
    public void setPodQuantity(BigDecimal podQuantity) {
        this.podQuantity = podQuantity;
    }
    public BigDecimal getPodDiscount() {
        return this.podDiscount;
    }
    
    public void setPodDiscount(BigDecimal podDiscount) {
        this.podDiscount = podDiscount;
    }
    public String getPodWarrantyTerms() {
        return this.podWarrantyTerms;
    }
    
    public void setPodWarrantyTerms(String podWarrantyTerms) {
        this.podWarrantyTerms = podWarrantyTerms;
    }
    public String getPodSchedule() {
        return this.podSchedule;
    }
    
    public void setPodSchedule(String podSchedule) {
        this.podSchedule = podSchedule;
    }
    public BigDecimal getPodRate() {
        return this.podRate;
    }
    
    public void setPodRate(BigDecimal podRate) {
        this.podRate = podRate;
    }
    public Set getErpmPoTaxeses() {
        return this.erpmPoTaxeses;
    }
    
    public void setErpmPoTaxeses(Set erpmPoTaxeses) {
        this.erpmPoTaxeses = erpmPoTaxeses;
    }




}


