package pojo.hibernate;
// Generated May 29, 2011 11:33:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ErpmItemRate generated by hbm2java
 */
public class ErpmItemRate  implements java.io.Serializable {


     private Integer irItemRateId;
     private Institutionmaster institutionmaster;
     private ErpmGenMaster erpmGenMasterByIrWarrantyStartsFromId;
     private ErpmGenMaster erpmGenMasterByIrCurrencyId;
     private Suppliermaster suppliermaster;
     private ErpmItemMaster erpmItemMaster;
     private Integer irWarrantyMonths;
     private String irWarrantyClause;
     private Set erpmItemRateDetailses = new HashSet(0);

    public ErpmItemRate() {
    }

    public ErpmItemRate(Institutionmaster institutionmaster, ErpmGenMaster erpmGenMasterByIrWarrantyStartsFromId, ErpmGenMaster erpmGenMasterByIrCurrencyId, Suppliermaster suppliermaster, ErpmItemMaster erpmItemMaster, Integer irWarrantyMonths, String irWarrantyClause, Set erpmItemRateDetailses) {
       this.institutionmaster = institutionmaster;
       this.erpmGenMasterByIrWarrantyStartsFromId = erpmGenMasterByIrWarrantyStartsFromId;
       this.erpmGenMasterByIrCurrencyId = erpmGenMasterByIrCurrencyId;
       this.suppliermaster = suppliermaster;
       this.erpmItemMaster = erpmItemMaster;
       this.irWarrantyMonths = irWarrantyMonths;
       this.irWarrantyClause = irWarrantyClause;
       this.erpmItemRateDetailses = erpmItemRateDetailses;
    }
   
    public Integer getIrItemRateId() {
        return this.irItemRateId;
    }
    
    public void setIrItemRateId(Integer irItemRateId) {
        this.irItemRateId = irItemRateId;
    }
    public Institutionmaster getInstitutionmaster() {
        return this.institutionmaster;
    }
    
    public void setInstitutionmaster(Institutionmaster institutionmaster) {
        this.institutionmaster = institutionmaster;
    }
    public ErpmGenMaster getErpmGenMasterByIrWarrantyStartsFromId() {
        return this.erpmGenMasterByIrWarrantyStartsFromId;
    }
    
    public void setErpmGenMasterByIrWarrantyStartsFromId(ErpmGenMaster erpmGenMasterByIrWarrantyStartsFromId) {
        this.erpmGenMasterByIrWarrantyStartsFromId = erpmGenMasterByIrWarrantyStartsFromId;
    }
    public ErpmGenMaster getErpmGenMasterByIrCurrencyId() {
        return this.erpmGenMasterByIrCurrencyId;
    }
    
    public void setErpmGenMasterByIrCurrencyId(ErpmGenMaster erpmGenMasterByIrCurrencyId) {
        this.erpmGenMasterByIrCurrencyId = erpmGenMasterByIrCurrencyId;
    }
    public Suppliermaster getSuppliermaster() {
        return this.suppliermaster;
    }
    
    public void setSuppliermaster(Suppliermaster suppliermaster) {
        this.suppliermaster = suppliermaster;
    }
    public ErpmItemMaster getErpmItemMaster() {
        return this.erpmItemMaster;
    }
    
    public void setErpmItemMaster(ErpmItemMaster erpmItemMaster) {
        this.erpmItemMaster = erpmItemMaster;
    }
    public Integer getIrWarrantyMonths() {
        return this.irWarrantyMonths;
    }
    
    public void setIrWarrantyMonths(Integer irWarrantyMonths) {
        this.irWarrantyMonths = irWarrantyMonths;
    }
    public String getIrWarrantyClause() {
        return this.irWarrantyClause;
    }
    
    public void setIrWarrantyClause(String irWarrantyClause) {
        this.irWarrantyClause = irWarrantyClause;
    }
    public Set getErpmItemRateDetailses() {
        return this.erpmItemRateDetailses;
    }
    
    public void setErpmItemRateDetailses(Set erpmItemRateDetailses) {
        this.erpmItemRateDetailses = erpmItemRateDetailses;
    }




}


