package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ErpmIssueReceive generated by hbm2java
 */
public class ErpmIssueReceive  implements java.io.Serializable {


     private Integer isrId;
     private ErpmIssueMaster erpmIssueMaster;
     private Employeemaster employeemaster;
     private Subinstitutionmaster subinstitutionmaster;
     private Committeemaster committeemaster;
     private Institutionmaster institutionmaster;
     private Departmentmaster departmentmaster;
     private String isrReceiptNo;
     private Date isrReceiptDate;
     private String isrRemarks;

    public ErpmIssueReceive() {
    }

	
    public ErpmIssueReceive(ErpmIssueMaster erpmIssueMaster, Subinstitutionmaster subinstitutionmaster, Institutionmaster institutionmaster, Departmentmaster departmentmaster, String isrReceiptNo, Date isrReceiptDate) {
        this.erpmIssueMaster = erpmIssueMaster;
        this.subinstitutionmaster = subinstitutionmaster;
        this.institutionmaster = institutionmaster;
        this.departmentmaster = departmentmaster;
        this.isrReceiptNo = isrReceiptNo;
        this.isrReceiptDate = isrReceiptDate;
    }
    public ErpmIssueReceive(ErpmIssueMaster erpmIssueMaster, Employeemaster employeemaster, Subinstitutionmaster subinstitutionmaster, Committeemaster committeemaster, Institutionmaster institutionmaster, Departmentmaster departmentmaster, String isrReceiptNo, Date isrReceiptDate, String isrRemarks) {
       this.erpmIssueMaster = erpmIssueMaster;
       this.employeemaster = employeemaster;
       this.subinstitutionmaster = subinstitutionmaster;
       this.committeemaster = committeemaster;
       this.institutionmaster = institutionmaster;
       this.departmentmaster = departmentmaster;
       this.isrReceiptNo = isrReceiptNo;
       this.isrReceiptDate = isrReceiptDate;
       this.isrRemarks = isrRemarks;
    }
   
    public Integer getIsrId() {
        return this.isrId;
    }
    
    public void setIsrId(Integer isrId) {
        this.isrId = isrId;
    }
    public ErpmIssueMaster getErpmIssueMaster() {
        return this.erpmIssueMaster;
    }
    
    public void setErpmIssueMaster(ErpmIssueMaster erpmIssueMaster) {
        this.erpmIssueMaster = erpmIssueMaster;
    }
    public Employeemaster getEmployeemaster() {
        return this.employeemaster;
    }
    
    public void setEmployeemaster(Employeemaster employeemaster) {
        this.employeemaster = employeemaster;
    }
    public Subinstitutionmaster getSubinstitutionmaster() {
        return this.subinstitutionmaster;
    }
    
    public void setSubinstitutionmaster(Subinstitutionmaster subinstitutionmaster) {
        this.subinstitutionmaster = subinstitutionmaster;
    }
    public Committeemaster getCommitteemaster() {
        return this.committeemaster;
    }
    
    public void setCommitteemaster(Committeemaster committeemaster) {
        this.committeemaster = committeemaster;
    }
    public Institutionmaster getInstitutionmaster() {
        return this.institutionmaster;
    }
    
    public void setInstitutionmaster(Institutionmaster institutionmaster) {
        this.institutionmaster = institutionmaster;
    }
    public Departmentmaster getDepartmentmaster() {
        return this.departmentmaster;
    }
    
    public void setDepartmentmaster(Departmentmaster departmentmaster) {
        this.departmentmaster = departmentmaster;
    }
    public String getIsrReceiptNo() {
        return this.isrReceiptNo;
    }
    
    public void setIsrReceiptNo(String isrReceiptNo) {
        this.isrReceiptNo = isrReceiptNo;
    }
    public Date getIsrReceiptDate() {
        return this.isrReceiptDate;
    }
    
    public void setIsrReceiptDate(Date isrReceiptDate) {
        this.isrReceiptDate = isrReceiptDate;
    }
    public String getIsrRemarks() {
        return this.isrRemarks;
    }
    
    public void setIsrRemarks(String isrRemarks) {
        this.isrRemarks = isrRemarks;
    }




}


