package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ErpmPurchaseinvoiceMaster generated by hbm2java
 */
public class ErpmPurchaseinvoiceMaster  implements java.io.Serializable {
     private Integer pimPimId;
     private Departmentmaster departmentmaster;
     private ErpmPoMaster erpmPoMaster;
     private Suppliermaster suppliermaster;
     private Erpmusers erpmusers;
     private ErpmPurchasechallanMaster erpmPurchasechallanMaster;
     private Institutionmaster institutionmaster;
     private Subinstitutionmaster subinstitutionmaster;
     private String pimInvoiceType;
     private Date pimInvoiceRecvdDate;
     private String pimSupplierInvoiceNo;
     private Date pimSupplierInvoiceDate;
     private BigDecimal pimImportExchangeRate;
     private String pimRemarks;
     private String pimCheckedBy;
     private Set erpmPurchaseinvoiceTermses = new HashSet(0);
     private Set erpmPurchaseinvoiceDetails = new HashSet(0);

    public ErpmPurchaseinvoiceMaster() {
    }

    public ErpmPurchaseinvoiceMaster(Departmentmaster departmentmaster, Institutionmaster institutionmaster, Subinstitutionmaster subinstitutionmaster, Date pimInvoiceRecvdDate, String pimSupplierInvoiceNo, Date pimSupplierInvoiceDate) {
        this.departmentmaster = departmentmaster;
        this.institutionmaster = institutionmaster;
        this.subinstitutionmaster = subinstitutionmaster;
        this.pimInvoiceRecvdDate = pimInvoiceRecvdDate;
        this.pimSupplierInvoiceNo = pimSupplierInvoiceNo;
        this.pimSupplierInvoiceDate = pimSupplierInvoiceDate;
    }
    public ErpmPurchaseinvoiceMaster(Departmentmaster departmentmaster, ErpmPoMaster erpmPoMaster, Suppliermaster suppliermaster, Erpmusers erpmusers, ErpmPurchasechallanMaster erpmPurchasechallanMaster, Institutionmaster institutionmaster, Subinstitutionmaster subinstitutionmaster, String pimInvoiceType, Date pimInvoiceRecvdDate, String pimSupplierInvoiceNo, Date pimSupplierInvoiceDate, BigDecimal pimImportExchangeRate, String pimRemarks, String pimCheckedBy, Set erpmPurchaseinvoiceTermses, Set erpmPurchaseinvoiceDetails) {
       this.departmentmaster = departmentmaster;
       this.erpmPoMaster = erpmPoMaster;
       this.suppliermaster = suppliermaster;
       this.erpmusers = erpmusers;
       this.erpmPurchasechallanMaster = erpmPurchasechallanMaster;
       this.institutionmaster = institutionmaster;
       this.subinstitutionmaster = subinstitutionmaster;
       this.pimInvoiceType = pimInvoiceType;
       this.pimInvoiceRecvdDate = pimInvoiceRecvdDate;
       this.pimSupplierInvoiceNo = pimSupplierInvoiceNo;
       this.pimSupplierInvoiceDate = pimSupplierInvoiceDate;
       this.pimImportExchangeRate = pimImportExchangeRate;
       this.pimRemarks = pimRemarks;
       this.pimCheckedBy = pimCheckedBy;
       this.erpmPurchaseinvoiceTermses = erpmPurchaseinvoiceTermses;
       this.erpmPurchaseinvoiceDetails = erpmPurchaseinvoiceDetails;
    }
   
    public Integer getPimPimId() {
        return this.pimPimId;
    }
    
    public void setPimPimId(Integer pimPimId) {
        this.pimPimId = pimPimId;
    }
    public Departmentmaster getDepartmentmaster() {
        return this.departmentmaster;
    }
    
    public void setDepartmentmaster(Departmentmaster departmentmaster) {
        this.departmentmaster = departmentmaster;
    }
    public ErpmPoMaster getErpmPoMaster() {
        return this.erpmPoMaster;
    }
    
    public void setErpmPoMaster(ErpmPoMaster erpmPoMaster) {
        this.erpmPoMaster = erpmPoMaster;
    }
    public Suppliermaster getSuppliermaster() {
        return this.suppliermaster;
    }
    
    public void setSuppliermaster(Suppliermaster suppliermaster) {
        this.suppliermaster = suppliermaster;
    }
    public Erpmusers getErpmusers() {
        return this.erpmusers;
    }
    
    public void setErpmusers(Erpmusers erpmusers) {
        this.erpmusers = erpmusers;
    }
    public ErpmPurchasechallanMaster getErpmPurchasechallanMaster() {
        return this.erpmPurchasechallanMaster;
    }
    
    public void setErpmPurchasechallanMaster(ErpmPurchasechallanMaster erpmPurchasechallanMaster) {
        this.erpmPurchasechallanMaster = erpmPurchasechallanMaster;
    }
    public Institutionmaster getInstitutionmaster() {
        return this.institutionmaster;
    }
    
    public void setInstitutionmaster(Institutionmaster institutionmaster) {
        this.institutionmaster = institutionmaster;
    }
    public Subinstitutionmaster getSubinstitutionmaster() {
        return this.subinstitutionmaster;
    }
    
    public void setSubinstitutionmaster(Subinstitutionmaster subinstitutionmaster) {
        this.subinstitutionmaster = subinstitutionmaster;
    }
    public String getPimInvoiceType() {
        return this.pimInvoiceType;
    }
    
    public void setPimInvoiceType(String pimInvoiceType) {
        this.pimInvoiceType = pimInvoiceType;
    }
    public Date getPimInvoiceRecvdDate() {
        return this.pimInvoiceRecvdDate;
    }
    
    public void setPimInvoiceRecvdDate(Date pimInvoiceRecvdDate) {
        this.pimInvoiceRecvdDate = pimInvoiceRecvdDate;
    }
    public String getPimSupplierInvoiceNo() {
        return this.pimSupplierInvoiceNo;
    }
    
    public void setPimSupplierInvoiceNo(String pimSupplierInvoiceNo) {
        this.pimSupplierInvoiceNo = pimSupplierInvoiceNo;
    }
    public Date getPimSupplierInvoiceDate() {
        return this.pimSupplierInvoiceDate;
    }
    
    public void setPimSupplierInvoiceDate(Date pimSupplierInvoiceDate) {
        this.pimSupplierInvoiceDate = pimSupplierInvoiceDate;
    }
    public BigDecimal getPimImportExchangeRate() {
        return this.pimImportExchangeRate;
    }
    
    public void setPimImportExchangeRate(BigDecimal pimImportExchangeRate) {
        this.pimImportExchangeRate = pimImportExchangeRate;
    }
    public String getPimRemarks() {
        return this.pimRemarks;
    }
    
    public void setPimRemarks(String pimRemarks) {
        this.pimRemarks = pimRemarks;
    }
    public String getPimCheckedBy() {
        return this.pimCheckedBy;
    }
    
    public void setPimCheckedBy(String pimCheckedBy) {
        this.pimCheckedBy = pimCheckedBy;
    }
    public Set getErpmPurchaseinvoiceTermses() {
        return this.erpmPurchaseinvoiceTermses;
    }
    
    public void setErpmPurchaseinvoiceTermses(Set erpmPurchaseinvoiceTermses) {
        this.erpmPurchaseinvoiceTermses = erpmPurchaseinvoiceTermses;
    }
    public Set getErpmPurchaseinvoiceDetails() {
        return this.erpmPurchaseinvoiceDetails;
    }
    
    public void setErpmPurchaseinvoiceDetails(Set erpmPurchaseinvoiceDetails) {
        this.erpmPurchaseinvoiceDetails = erpmPurchaseinvoiceDetails;
    }




}


