package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ErpmIssueMaster generated by hbm2java
 */
public class ErpmIssueMaster  implements java.io.Serializable {


     private Integer ismId;
     private Departmentmaster departmentmasterByIsmToDepartmentId;
     private Departmentmaster departmentmasterByIsmFromDepartmentId;
     private Institutionmaster institutionmasterByIsmToInstituteId;
     private Employeemaster employeemasterByIsmFromEmployeeId;
     private Institutionmaster institutionmasterByIsmFromInstituteId;
     private Subinstitutionmaster subinstitutionmasterByIsmFromSubinstituteId;
     private Employeemaster employeemasterByIsmToEmployeeId;
     private Suppliermaster suppliermaster;
     private Subinstitutionmaster subinstitutionmasterByIsmToSubinstituteId;
     private ErpmIndentMaster erpmIndentMaster;
     private Committeemaster committeemaster;
     private String ismIssueNo;
     private Date ismIssueDate;
     private String ismIssueDesc;
     private String ismToEmail;
     private char ismIssueType;
     private Date ismReturnDueDate;
     private String ismRemarks;
     private Set erpmIssueDetails = new HashSet(0);
     private Set erpmIssueReturnDetails = new HashSet(0);
     private Set erpmIssueReceives = new HashSet(0);

    public ErpmIssueMaster() {
    }

	
    public ErpmIssueMaster(Departmentmaster departmentmasterByIsmToDepartmentId, Departmentmaster departmentmasterByIsmFromDepartmentId, Institutionmaster institutionmasterByIsmToInstituteId, Institutionmaster institutionmasterByIsmFromInstituteId, Subinstitutionmaster subinstitutionmasterByIsmFromSubinstituteId, Subinstitutionmaster subinstitutionmasterByIsmToSubinstituteId, String ismIssueNo, Date ismIssueDate, char ismIssueType) {
        this.departmentmasterByIsmToDepartmentId = departmentmasterByIsmToDepartmentId;
        this.departmentmasterByIsmFromDepartmentId = departmentmasterByIsmFromDepartmentId;
        this.institutionmasterByIsmToInstituteId = institutionmasterByIsmToInstituteId;
        this.institutionmasterByIsmFromInstituteId = institutionmasterByIsmFromInstituteId;
        this.subinstitutionmasterByIsmFromSubinstituteId = subinstitutionmasterByIsmFromSubinstituteId;
        this.subinstitutionmasterByIsmToSubinstituteId = subinstitutionmasterByIsmToSubinstituteId;
        this.ismIssueNo = ismIssueNo;
        this.ismIssueDate = ismIssueDate;
        this.ismIssueType = ismIssueType;
    }
    public ErpmIssueMaster(Departmentmaster departmentmasterByIsmToDepartmentId, Departmentmaster departmentmasterByIsmFromDepartmentId, Institutionmaster institutionmasterByIsmToInstituteId, Employeemaster employeemasterByIsmFromEmployeeId, Institutionmaster institutionmasterByIsmFromInstituteId, Subinstitutionmaster subinstitutionmasterByIsmFromSubinstituteId, Employeemaster employeemasterByIsmToEmployeeId, Suppliermaster suppliermaster, Subinstitutionmaster subinstitutionmasterByIsmToSubinstituteId, ErpmIndentMaster erpmIndentMaster, Committeemaster committeemaster, String ismIssueNo, Date ismIssueDate, String ismIssueDesc, String ismToEmail, char ismIssueType, Date ismReturnDueDate, String ismRemarks, Set erpmIssueDetails, Set erpmIssueReturnDetails, Set erpmIssueReceives) {
       this.departmentmasterByIsmToDepartmentId = departmentmasterByIsmToDepartmentId;
       this.departmentmasterByIsmFromDepartmentId = departmentmasterByIsmFromDepartmentId;
       this.institutionmasterByIsmToInstituteId = institutionmasterByIsmToInstituteId;
       this.employeemasterByIsmFromEmployeeId = employeemasterByIsmFromEmployeeId;
       this.institutionmasterByIsmFromInstituteId = institutionmasterByIsmFromInstituteId;
       this.subinstitutionmasterByIsmFromSubinstituteId = subinstitutionmasterByIsmFromSubinstituteId;
       this.employeemasterByIsmToEmployeeId = employeemasterByIsmToEmployeeId;
       this.suppliermaster = suppliermaster;
       this.subinstitutionmasterByIsmToSubinstituteId = subinstitutionmasterByIsmToSubinstituteId;
       this.erpmIndentMaster = erpmIndentMaster;
       this.committeemaster = committeemaster;
       this.ismIssueNo = ismIssueNo;
       this.ismIssueDate = ismIssueDate;
       this.ismIssueDesc = ismIssueDesc;
       this.ismToEmail = ismToEmail;
       this.ismIssueType = ismIssueType;
       this.ismReturnDueDate = ismReturnDueDate;
       this.ismRemarks = ismRemarks;
       this.erpmIssueDetails = erpmIssueDetails;
       this.erpmIssueReturnDetails = erpmIssueReturnDetails;
       this.erpmIssueReceives = erpmIssueReceives;
    }
   
    public Integer getIsmId() {
        return this.ismId;
    }
    
    public void setIsmId(Integer ismId) {
        this.ismId = ismId;
    }
    public Departmentmaster getDepartmentmasterByIsmToDepartmentId() {
        return this.departmentmasterByIsmToDepartmentId;
    }
    
    public void setDepartmentmasterByIsmToDepartmentId(Departmentmaster departmentmasterByIsmToDepartmentId) {
        this.departmentmasterByIsmToDepartmentId = departmentmasterByIsmToDepartmentId;
    }
    public Departmentmaster getDepartmentmasterByIsmFromDepartmentId() {
        return this.departmentmasterByIsmFromDepartmentId;
    }
    
    public void setDepartmentmasterByIsmFromDepartmentId(Departmentmaster departmentmasterByIsmFromDepartmentId) {
        this.departmentmasterByIsmFromDepartmentId = departmentmasterByIsmFromDepartmentId;
    }
    public Institutionmaster getInstitutionmasterByIsmToInstituteId() {
        return this.institutionmasterByIsmToInstituteId;
    }
    
    public void setInstitutionmasterByIsmToInstituteId(Institutionmaster institutionmasterByIsmToInstituteId) {
        this.institutionmasterByIsmToInstituteId = institutionmasterByIsmToInstituteId;
    }
    public Employeemaster getEmployeemasterByIsmFromEmployeeId() {
        return this.employeemasterByIsmFromEmployeeId;
    }
    
    public void setEmployeemasterByIsmFromEmployeeId(Employeemaster employeemasterByIsmFromEmployeeId) {
        this.employeemasterByIsmFromEmployeeId = employeemasterByIsmFromEmployeeId;
    }
    public Institutionmaster getInstitutionmasterByIsmFromInstituteId() {
        return this.institutionmasterByIsmFromInstituteId;
    }
    
    public void setInstitutionmasterByIsmFromInstituteId(Institutionmaster institutionmasterByIsmFromInstituteId) {
        this.institutionmasterByIsmFromInstituteId = institutionmasterByIsmFromInstituteId;
    }
    public Subinstitutionmaster getSubinstitutionmasterByIsmFromSubinstituteId() {
        return this.subinstitutionmasterByIsmFromSubinstituteId;
    }
    
    public void setSubinstitutionmasterByIsmFromSubinstituteId(Subinstitutionmaster subinstitutionmasterByIsmFromSubinstituteId) {
        this.subinstitutionmasterByIsmFromSubinstituteId = subinstitutionmasterByIsmFromSubinstituteId;
    }
    public Employeemaster getEmployeemasterByIsmToEmployeeId() {
        return this.employeemasterByIsmToEmployeeId;
    }
    
    public void setEmployeemasterByIsmToEmployeeId(Employeemaster employeemasterByIsmToEmployeeId) {
        this.employeemasterByIsmToEmployeeId = employeemasterByIsmToEmployeeId;
    }
    public Suppliermaster getSuppliermaster() {
        return this.suppliermaster;
    }
    
    public void setSuppliermaster(Suppliermaster suppliermaster) {
        this.suppliermaster = suppliermaster;
    }
    public Subinstitutionmaster getSubinstitutionmasterByIsmToSubinstituteId() {
        return this.subinstitutionmasterByIsmToSubinstituteId;
    }
    
    public void setSubinstitutionmasterByIsmToSubinstituteId(Subinstitutionmaster subinstitutionmasterByIsmToSubinstituteId) {
        this.subinstitutionmasterByIsmToSubinstituteId = subinstitutionmasterByIsmToSubinstituteId;
    }
    public ErpmIndentMaster getErpmIndentMaster() {
        return this.erpmIndentMaster;
    }
    
    public void setErpmIndentMaster(ErpmIndentMaster erpmIndentMaster) {
        this.erpmIndentMaster = erpmIndentMaster;
    }
    public Committeemaster getCommitteemaster() {
        return this.committeemaster;
    }
    
    public void setCommitteemaster(Committeemaster committeemaster) {
        this.committeemaster = committeemaster;
    }
    public String getIsmIssueNo() {
        return this.ismIssueNo;
    }
    
    public void setIsmIssueNo(String ismIssueNo) {
        this.ismIssueNo = ismIssueNo;
    }
    public Date getIsmIssueDate() {
        return this.ismIssueDate;
    }
    
    public void setIsmIssueDate(Date ismIssueDate) {
        this.ismIssueDate = ismIssueDate;
    }
    public String getIsmIssueDesc() {
        return this.ismIssueDesc;
    }
    
    public void setIsmIssueDesc(String ismIssueDesc) {
        this.ismIssueDesc = ismIssueDesc;
    }
    public String getIsmToEmail() {
        return this.ismToEmail;
    }
    
    public void setIsmToEmail(String ismToEmail) {
        this.ismToEmail = ismToEmail;
    }
    public char getIsmIssueType() {
        return this.ismIssueType;
    }
    
    public void setIsmIssueType(char ismIssueType) {
        this.ismIssueType = ismIssueType;
    }
    public Date getIsmReturnDueDate() {
        return this.ismReturnDueDate;
    }
    
    public void setIsmReturnDueDate(Date ismReturnDueDate) {
        this.ismReturnDueDate = ismReturnDueDate;
    }
    public String getIsmRemarks() {
        return this.ismRemarks;
    }
    
    public void setIsmRemarks(String ismRemarks) {
        this.ismRemarks = ismRemarks;
    }
    public Set getErpmIssueDetails() {
        return this.erpmIssueDetails;
    }
    
    public void setErpmIssueDetails(Set erpmIssueDetails) {
        this.erpmIssueDetails = erpmIssueDetails;
    }
    public Set getErpmIssueReturnDetails() {
        return this.erpmIssueReturnDetails;
    }
    
    public void setErpmIssueReturnDetails(Set erpmIssueReturnDetails) {
        this.erpmIssueReturnDetails = erpmIssueReturnDetails;
    }
    public Set getErpmIssueReceives() {
        return this.erpmIssueReceives;
    }
    
    public void setErpmIssueReceives(Set erpmIssueReceives) {
        this.erpmIssueReceives = erpmIssueReceives;
    }




}


