package pojo.hibernate;
// Generated 26 Mar, 2012 3:25:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ErpmIndentDetail generated by hbm2java
 */
public class ErpmIndentDetail  implements java.io.Serializable {


     private Short indtDetailId;
     private ErpmItemRate erpmItemRate;
     private ErpmIndentMaster erpmIndentMaster;
     private ErpmItemMaster erpmItemMaster;
     private short indtQuantity;
     private int indtApproxcost;
     private String indtPurpose;
     private Set erpmPoDetailses = new HashSet(0);

    public ErpmIndentDetail() {
    }

	
    public ErpmIndentDetail(ErpmIndentMaster erpmIndentMaster, ErpmItemMaster erpmItemMaster, short indtQuantity, int indtApproxcost) {
        this.erpmIndentMaster = erpmIndentMaster;
        this.erpmItemMaster = erpmItemMaster;
        this.indtQuantity = indtQuantity;
        this.indtApproxcost = indtApproxcost;
    }
    public ErpmIndentDetail(ErpmItemRate erpmItemRate, ErpmIndentMaster erpmIndentMaster, ErpmItemMaster erpmItemMaster, short indtQuantity, int indtApproxcost, String indtPurpose, Set erpmPoDetailses) {
       this.erpmItemRate = erpmItemRate;
       this.erpmIndentMaster = erpmIndentMaster;
       this.erpmItemMaster = erpmItemMaster;
       this.indtQuantity = indtQuantity;
       this.indtApproxcost = indtApproxcost;
       this.indtPurpose = indtPurpose;
       this.erpmPoDetailses = erpmPoDetailses;
    }
   
    public Short getIndtDetailId() {
        return this.indtDetailId;
    }
    
    public void setIndtDetailId(Short indtDetailId) {
        this.indtDetailId = indtDetailId;
    }
    public ErpmItemRate getErpmItemRate() {
        return this.erpmItemRate;
    }
    
    public void setErpmItemRate(ErpmItemRate erpmItemRate) {
        this.erpmItemRate = erpmItemRate;
    }
    public ErpmIndentMaster getErpmIndentMaster() {
        return this.erpmIndentMaster;
    }
    
    public void setErpmIndentMaster(ErpmIndentMaster erpmIndentMaster) {
        this.erpmIndentMaster = erpmIndentMaster;
    }
    public ErpmItemMaster getErpmItemMaster() {
        return this.erpmItemMaster;
    }
    
    public void setErpmItemMaster(ErpmItemMaster erpmItemMaster) {
        this.erpmItemMaster = erpmItemMaster;
    }
    public short getIndtQuantity() {
        return this.indtQuantity;
    }
    
    public void setIndtQuantity(short indtQuantity) {
        this.indtQuantity = indtQuantity;
    }
    public int getIndtApproxcost() {
        return this.indtApproxcost;
    }
    
    public void setIndtApproxcost(int indtApproxcost) {
        this.indtApproxcost = indtApproxcost;
    }
    public String getIndtPurpose() {
        return this.indtPurpose;
    }
    
    public void setIndtPurpose(String indtPurpose) {
        this.indtPurpose = indtPurpose;
    }
    public Set getErpmPoDetailses() {
        return this.erpmPoDetailses;
    }
    
    public void setErpmPoDetailses(Set erpmPoDetailses) {
        this.erpmPoDetailses = erpmPoDetailses;
    }




}


