package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ErpmItemMaster generated by hbm2java
 */
public class ErpmItemMaster  implements java.io.Serializable {


     private Integer erpmimId;
     private ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat1;
     private ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat3;
     private ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat2;
     private ErpmGenMaster erpmGenMaster;
     private ErpmCapitalCategory erpmCapitalCategory;
     private Institutionmaster institutionmaster;
     private String erpmimItemBriefDesc;
     private String erpmimMake;
     private String erpmimModel;
     private String erpmimDetailedDesc;
     private String erpmimRemarks;
     private String erpmimIssuePolicy;
     private char erpmimSerialNoApplicable;
     private Character erpmimDepreciationMethod;
     private Integer erpmimDepreciationPercentage;
     private Integer erpmimResidualValue;
     private Set erpmPurchaseinvoiceDetails = new HashSet(0);
     private Set erpmStockReceiveds = new HashSet(0);
     private Set erpmPurchasechallanDetails = new HashSet(0);
     private Set erpmPoLocationses = new HashSet(0);
     private Set erpmPoDetailses = new HashSet(0);
     private Set erpmItemRates = new HashSet(0);
     private Set erpmIndentDetails = new HashSet(0);
     private Set erpmTempOpeningStocks = new HashSet(0);
     private Set erpmIssueReturnDetails = new HashSet(0);
     private Set erpmIssueDetails = new HashSet(0);

    public ErpmItemMaster() {
    }

	
    public ErpmItemMaster(ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat1, ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat3, ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat2, ErpmGenMaster erpmGenMaster, String erpmimItemBriefDesc, String erpmimDetailedDesc, String erpmimIssuePolicy, char erpmimSerialNoApplicable) {
        this.erpmItemCategoryMasterByErpmimItemCat1 = erpmItemCategoryMasterByErpmimItemCat1;
        this.erpmItemCategoryMasterByErpmimItemCat3 = erpmItemCategoryMasterByErpmimItemCat3;
        this.erpmItemCategoryMasterByErpmimItemCat2 = erpmItemCategoryMasterByErpmimItemCat2;
        this.erpmGenMaster = erpmGenMaster;
        this.erpmimItemBriefDesc = erpmimItemBriefDesc;
        this.erpmimDetailedDesc = erpmimDetailedDesc;
        this.erpmimIssuePolicy = erpmimIssuePolicy;
        this.erpmimSerialNoApplicable = erpmimSerialNoApplicable;
    }
    public ErpmItemMaster(ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat1, ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat3, ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat2, ErpmGenMaster erpmGenMaster, ErpmCapitalCategory erpmCapitalCategory, Institutionmaster institutionmaster, String erpmimItemBriefDesc, String erpmimMake, String erpmimModel, String erpmimDetailedDesc, String erpmimRemarks, String erpmimIssuePolicy, char erpmimSerialNoApplicable, Character erpmimDepreciationMethod, Integer erpmimDepreciationPercentage, Integer erpmimResidualValue, Set erpmPurchaseinvoiceDetails, Set erpmStockReceiveds, Set erpmPurchasechallanDetails, Set erpmPoLocationses, Set erpmPoDetailses, Set erpmItemRates, Set erpmIndentDetails, Set erpmTempOpeningStocks, Set erpmIssueReturnDetails, Set erpmIssueDetails) {
       this.erpmItemCategoryMasterByErpmimItemCat1 = erpmItemCategoryMasterByErpmimItemCat1;
       this.erpmItemCategoryMasterByErpmimItemCat3 = erpmItemCategoryMasterByErpmimItemCat3;
       this.erpmItemCategoryMasterByErpmimItemCat2 = erpmItemCategoryMasterByErpmimItemCat2;
       this.erpmGenMaster = erpmGenMaster;
       this.erpmCapitalCategory = erpmCapitalCategory;
       this.institutionmaster = institutionmaster;
       this.erpmimItemBriefDesc = erpmimItemBriefDesc;
       this.erpmimMake = erpmimMake;
       this.erpmimModel = erpmimModel;
       this.erpmimDetailedDesc = erpmimDetailedDesc;
       this.erpmimRemarks = erpmimRemarks;
       this.erpmimIssuePolicy = erpmimIssuePolicy;
       this.erpmimSerialNoApplicable = erpmimSerialNoApplicable;
       this.erpmimDepreciationMethod = erpmimDepreciationMethod;
       this.erpmimDepreciationPercentage = erpmimDepreciationPercentage;
       this.erpmimResidualValue = erpmimResidualValue;
       this.erpmPurchaseinvoiceDetails = erpmPurchaseinvoiceDetails;
       this.erpmStockReceiveds = erpmStockReceiveds;
       this.erpmPurchasechallanDetails = erpmPurchasechallanDetails;
       this.erpmPoLocationses = erpmPoLocationses;
       this.erpmPoDetailses = erpmPoDetailses;
       this.erpmItemRates = erpmItemRates;
       this.erpmIndentDetails = erpmIndentDetails;
       this.erpmTempOpeningStocks = erpmTempOpeningStocks;
       this.erpmIssueReturnDetails = erpmIssueReturnDetails;
       this.erpmIssueDetails = erpmIssueDetails;
    }
   
    public Integer getErpmimId() {
        return this.erpmimId;
    }
    
    public void setErpmimId(Integer erpmimId) {
        this.erpmimId = erpmimId;
    }
    public ErpmItemCategoryMaster getErpmItemCategoryMasterByErpmimItemCat1() {
        return this.erpmItemCategoryMasterByErpmimItemCat1;
    }
    
    public void setErpmItemCategoryMasterByErpmimItemCat1(ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat1) {
        this.erpmItemCategoryMasterByErpmimItemCat1 = erpmItemCategoryMasterByErpmimItemCat1;
    }
    public ErpmItemCategoryMaster getErpmItemCategoryMasterByErpmimItemCat3() {
        return this.erpmItemCategoryMasterByErpmimItemCat3;
    }
    
    public void setErpmItemCategoryMasterByErpmimItemCat3(ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat3) {
        this.erpmItemCategoryMasterByErpmimItemCat3 = erpmItemCategoryMasterByErpmimItemCat3;
    }
    public ErpmItemCategoryMaster getErpmItemCategoryMasterByErpmimItemCat2() {
        return this.erpmItemCategoryMasterByErpmimItemCat2;
    }
    
    public void setErpmItemCategoryMasterByErpmimItemCat2(ErpmItemCategoryMaster erpmItemCategoryMasterByErpmimItemCat2) {
        this.erpmItemCategoryMasterByErpmimItemCat2 = erpmItemCategoryMasterByErpmimItemCat2;
    }
    public ErpmGenMaster getErpmGenMaster() {
        return this.erpmGenMaster;
    }
    
    public void setErpmGenMaster(ErpmGenMaster erpmGenMaster) {
        this.erpmGenMaster = erpmGenMaster;
    }
    public ErpmCapitalCategory getErpmCapitalCategory() {
        return this.erpmCapitalCategory;
    }
    
    public void setErpmCapitalCategory(ErpmCapitalCategory erpmCapitalCategory) {
        this.erpmCapitalCategory = erpmCapitalCategory;
    }
    public Institutionmaster getInstitutionmaster() {
        return this.institutionmaster;
    }
    
    public void setInstitutionmaster(Institutionmaster institutionmaster) {
        this.institutionmaster = institutionmaster;
    }
    public String getErpmimItemBriefDesc() {
        return this.erpmimItemBriefDesc;
    }
    
    public void setErpmimItemBriefDesc(String erpmimItemBriefDesc) {
        this.erpmimItemBriefDesc = erpmimItemBriefDesc;
    }
    public String getErpmimMake() {
        return this.erpmimMake;
    }
    
    public void setErpmimMake(String erpmimMake) {
        this.erpmimMake = erpmimMake;
    }
    public String getErpmimModel() {
        return this.erpmimModel;
    }
    
    public void setErpmimModel(String erpmimModel) {
        this.erpmimModel = erpmimModel;
    }
    public String getErpmimDetailedDesc() {
        return this.erpmimDetailedDesc;
    }
    
    public void setErpmimDetailedDesc(String erpmimDetailedDesc) {
        this.erpmimDetailedDesc = erpmimDetailedDesc;
    }
    public String getErpmimRemarks() {
        return this.erpmimRemarks;
    }
    
    public void setErpmimRemarks(String erpmimRemarks) {
        this.erpmimRemarks = erpmimRemarks;
    }
    public String getErpmimIssuePolicy() {
        return this.erpmimIssuePolicy;
    }
    
    public void setErpmimIssuePolicy(String erpmimIssuePolicy) {
        this.erpmimIssuePolicy = erpmimIssuePolicy;
    }
    public char getErpmimSerialNoApplicable() {
        return this.erpmimSerialNoApplicable;
    }
    
    public void setErpmimSerialNoApplicable(char erpmimSerialNoApplicable) {
        this.erpmimSerialNoApplicable = erpmimSerialNoApplicable;
    }
    public Character getErpmimDepreciationMethod() {
        return this.erpmimDepreciationMethod;
    }
    
    public void setErpmimDepreciationMethod(Character erpmimDepreciationMethod) {
        this.erpmimDepreciationMethod = erpmimDepreciationMethod;
    }
    public Integer getErpmimDepreciationPercentage() {
        return this.erpmimDepreciationPercentage;
    }
    
    public void setErpmimDepreciationPercentage(Integer erpmimDepreciationPercentage) {
        this.erpmimDepreciationPercentage = erpmimDepreciationPercentage;
    }
    public Integer getErpmimResidualValue() {
        return this.erpmimResidualValue;
    }
    
    public void setErpmimResidualValue(Integer erpmimResidualValue) {
        this.erpmimResidualValue = erpmimResidualValue;
    }
    public Set getErpmPurchaseinvoiceDetails() {
        return this.erpmPurchaseinvoiceDetails;
    }
    
    public void setErpmPurchaseinvoiceDetails(Set erpmPurchaseinvoiceDetails) {
        this.erpmPurchaseinvoiceDetails = erpmPurchaseinvoiceDetails;
    }
    public Set getErpmStockReceiveds() {
        return this.erpmStockReceiveds;
    }
    
    public void setErpmStockReceiveds(Set erpmStockReceiveds) {
        this.erpmStockReceiveds = erpmStockReceiveds;
    }
    public Set getErpmPurchasechallanDetails() {
        return this.erpmPurchasechallanDetails;
    }
    
    public void setErpmPurchasechallanDetails(Set erpmPurchasechallanDetails) {
        this.erpmPurchasechallanDetails = erpmPurchasechallanDetails;
    }
    public Set getErpmPoLocationses() {
        return this.erpmPoLocationses;
    }
    
    public void setErpmPoLocationses(Set erpmPoLocationses) {
        this.erpmPoLocationses = erpmPoLocationses;
    }
    public Set getErpmPoDetailses() {
        return this.erpmPoDetailses;
    }
    
    public void setErpmPoDetailses(Set erpmPoDetailses) {
        this.erpmPoDetailses = erpmPoDetailses;
    }
    public Set getErpmItemRates() {
        return this.erpmItemRates;
    }
    
    public void setErpmItemRates(Set erpmItemRates) {
        this.erpmItemRates = erpmItemRates;
    }
    public Set getErpmIndentDetails() {
        return this.erpmIndentDetails;
    }
    
    public void setErpmIndentDetails(Set erpmIndentDetails) {
        this.erpmIndentDetails = erpmIndentDetails;
    }
    public Set getErpmTempOpeningStocks() {
        return this.erpmTempOpeningStocks;
    }
    
    public void setErpmTempOpeningStocks(Set erpmTempOpeningStocks) {
        this.erpmTempOpeningStocks = erpmTempOpeningStocks;
    }
    public Set getErpmIssueReturnDetails() {
        return this.erpmIssueReturnDetails;
    }
    
    public void setErpmIssueReturnDetails(Set erpmIssueReturnDetails) {
        this.erpmIssueReturnDetails = erpmIssueReturnDetails;
    }
    public Set getErpmIssueDetails() {
        return this.erpmIssueDetails;
    }
    
    public void setErpmIssueDetails(Set erpmIssueDetails) {
        this.erpmIssueDetails = erpmIssueDetails;
    }




}


