package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ErpmIssueDetail generated by hbm2java
 */
public class ErpmIssueDetail  implements java.io.Serializable {


     private Integer isdId;
     private ErpmItemMaster erpmItemMaster;
     private ErpmIssueMaster erpmIssueMaster;
     private BigDecimal isdIssuedQuantity;
     private BigDecimal isdReceivedQuantity;
     private BigDecimal isdReturnedQuantity;
     private Set erpmIssueSerialDetails = new HashSet(0);

    public ErpmIssueDetail() {
    }

	
    public ErpmIssueDetail(ErpmItemMaster erpmItemMaster, ErpmIssueMaster erpmIssueMaster, BigDecimal isdIssuedQuantity, BigDecimal isdReceivedQuantity, BigDecimal isdReturnedQuantity) {
        this.erpmItemMaster = erpmItemMaster;
        this.erpmIssueMaster = erpmIssueMaster;
        this.isdIssuedQuantity = isdIssuedQuantity;
        this.isdReceivedQuantity = isdReceivedQuantity;
        this.isdReturnedQuantity = isdReturnedQuantity;
    }
    public ErpmIssueDetail(ErpmItemMaster erpmItemMaster, ErpmIssueMaster erpmIssueMaster, BigDecimal isdIssuedQuantity, BigDecimal isdReceivedQuantity, BigDecimal isdReturnedQuantity, Set erpmIssueSerialDetails) {
       this.erpmItemMaster = erpmItemMaster;
       this.erpmIssueMaster = erpmIssueMaster;
       this.isdIssuedQuantity = isdIssuedQuantity;
       this.isdReceivedQuantity = isdReceivedQuantity;
       this.isdReturnedQuantity = isdReturnedQuantity;
       this.erpmIssueSerialDetails = erpmIssueSerialDetails;
    }
   
    public Integer getIsdId() {
        return this.isdId;
    }
    
    public void setIsdId(Integer isdId) {
        this.isdId = isdId;
    }
    public ErpmItemMaster getErpmItemMaster() {
        return this.erpmItemMaster;
    }
    
    public void setErpmItemMaster(ErpmItemMaster erpmItemMaster) {
        this.erpmItemMaster = erpmItemMaster;
    }
    public ErpmIssueMaster getErpmIssueMaster() {
        return this.erpmIssueMaster;
    }
    
    public void setErpmIssueMaster(ErpmIssueMaster erpmIssueMaster) {
        this.erpmIssueMaster = erpmIssueMaster;
    }
    public BigDecimal getIsdIssuedQuantity() {
        return this.isdIssuedQuantity;
    }
    
    public void setIsdIssuedQuantity(BigDecimal isdIssuedQuantity) {
        this.isdIssuedQuantity = isdIssuedQuantity;
    }
    public BigDecimal getIsdReceivedQuantity() {
        return this.isdReceivedQuantity;
    }
    
    public void setIsdReceivedQuantity(BigDecimal isdReceivedQuantity) {
        this.isdReceivedQuantity = isdReceivedQuantity;
    }
    public BigDecimal getIsdReturnedQuantity() {
        return this.isdReturnedQuantity;
    }
    
    public void setIsdReturnedQuantity(BigDecimal isdReturnedQuantity) {
        this.isdReturnedQuantity = isdReturnedQuantity;
    }
    public Set getErpmIssueSerialDetails() {
        return this.erpmIssueSerialDetails;
    }
    
    public void setErpmIssueSerialDetails(Set erpmIssueSerialDetails) {
        this.erpmIssueSerialDetails = erpmIssueSerialDetails;
    }




}


