package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Erpmprogram generated by hbm2java
 */
public class Erpmprogram  implements java.io.Serializable {


     private Short erpmpId;
     private Erpmsubmodule erpmsubmodule;
     private Erpmprogram erpmprogram;
     private String erpmpDisplayName;
     private String erpmpDisplayNameHindi;
     private String erpmpPurpose;
     private String erpmpHref;
     private Byte erpmpOrder;
     private String epmpEnvVariable;
     private Set genericroleprivilegeses = new HashSet(0);
     private Set gfrProgramMappings = new HashSet(0);
     private Set erpmprograms = new HashSet(0);
     private Set userprivilegeses = new HashSet(0);
     private Set institutionroleprivilegeses = new HashSet(0);

    public Erpmprogram() {
    }

	
    public Erpmprogram(Erpmsubmodule erpmsubmodule, String erpmpDisplayName, String erpmpDisplayNameHindi) {
        this.erpmsubmodule = erpmsubmodule;
        this.erpmpDisplayName = erpmpDisplayName;
        this.erpmpDisplayNameHindi= erpmpDisplayNameHindi;
    }
    public Erpmprogram(Erpmsubmodule erpmsubmodule, Erpmprogram erpmprogram, String erpmpDisplayName,String erpmpDisplayNameHindi, String erpmpPurpose, String erpmpHref, Byte erpmpOrder, String epmpEnvVariable, Set genericroleprivilegeses, Set gfrProgramMappings, Set erpmprograms, Set userprivilegeses, Set institutionroleprivilegeses) {
       this.erpmsubmodule = erpmsubmodule;
       this.erpmprogram = erpmprogram;
       this.erpmpDisplayName = erpmpDisplayName;
       this.erpmpDisplayNameHindi = erpmpDisplayNameHindi;
       this.erpmpPurpose = erpmpPurpose;
       this.erpmpHref = erpmpHref;
       this.erpmpOrder = erpmpOrder;
       this.epmpEnvVariable = epmpEnvVariable;
       this.genericroleprivilegeses = genericroleprivilegeses;
       this.gfrProgramMappings = gfrProgramMappings;
       this.erpmprograms = erpmprograms;
       this.userprivilegeses = userprivilegeses;
       this.institutionroleprivilegeses = institutionroleprivilegeses;
    }
   
    public Short getErpmpId() {
        return this.erpmpId;
    }
    
    public void setErpmpId(Short erpmpId) {
        this.erpmpId = erpmpId;
    }
    public Erpmsubmodule getErpmsubmodule() {
        return this.erpmsubmodule;
    }
    
    public void setErpmsubmodule(Erpmsubmodule erpmsubmodule) {
        this.erpmsubmodule = erpmsubmodule;
    }
    public Erpmprogram getErpmprogram() {
        return this.erpmprogram;
    }
    
    public void setErpmprogram(Erpmprogram erpmprogram) {
        this.erpmprogram = erpmprogram;
    }
    public String getErpmpDisplayName() {
        return this.erpmpDisplayName;
    }
    
    public void setErpmpDisplayName(String erpmpDisplayName) {
        this.erpmpDisplayName = erpmpDisplayName;
    }

    public String getErpmpDisplayNameHindi() {
        return this.erpmpDisplayName;
    }

    public void setErpmpDisplayNameHindi(String erpmpDisplayName) {
        this.erpmpDisplayNameHindi = erpmpDisplayName;
    }

    public String getErpmpPurpose() {
        return this.erpmpPurpose;
    }
    
    public void setErpmpPurpose(String erpmpPurpose) {
        this.erpmpPurpose = erpmpPurpose;
    }
    public String getErpmpHref() {
        return this.erpmpHref;
    }
    
    public void setErpmpHref(String erpmpHref) {
        this.erpmpHref = erpmpHref;
    }
    public Byte getErpmpOrder() {
        return this.erpmpOrder;
    }
    
    public void setErpmpOrder(Byte erpmpOrder) {
        this.erpmpOrder = erpmpOrder;
    }
    public String getEpmpEnvVariable() {
        return this.epmpEnvVariable;
    }
    
    public void setEpmpEnvVariable(String epmpEnvVariable) {
        this.epmpEnvVariable = epmpEnvVariable;
    }
    public Set getGenericroleprivilegeses() {
        return this.genericroleprivilegeses;
    }
    
    public void setGenericroleprivilegeses(Set genericroleprivilegeses) {
        this.genericroleprivilegeses = genericroleprivilegeses;
    }
    public Set getGfrProgramMappings() {
        return this.gfrProgramMappings;
    }
    
    public void setGfrProgramMappings(Set gfrProgramMappings) {
        this.gfrProgramMappings = gfrProgramMappings;
    }
    public Set getErpmprograms() {
        return this.erpmprograms;
    }
    
    public void setErpmprograms(Set erpmprograms) {
        this.erpmprograms = erpmprograms;
    }
    public Set getUserprivilegeses() {
        return this.userprivilegeses;
    }
    
    public void setUserprivilegeses(Set userprivilegeses) {
        this.userprivilegeses = userprivilegeses;
    }
    public Set getInstitutionroleprivilegeses() {
        return this.institutionroleprivilegeses;
    }
    
    public void setInstitutionroleprivilegeses(Set institutionroleprivilegeses) {
        this.institutionroleprivilegeses = institutionroleprivilegeses;
    }




}


