package pojo.hibernate;
// Generated 26 Mar, 2012 3:25:11 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ErpmPurchasechallanDetail generated by hbm2java
 */
public class ErpmPurchasechallanDetail  implements java.io.Serializable {


     private Integer pcdPcdId;
     private ErpmPurchasechallanMaster erpmPurchasechallanMaster;
     private ErpmItemMaster erpmItemMaster;
     private BigDecimal pcdRecvQuantity;
     private Set erpmPurchasechallanSerials = new HashSet(0);

    public ErpmPurchasechallanDetail() {
    }

	
    public ErpmPurchasechallanDetail(ErpmPurchasechallanMaster erpmPurchasechallanMaster) {
        this.erpmPurchasechallanMaster = erpmPurchasechallanMaster;
    }
    public ErpmPurchasechallanDetail(ErpmPurchasechallanMaster erpmPurchasechallanMaster, ErpmItemMaster erpmItemMaster, BigDecimal pcdRecvQuantity, Set erpmPurchasechallanSerials) {
       this.erpmPurchasechallanMaster = erpmPurchasechallanMaster;
       this.erpmItemMaster = erpmItemMaster;
       this.pcdRecvQuantity = pcdRecvQuantity;
       this.erpmPurchasechallanSerials = erpmPurchasechallanSerials;
    }
   
    public Integer getPcdPcdId() {
        return this.pcdPcdId;
    }
    
    public void setPcdPcdId(Integer pcdPcdId) {
        this.pcdPcdId = pcdPcdId;
    }
    public ErpmPurchasechallanMaster getErpmPurchasechallanMaster() {
        return this.erpmPurchasechallanMaster;
    }
    
    public void setErpmPurchasechallanMaster(ErpmPurchasechallanMaster erpmPurchasechallanMaster) {
        this.erpmPurchasechallanMaster = erpmPurchasechallanMaster;
    }
    public ErpmItemMaster getErpmItemMaster() {
        return this.erpmItemMaster;
    }
    
    public void setErpmItemMaster(ErpmItemMaster erpmItemMaster) {
        this.erpmItemMaster = erpmItemMaster;
    }
    public BigDecimal getPcdRecvQuantity() {
        return this.pcdRecvQuantity;
    }
    
    public void setPcdRecvQuantity(BigDecimal pcdRecvQuantity) {
        this.pcdRecvQuantity = pcdRecvQuantity;
    }
    public Set getErpmPurchasechallanSerials() {
        return this.erpmPurchasechallanSerials;
    }
    
    public void setErpmPurchasechallanSerials(Set erpmPurchasechallanSerials) {
        this.erpmPurchasechallanSerials = erpmPurchasechallanSerials;
    }




}


