package pojo.hibernate;
// Generated 26 Mar, 2012 3:25:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Genericuserroles generated by hbm2java
 */
public class Genericuserroles  implements java.io.Serializable {


     private Byte gurId;
     private String gurRoleName;
     private String gurDescription;
     private Set genericroleprivilegeses = new HashSet(0);

    public Genericuserroles() {
    }

	
    public Genericuserroles(String gurRoleName) {
        this.gurRoleName = gurRoleName;
    }
    public Genericuserroles(String gurRoleName, String gurDescription, Set genericroleprivilegeses) {
       this.gurRoleName = gurRoleName;
       this.gurDescription = gurDescription;
       this.genericroleprivilegeses = genericroleprivilegeses;
    }
   
    public Byte getGurId() {
        return this.gurId;
    }
    
    public void setGurId(Byte gurId) {
        this.gurId = gurId;
    }
    public String getGurRoleName() {
        return this.gurRoleName;
    }
    
    public void setGurRoleName(String gurRoleName) {
        this.gurRoleName = gurRoleName;
    }
    public String getGurDescription() {
        return this.gurDescription;
    }
    
    public void setGurDescription(String gurDescription) {
        this.gurDescription = gurDescription;
    }
    public Set getGenericroleprivilegeses() {
        return this.genericroleprivilegeses;
    }
    
    public void setGenericroleprivilegeses(Set genericroleprivilegeses) {
        this.genericroleprivilegeses = genericroleprivilegeses;
    }




}


