package pojo.hibernate;
// Generated 16 Nov, 2012 3:00:48 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * ViewStockReceived generated by hbm2java
 */
public class ViewStockReceived  implements java.io.Serializable {


     private int stId;
     private short stImId;
     private int stSimId;
     private int stDmId;
     private Integer stSmId;
     private int stItemId;
     private Date stInStockSince;
     private Integer stChallanDetId;
     private String stPoNo;
     private Date stPoDate;
     private String stChallanNo;
     private Date stChallanDate;
     private String stInvoiceNo;
     private Date stInvoiceDate;
     private BigDecimal stQuantity;
     private BigDecimal stUnitRate;
     private BigDecimal stTaxValue;
     private String stCsrNo;
     private Integer stCsrPgNo;
     private String stDeptSrNo;
     private Integer stDeptSrPgNo;
     private String stProductNo;
     private String stStockSerialNo;
     private Date stWarrantyExpiryDate;
     private Integer stWarrantyTypeId;
     private String serialCode;

    public ViewStockReceived() {
    }

	
    public ViewStockReceived(int stId, short stImId, int stSimId, int stDmId, int stItemId) {
        this.stId = stId;
        this.stImId = stImId;
        this.stSimId = stSimId;
        this.stDmId = stDmId;
        this.stItemId = stItemId;
    }
    public ViewStockReceived(int stId, short stImId, int stSimId, int stDmId, Integer stSmId, int stItemId, Date stInStockSince, Integer stChallanDetId, String stPoNo, Date stPoDate, String stChallanNo, Date stChallanDate, String stInvoiceNo, Date stInvoiceDate, BigDecimal stQuantity, BigDecimal stUnitRate, BigDecimal stTaxValue, String stCsrNo, Integer stCsrPgNo, String stDeptSrNo, Integer stDeptSrPgNo, String stProductNo, String stStockSerialNo, Date stWarrantyExpiryDate, Integer stWarrantyTypeId, String serialCode) {
       this.stId = stId;
       this.stImId = stImId;
       this.stSimId = stSimId;
       this.stDmId = stDmId;
       this.stSmId = stSmId;
       this.stItemId = stItemId;
       this.stInStockSince = stInStockSince;
       this.stChallanDetId = stChallanDetId;
       this.stPoNo = stPoNo;
       this.stPoDate = stPoDate;
       this.stChallanNo = stChallanNo;
       this.stChallanDate = stChallanDate;
       this.stInvoiceNo = stInvoiceNo;
       this.stInvoiceDate = stInvoiceDate;
       this.stQuantity = stQuantity;
       this.stUnitRate = stUnitRate;
       this.stTaxValue = stTaxValue;
       this.stCsrNo = stCsrNo;
       this.stCsrPgNo = stCsrPgNo;
       this.stDeptSrNo = stDeptSrNo;
       this.stDeptSrPgNo = stDeptSrPgNo;
       this.stProductNo = stProductNo;
       this.stStockSerialNo = stStockSerialNo;
       this.stWarrantyExpiryDate = stWarrantyExpiryDate;
       this.stWarrantyTypeId = stWarrantyTypeId;
       this.serialCode = serialCode;
    }
   
    public int getStId() {
        return this.stId;
    }
    
    public void setStId(int stId) {
        this.stId = stId;
    }
    public short getStImId() {
        return this.stImId;
    }
    
    public void setStImId(short stImId) {
        this.stImId = stImId;
    }
    public int getStSimId() {
        return this.stSimId;
    }
    
    public void setStSimId(int stSimId) {
        this.stSimId = stSimId;
    }
    public int getStDmId() {
        return this.stDmId;
    }
    
    public void setStDmId(int stDmId) {
        this.stDmId = stDmId;
    }
    public Integer getStSmId() {
        return this.stSmId;
    }
    
    public void setStSmId(Integer stSmId) {
        this.stSmId = stSmId;
    }
    public int getStItemId() {
        return this.stItemId;
    }
    
    public void setStItemId(int stItemId) {
        this.stItemId = stItemId;
    }
    public Date getStInStockSince() {
        return this.stInStockSince;
    }
    
    public void setStInStockSince(Date stInStockSince) {
        this.stInStockSince = stInStockSince;
    }
    public Integer getStChallanDetId() {
        return this.stChallanDetId;
    }
    
    public void setStChallanDetId(Integer stChallanDetId) {
        this.stChallanDetId = stChallanDetId;
    }
    public String getStPoNo() {
        return this.stPoNo;
    }
    
    public void setStPoNo(String stPoNo) {
        this.stPoNo = stPoNo;
    }
    public Date getStPoDate() {
        return this.stPoDate;
    }
    
    public void setStPoDate(Date stPoDate) {
        this.stPoDate = stPoDate;
    }
    public String getStChallanNo() {
        return this.stChallanNo;
    }
    
    public void setStChallanNo(String stChallanNo) {
        this.stChallanNo = stChallanNo;
    }
    public Date getStChallanDate() {
        return this.stChallanDate;
    }
    
    public void setStChallanDate(Date stChallanDate) {
        this.stChallanDate = stChallanDate;
    }
    public String getStInvoiceNo() {
        return this.stInvoiceNo;
    }
    
    public void setStInvoiceNo(String stInvoiceNo) {
        this.stInvoiceNo = stInvoiceNo;
    }
    public Date getStInvoiceDate() {
        return this.stInvoiceDate;
    }
    
    public void setStInvoiceDate(Date stInvoiceDate) {
        this.stInvoiceDate = stInvoiceDate;
    }
    public BigDecimal getStQuantity() {
        return this.stQuantity;
    }
    
    public void setStQuantity(BigDecimal stQuantity) {
        this.stQuantity = stQuantity;
    }
    public BigDecimal getStUnitRate() {
        return this.stUnitRate;
    }
    
    public void setStUnitRate(BigDecimal stUnitRate) {
        this.stUnitRate = stUnitRate;
    }
    public BigDecimal getStTaxValue() {
        return this.stTaxValue;
    }
    
    public void setStTaxValue(BigDecimal stTaxValue) {
        this.stTaxValue = stTaxValue;
    }
    public String getStCsrNo() {
        return this.stCsrNo;
    }
    
    public void setStCsrNo(String stCsrNo) {
        this.stCsrNo = stCsrNo;
    }
    public Integer getStCsrPgNo() {
        return this.stCsrPgNo;
    }
    
    public void setStCsrPgNo(Integer stCsrPgNo) {
        this.stCsrPgNo = stCsrPgNo;
    }
    public String getStDeptSrNo() {
        return this.stDeptSrNo;
    }
    
    public void setStDeptSrNo(String stDeptSrNo) {
        this.stDeptSrNo = stDeptSrNo;
    }
    public Integer getStDeptSrPgNo() {
        return this.stDeptSrPgNo;
    }
    
    public void setStDeptSrPgNo(Integer stDeptSrPgNo) {
        this.stDeptSrPgNo = stDeptSrPgNo;
    }
    public String getStProductNo() {
        return this.stProductNo;
    }
    
    public void setStProductNo(String stProductNo) {
        this.stProductNo = stProductNo;
    }
    public String getStStockSerialNo() {
        return this.stStockSerialNo;
    }
    
    public void setStStockSerialNo(String stStockSerialNo) {
        this.stStockSerialNo = stStockSerialNo;
    }
    public Date getStWarrantyExpiryDate() {
        return this.stWarrantyExpiryDate;
    }
    
    public void setStWarrantyExpiryDate(Date stWarrantyExpiryDate) {
        this.stWarrantyExpiryDate = stWarrantyExpiryDate;
    }
    public Integer getStWarrantyTypeId() {
        return this.stWarrantyTypeId;
    }
    
    public void setStWarrantyTypeId(Integer stWarrantyTypeId) {
        this.stWarrantyTypeId = stWarrantyTypeId;
    }
    public String getSerialCode() {
        return this.serialCode;
    }
    
    public void setSerialCode(String serialCode) {
        this.serialCode = serialCode;
    }




}


