package pojo.hibernate;
// Generated Sep 13, 2012 5:14:15 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ViewIssueSerialDetail generated by hbm2java
 */
public class ViewIssueSerialDetail  implements java.io.Serializable {


     private Long issdId;
     private int isdId;
     private int isdIsmId;
     private int isdItemId;
     private BigDecimal isdIssuedQuantity;
     private BigDecimal isdReceivedQuantity;
     private BigDecimal isdReturnedQuantity;
     private Long issdIsdId;
     private Long issdStockSerialId;
     private Integer issdReceived;
     private Integer issdReturned;
     private String stStockSerialNo;
     private BigDecimal displayQuantity;
     private String erpmimItemBriefDesc;
     private char erpmimSerialNoApplicable;
     private String ismIssueNo;

    public ViewIssueSerialDetail() {
    }

	
    public ViewIssueSerialDetail(Long issdId, int isdId, int isdIsmId, int isdItemId, BigDecimal isdIssuedQuantity, BigDecimal isdReceivedQuantity, BigDecimal isdReturnedQuantity, String erpmimItemBriefDesc, char erpmimSerialNoApplicable) {
        this.issdId = issdId;
        this.isdId = isdId;
        this.isdIsmId = isdIsmId;
        this.isdItemId = isdItemId;
        this.isdIssuedQuantity = isdIssuedQuantity;
        this.isdReceivedQuantity = isdReceivedQuantity;
        this.isdReturnedQuantity = isdReturnedQuantity;
        this.erpmimItemBriefDesc = erpmimItemBriefDesc;
        this.erpmimSerialNoApplicable = erpmimSerialNoApplicable;
    }
    public ViewIssueSerialDetail(Long issdId, int isdId, int isdIsmId, int isdItemId, BigDecimal isdIssuedQuantity, BigDecimal isdReceivedQuantity, BigDecimal isdReturnedQuantity, Long issdIsdId, Long issdStockSerialId, Integer issdReceived, Integer issdReturned, String stStockSerialNo, BigDecimal displayQuantity, String erpmimItemBriefDesc, char erpmimSerialNoApplicable, String ismIssueNo) {
       this.issdId = issdId;
       this.isdId = isdId;
       this.isdIsmId = isdIsmId;
       this.isdItemId = isdItemId;
       this.isdIssuedQuantity = isdIssuedQuantity;
       this.isdReceivedQuantity = isdReceivedQuantity;
       this.isdReturnedQuantity = isdReturnedQuantity;
       this.issdIsdId = issdIsdId;
       this.issdStockSerialId = issdStockSerialId;
       this.issdReceived = issdReceived;
       this.issdReturned = issdReturned;
       this.stStockSerialNo = stStockSerialNo;
       this.displayQuantity = displayQuantity;
       this.erpmimItemBriefDesc = erpmimItemBriefDesc;
       this.erpmimSerialNoApplicable = erpmimSerialNoApplicable;
       this.ismIssueNo = ismIssueNo;
    }
   
    public Long getIssdId() {
        return this.issdId;
    }
    
    public void setIssdId(Long issdId) {
        this.issdId = issdId;
    }
    public int getIsdId() {
        return this.isdId;
    }
    
    public void setIsdId(int isdId) {
        this.isdId = isdId;
    }
    public int getIsdIsmId() {
        return this.isdIsmId;
    }
    
    public void setIsdIsmId(int isdIsmId) {
        this.isdIsmId = isdIsmId;
    }
    public int getIsdItemId() {
        return this.isdItemId;
    }
    
    public void setIsdItemId(int isdItemId) {
        this.isdItemId = isdItemId;
    }
    public BigDecimal getIsdIssuedQuantity() {
        return this.isdIssuedQuantity;
    }
    
    public void setIsdIssuedQuantity(BigDecimal isdIssuedQuantity) {
        this.isdIssuedQuantity = isdIssuedQuantity;
    }
    public BigDecimal getIsdReceivedQuantity() {
        return this.isdReceivedQuantity;
    }
    
    public void setIsdReceivedQuantity(BigDecimal isdReceivedQuantity) {
        this.isdReceivedQuantity = isdReceivedQuantity;
    }
    public BigDecimal getIsdReturnedQuantity() {
        return this.isdReturnedQuantity;
    }
    
    public void setIsdReturnedQuantity(BigDecimal isdReturnedQuantity) {
        this.isdReturnedQuantity = isdReturnedQuantity;
    }
    public Long getIssdIsdId() {
        return this.issdIsdId;
    }
    
    public void setIssdIsdId(Long issdIsdId) {
        this.issdIsdId = issdIsdId;
    }
    public Long getIssdStockSerialId() {
        return this.issdStockSerialId;
    }
    
    public void setIssdStockSerialId(Long issdStockSerialId) {
        this.issdStockSerialId = issdStockSerialId;
    }
    public Integer getIssdReceived() {
        return this.issdReceived;
    }
    
    public void setIssdReceived(Integer issdReceived) {
        this.issdReceived = issdReceived;
    }
    public Integer getIssdReturned() {
        return this.issdReturned;
    }
    
    public void setIssdReturned(Integer issdReturned) {
        this.issdReturned = issdReturned;
    }
    public String getStStockSerialNo() {
        return this.stStockSerialNo;
    }
    
    public void setStStockSerialNo(String stStockSerialNo) {
        this.stStockSerialNo = stStockSerialNo;
    }
    public BigDecimal getDisplayQuantity() {
        return this.displayQuantity;
    }
    
    public void setDisplayQuantity(BigDecimal displayQuantity) {
        this.displayQuantity = displayQuantity;
    }
    public String getErpmimItemBriefDesc() {
        return this.erpmimItemBriefDesc;
    }
    
    public void setErpmimItemBriefDesc(String erpmimItemBriefDesc) {
        this.erpmimItemBriefDesc = erpmimItemBriefDesc;
    }
    public char getErpmimSerialNoApplicable() {
        return this.erpmimSerialNoApplicable;
    }
    
    public void setErpmimSerialNoApplicable(char erpmimSerialNoApplicable) {
        this.erpmimSerialNoApplicable = erpmimSerialNoApplicable;
    }
    public String getIsmIssueNo() {
        return this.ismIssueNo;
    }
    
    public void setIsmIssueNo(String ismIssueNo) {
        this.ismIssueNo = ismIssueNo;
    }




}


