package pojo.hibernate;
// Generated May 30, 2013 2:31:14 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Workflowtransaction generated by hbm2java
 */
public class Workflowtransaction  implements java.io.Serializable {


     private Integer wftId;
     private ErpmGenMaster erpmGenMaster;
     private Committeemaster committeemasterByWftDestinationId;
     private Committeemaster committeemasterByWftSourceId;
     private Workflowmaster workflowmaster;
     private Date wftDate;
     private int wftWorkId;
     private Integer wftStage;
     private String wftDestinationEmail;
     private String wftActionRemarks;

    public Workflowtransaction() {
    }

	
    public Workflowtransaction(Workflowmaster workflowmaster, Date wftDate, int wftWorkId) {
        this.workflowmaster = workflowmaster;
        this.wftDate = wftDate;
        this.wftWorkId = wftWorkId;
    }
    public Workflowtransaction(ErpmGenMaster erpmGenMaster, Committeemaster committeemasterByWftDestinationId, Committeemaster committeemasterByWftSourceId, Workflowmaster workflowmaster, Date wftDate, int wftWorkId, Integer wftStage, String wftDestinationEmail, String wftActionRemarks) {
       this.erpmGenMaster = erpmGenMaster;
       this.committeemasterByWftDestinationId = committeemasterByWftDestinationId;
       this.committeemasterByWftSourceId = committeemasterByWftSourceId;
       this.workflowmaster = workflowmaster;
       this.wftDate = wftDate;
       this.wftWorkId = wftWorkId;
       this.wftStage = wftStage;
       this.wftDestinationEmail = wftDestinationEmail;
       this.wftActionRemarks = wftActionRemarks;
    }
   
    public Integer getWftId() {
        return this.wftId;
    }
    
    public void setWftId(Integer wftId) {
        this.wftId = wftId;
    }
    public ErpmGenMaster getErpmGenMaster() {
        return this.erpmGenMaster;
    }
    
    public void setErpmGenMaster(ErpmGenMaster erpmGenMaster) {
        this.erpmGenMaster = erpmGenMaster;
    }
    public Committeemaster getCommitteemasterByWftDestinationId() {
        return this.committeemasterByWftDestinationId;
    }
    
    public void setCommitteemasterByWftDestinationId(Committeemaster committeemasterByWftDestinationId) {
        this.committeemasterByWftDestinationId = committeemasterByWftDestinationId;
    }
    public Committeemaster getCommitteemasterByWftSourceId() {
        return this.committeemasterByWftSourceId;
    }
    
    public void setCommitteemasterByWftSourceId(Committeemaster committeemasterByWftSourceId) {
        this.committeemasterByWftSourceId = committeemasterByWftSourceId;
    }
    public Workflowmaster getWorkflowmaster() {
        return this.workflowmaster;
    }
    
    public void setWorkflowmaster(Workflowmaster workflowmaster) {
        this.workflowmaster = workflowmaster;
    }
    public Date getWftDate() {
        return this.wftDate;
    }
    
    public void setWftDate(Date wftDate) {
        this.wftDate = wftDate;
    }
    public int getWftWorkId() {
        return this.wftWorkId;
    }
    
    public void setWftWorkId(int wftWorkId) {
        this.wftWorkId = wftWorkId;
    }
    public Integer getWftStage() {
        return this.wftStage;
    }
    
    public void setWftStage(Integer wftStage) {
        this.wftStage = wftStage;
    }
    public String getWftDestinationEmail() {
        return this.wftDestinationEmail;
    }
    
    public void setWftDestinationEmail(String wftDestinationEmail) {
        this.wftDestinationEmail = wftDestinationEmail;
    }
    public String getWftActionRemarks() {
        return this.wftActionRemarks;
    }
    
    public void setWftActionRemarks(String wftActionRemarks) {
        this.wftActionRemarks = wftActionRemarks;
    }




}


