CREATE TABLE `admissionentrancedata` (
  `id` int(20) NOT NULL,
  `Study_Center` varchar(255) NOT NULL,
  `Programme_Applied_for` varchar(255) NOT NULL,
  `Branch_For_Graduate_Courses` varchar(255) NOT NULL,
  `Branch_Applied_for_BA-Hons_Programmes` varchar(255) NOT NULL,
  `Branch_Applied_for_BCom_Hons_Programmes` varchar(255)NOT NULL,
  `Branch_Applied_for_Professional_Programmes` varchar(255) NOT NULL,
  `Branch_Applied_for_B.Sc_Hons_Programmes`varchar(255) NOT NULL,
  `Branch_Applied_for_Programmes_of_Study_of_Research` varchar(255) NOT NULL,
  `Branch_Applied_for_Programmes_of_Study_of_Research_Mpur` varchar(255) NOT NULL,
  `Branch_Applied_for_Programmes_of_Study_of_Post_Graduate_Mpur`varchar(255) NOT NULL,
  `Branch_Applied_for_Programmes_of_Study_of_Post_Graduate` varchar(255) NOT NULL, 
  `EntranceExam_Center` varchar(255) NOT NULL,
  `Name_of_the_Applicant` varchar(255) NOT NULL,
  `Email` varchar(255) NOT NULL,
  `Mobile` varchar(255) NOT NULL,
  `Gender` varchar(255) NOT NULL,
  `Date_of_Birth`varchar(255) NOT NULL,
  `Age` varchar(255) NOT NULL,
  `Age_in_months`varchar(255) NOT NULL,
  `Marital_Status` varchar(255) NOT NULL,
  `Category`varchar(255) NOT NULL,
  `Are_You_Physically_Handicapped` varchar(255) NOT NULL,
  `disability_percentage` varchar(255) NOT NULL,
  `Disability_type` varchar(255) NOT NULL,
  `Religion`varchar(255) NOT NULL,
  `OtherReligion`varchar(255) NOT NULL,
  `Nationality` varchar(255) NOT NULL,
  `Present_State` varchar(255) NOT NULL,
  `Address_for_Correspondence`varchar(255) NOT NULL,
  `Permanent_Address` varchar(255) NOT NULL,
  `Fathers_Name`varchar(255) NOT NULL,
  `Mothers_Name` varchar(255) NOT NULL,
  `Fathers_MobileNo` varchar(255) NOT NULL,
  `Mothers_MobileNo` varchar(255) NOT NULL,
  `Fathers_occupation`varchar(255) NOT NULL,
  `Mothers_occupation` varchar(255) NOT NULL,
  `Mothers_email_ID` varchar(255) NOT NULL,
  `Mothers_contact_number` varchar(255) NOT NULL,
  `Name_of_the_Institution_StdX` varchar(255) NOT NULL,
  `Board_University_StdX` varchar(255) NOT NULL,
  `Year_of_Passing_StdX` varchar(255) NOT NULL,
  `Marks_Obtained_StdX` varchar(255) NOT NULL,
  `Max_Marks_StdX` varchar(255) NOT NULL,
  `Marks_percentage_StdX` varchar(255) NOT NULL,
  `Name_of_the Institution_StdXII`varchar(255) NOT NULL,
  `Board_University_StdXII` varchar(255) NOT NULL,
  `Year_of_Passing_StdXII` varchar(255) NOT NULL,
  `Result_declared_StdXII`varchar(255) NOT NULL,
  `Marks_Obtained_StdXII`varchar(255) NOT NULL,    
  `Max_Marks_Std_XII` varchar(255) NOT NULL,
  `Marks_percentage_Std_XII` varchar(255) NOT NULL,
  `Name_of_the_Institution_Graduation` varchar(255) NOT NULL,
  `Board_University_Graduation` varchar(255) NOT NULL,
  `Year_of_Passing_Appearing_Graduation` varchar(255) NOT NULL,
  `Result_declared_Graduation`varchar(255) NOT NULL,
  `Marks_Obtained_Graduation` varchar(255) NOT NULL,
  `Max_Marks_Graduation` varchar(255) NOT NULL,
  `Subject_Graduation` varchar(255) NOT NULL,
  `Marks_percentage_Graduation`varchar(255) NOT NULL,
  `Name_of_the_Institution_Post_Graduarion` varchar(255) NOT NULL,
  `Board_University_Post_Graduarion` varchar(255) NOT NULL,
  `Year_of_Passing_Appearing_Post_Graduarion` varchar(255)NOT NULL,
  `Subject_Post_Graduation`varchar(255) NOT NULL, 
  `Result_declared_Post_Graduarion` varchar(255) NOT NULL,
  `Marks_Obtained_Post_Graduarion`varchar(255) NOT NULL,
  `Max_Marks_Post_Graduarion`varchar(255) NOT NULL,
  `percentage_of_Marks_Post_Graduarion`varchar(255) NOT NULL,
  `Name_of_the_Institution_MPhil`varchar(255) NOT NULL,
  `Board_University_MPhil` varchar(255) NOT NULL,
  `Year_of_Passing_Appearing_MPhil`varchar(255) NOT NULL, 
  `Marks_Obtained_MPhil` varchar(255) NOT NULL,
  `Subject_Mphil`varchar(255) NOT NULL,
  `Max_Marks_MPhil`varchar(255) NOT NULL,
  `Marks_percentage_MPhil`varchar(255) NOT NULL,
  `Name_of_the_Institution_UGC_NET_SET_SLET_GATE` varchar(255) NOT NULL,
  `Board_University_UGC_NET_SET_SLET_GATE` varchar(255) NOT NULL,
  `Are_you_UGCNET_UGC_JRF_CSIR_NET_CSIR_JRF_SET_SLET_qualified` varchar(255) NOT NULL,
  `Year_of_Passing_Appearing_UGC_NET_SET_SLET_GATE` varchar(255) NOT NULL,
  `Marks_Obtained_UGC_NET_SET_SLET_GATE` varchar(255) NOT NULL,
  `Max_Marks_UGC_NET_SET_SLET_GATE`varchar(255) NOT NULL,
  `Subject_UGC_CSIR_NET_SET_SLET_GATE` varchar(255) NOT NULL,
  `Marks_percentage_UGC_NET_SET_SLET_GATE` varchar(255) NOT NULL,
  `Name_of_the_Institution_Other` varchar(255) NOT NULL,
  `Board_University_Other`varchar(255) NOT NULL,
  `Subject_Other` varchar(255) NOT NULL,
  `Year_of_Passing_Appearing_Other`varchar(255) NOT NULL,
  `Result_declared_Other` varchar(255) NOT NULL,
  `Marks_Obtained_Other`varchar(255) NOT NULL,
  `Result_waiting`varchar(255) NOT NULL,  
  `Max_Marks_Other` varchar(255) NOT NULL,
  `percentage_of_Marks_Other`varchar(255) NOT NULL,
  `JEE_Main_RollNo` varchar(255) NOT NULL,
  `JEE_Main_Rank`varchar(255) NOT NULL,
  `JEE_Main_Score` varchar(255) NOT NULL,
  `JEE_Main_State`varchar(255) NOT NULL,
  `MAT_RollNo`varchar(255) NOT NULL,
  `MAT_Rank` varchar(255) NOT NULL,
  `MAT_Score` varchar(255) NOT NULL,
  `MAT_State`varchar(255) NOT NULL,
  `CMAT_RollNo` varchar(255) NOT NULL,
  `CMAT_Rank` varchar(255) NOT NULL,
  `CMAT_Score` varchar(255) NOT NULL,
  `CMAT_State` varchar(255) NOT NULL,
  `GATE_Roll_No` varchar(255) NOT NULL,
  `GATE_Rank`varchar(255) NOT NULL,
  `GATE_Score`varchar(255) NOT NULL,
  `GATE_State`varchar(255) NOT NULL,
  `M_Phil_Roll_No`varchar(255) NOT NULL,
  `M_Phil_Rank`varchar(255) NOT NULL,
  `M_Phil_Score`varchar(255) NOT NULL,
  `M_Phil_State`varchar(255) NOT NULL,
  `NET_Roll_No`varchar(255) NOT NULL,
  `NET_Rank` varchar(255) NOT NULL,
  `NET_Score`varchar(255) NOT NULL,
  `NET_State` varchar(255) NOT NULL,
  `SLET_Roll_No`varchar(255) NOT NULL,
  `SLET_Rank`varchar(255) NOT NULL,
  `SLET_Score`varchar(255) NOT NULL,
  `SLET_State`varchar(255) NOT NULL,
  `Name_of_the_University_Institute`varchar(255) NOT NULL,
  `Name_of_post` varchar(255)NOT NULL,
  `Present_Pay_Grade` varchar(255) NOT NULL,
  `Nature_of_Appointment`varchar(255) NOT NULL,
  `Date_of_Joining` varchar(255) NOT NULL,
  `Remarks`varchar(255) NOT NULL,
  `Previous_Experience_if_any` varchar(255) NOT NULL,
  `Name_of_the_University_Institute2` varchar(255) NOT NULL,
  `Name_of_post2` varchar(255) NOT NULL,
  `Present_Pay_Grade2` varchar(255) NOT NULL,
  `Nature_of_Appointment2` varchar(255) NOT NULL,
  `Date_of_Joining2` varchar(255) NOT NULL,
  `Remarks2`varchar(255) NOT NULL,
  `Previous_Experience_if_any2` varchar(255) NOT NULL,
  `Name_of_the_University_Institute3` varchar(255) NOT NULL,
  `Subject_for_which_registered`varchar(255) NOT NULL,
  `Name_of_the_Supervisor` varchar(255) NOT NULL,
  `Period` varchar(255) NOT NULL,
  `Topic_of_research` varchar(255) NOT NULL,
  `Reasons_for_leaving` varchar(255) NOT NULL,
  `Areas_of_interest_for_research` varchar(255) NOT NULL,
  `Payment_Mode`varchar(255) NOT NULL,
  `Application_No` varchar(255) NOT NULL,
  `Payment_Date` varchar(255) NOT NULL,
  `Amount` varchar(255) NOT NULL,
  `Published` varchar(255) NOT NULL
) ENGINE = InnoDB;
