use brihaspati;

drop table if exists STUDENT_EXPIRY;

CREATE TABLE STUDENT_EXPIRY
(
        ID INTEGER NOT NULL,
	UID INTEGER NOT NULL,
	EMAIL VARCHAR (255) NOT NULL,
        CID VARCHAR (255) NOT NULL,
	ROLL_NO VARCHAR(255) NOT NULL,	
	EXPIRY_DAYS INTEGER NOT NULL,
        EXPIRY_DATE TIMESTAMP NOT NULL,
	STATUS VARCHAR (255) DEFAULT 'ENABLE', 
        PRIMARY KEY(ID)
);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (145, 'STUDENT_EXPIRY', 1000, 10);


