/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.dei.edrp.pms.searching;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/**
 * This class contains the setter getter methods for ProjectSearch.jsp page.
 */

public class ProjectSearchForm extends ValidatorForm {
	
	private static final long serialVersionUID = 1L;
	/*
	 * Generated fields
	 */

	private String keysearch;	//for holding searching element.
	private String searchOption="Project Name";
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	/*public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
				ActionErrors errors = new ActionErrors();
				if((keysearch == null) || (keysearch.length() < 1))
					errors.add("keysearch",new ActionMessage("page.fail","keysearch"));
			return errors;	
			}*/

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	/**
	 * The method getSearchOption return searching option.
	 * */
		public String getSearchOption() {
			return searchOption;
		}
		/**
		 * The method setSearchOption is used for setting the search option in variable searchOption. 
		 * */
		
		public void setSearchOption(String searchOption) {
			this.searchOption = searchOption;
		}

	
	
/**
 * The method getKeysearch return searching element.
 * */
	public String getKeysearch() {
		return keysearch;
	}
	/**
	 * The method setKeysearch is used for setting the search element in variable keysearch. 
	 * */
	
	public void setKeysearch(String keysearch) {
		this.keysearch = keysearch;
	}

}