package org.nmeict.smvdu.Beans;
// Generated Mar 30, 2013 9:21:41 AM by Hibernate Tools 3.2.1.GA



/**
 * AdminEmailConfig generated by hbm2java
 */
public class AdminEmailConfig  implements java.io.Serializable {


     private String adminEmailid;
     private AdminRecords adminRecords;
     private String adminConfigPass;
     private Byte adminEmailStatus;

    public AdminEmailConfig() {
    }

	
    public AdminEmailConfig(String adminEmailid) {
        this.adminEmailid = adminEmailid;
    }
    public AdminEmailConfig(String adminEmailid, AdminRecords adminRecords, String adminConfigPass, Byte adminEmailStatus) {
       this.adminEmailid = adminEmailid;
       this.adminRecords = adminRecords;
       this.adminConfigPass = adminConfigPass;
       this.adminEmailStatus = adminEmailStatus;
    }
   
    public String getAdminEmailid() {
        return this.adminEmailid;
    }
    
    public void setAdminEmailid(String adminEmailid) {
        this.adminEmailid = adminEmailid;
    }
    public AdminRecords getAdminRecords() {
        return this.adminRecords;
    }
    
    public void setAdminRecords(AdminRecords adminRecords) {
        this.adminRecords = adminRecords;
    }
    public String getAdminConfigPass() {
        return this.adminConfigPass;
    }
    
    public void setAdminConfigPass(String adminConfigPass) {
        this.adminConfigPass = adminConfigPass;
    }
    public Byte getAdminEmailStatus() {
        return this.adminEmailStatus;
    }
    
    public void setAdminEmailStatus(Byte adminEmailStatus) {
        this.adminEmailStatus = adminEmailStatus;
    }




}


