package org.nmeict.smvdu.Beans;
// Generated Mar 30, 2013 9:21:41 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ChallanMaster generated by hbm2java
 */
public class ChallanMaster  implements java.io.Serializable {


     private Integer cmSeqId;
     private OrgProfile orgProfile;
     private DegreeType degreeType;
     private String entryNo;
     private String examCode;
     private int challanNo;
     private Date challanDate;
     private float amount;
     private String accountHead;
     private double balance;

    public ChallanMaster() {
    }

    public ChallanMaster(OrgProfile orgProfile, DegreeType degreeType, String entryNo, String examCode, int challanNo, Date challanDate, float amount, String accountHead, double balance) {
       this.orgProfile = orgProfile;
       this.degreeType = degreeType;
       this.entryNo = entryNo;
       this.examCode = examCode;
       this.challanNo = challanNo;
       this.challanDate = challanDate;
       this.amount = amount;
       this.accountHead = accountHead;
       this.balance = balance;
    }
   
    public Integer getCmSeqId() {
        return this.cmSeqId;
    }
    
    public void setCmSeqId(Integer cmSeqId) {
        this.cmSeqId = cmSeqId;
    }
    public OrgProfile getOrgProfile() {
        return this.orgProfile;
    }
    
    public void setOrgProfile(OrgProfile orgProfile) {
        this.orgProfile = orgProfile;
    }
    public DegreeType getDegreeType() {
        return this.degreeType;
    }
    
    public void setDegreeType(DegreeType degreeType) {
        this.degreeType = degreeType;
    }
    public String getEntryNo() {
        return this.entryNo;
    }
    
    public void setEntryNo(String entryNo) {
        this.entryNo = entryNo;
    }
    public String getExamCode() {
        return this.examCode;
    }
    
    public void setExamCode(String examCode) {
        this.examCode = examCode;
    }
    public int getChallanNo() {
        return this.challanNo;
    }
    
    public void setChallanNo(int challanNo) {
        this.challanNo = challanNo;
    }
    public Date getChallanDate() {
        return this.challanDate;
    }
    
    public void setChallanDate(Date challanDate) {
        this.challanDate = challanDate;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    public String getAccountHead() {
        return this.accountHead;
    }
    
    public void setAccountHead(String accountHead) {
        this.accountHead = accountHead;
    }
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }




}


