package org.nmeict.smvdu.Beans;
// Generated Mar 30, 2013 9:21:41 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MopHeadFields generated by hbm2java
 */
public class MopHeadFields  implements java.io.Serializable {


     private Integer id;
     private OrgProfile orgProfile;
     private ModeOfPayment modeOfPayment;
     private String headFieldName;
     private int headFieldCreatorId;
     private Date headFieldCreatorDateTime;
     private Date headFieldModifierDateTime;

    public MopHeadFields() {
    }

    public MopHeadFields(OrgProfile orgProfile, ModeOfPayment modeOfPayment, String headFieldName, int headFieldCreatorId, Date headFieldCreatorDateTime, Date headFieldModifierDateTime) {
       this.orgProfile = orgProfile;
       this.modeOfPayment = modeOfPayment;
       this.headFieldName = headFieldName;
       this.headFieldCreatorId = headFieldCreatorId;
       this.headFieldCreatorDateTime = headFieldCreatorDateTime;
       this.headFieldModifierDateTime = headFieldModifierDateTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public OrgProfile getOrgProfile() {
        return this.orgProfile;
    }
    
    public void setOrgProfile(OrgProfile orgProfile) {
        this.orgProfile = orgProfile;
    }
    public ModeOfPayment getModeOfPayment() {
        return this.modeOfPayment;
    }
    
    public void setModeOfPayment(ModeOfPayment modeOfPayment) {
        this.modeOfPayment = modeOfPayment;
    }
    public String getHeadFieldName() {
        return this.headFieldName;
    }
    
    public void setHeadFieldName(String headFieldName) {
        this.headFieldName = headFieldName;
    }
    public int getHeadFieldCreatorId() {
        return this.headFieldCreatorId;
    }
    
    public void setHeadFieldCreatorId(int headFieldCreatorId) {
        this.headFieldCreatorId = headFieldCreatorId;
    }
    public Date getHeadFieldCreatorDateTime() {
        return this.headFieldCreatorDateTime;
    }
    
    public void setHeadFieldCreatorDateTime(Date headFieldCreatorDateTime) {
        this.headFieldCreatorDateTime = headFieldCreatorDateTime;
    }
    public Date getHeadFieldModifierDateTime() {
        return this.headFieldModifierDateTime;
    }
    
    public void setHeadFieldModifierDateTime(Date headFieldModifierDateTime) {
        this.headFieldModifierDateTime = headFieldModifierDateTime;
    }




}


