package pojo.hibernate;
// Generated May 29, 2011 11:33:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DepartmentalBudgetAllocation generated by hbm2java
 */
public class DepartmentalBudgetAllocation  implements java.io.Serializable {


     private Integer dbaId;
     private Departmentmaster departmentmaster;
     private Institutionmaster institutionmaster;
     private Subinstitutionmaster subinstitutionmaster;
     private Budgetheadmaster budgetheadmaster;
     private Date dbaFromDate;
     private Date dbaToDate;
     private Integer dbaAmount;
     private Set erpmIndentMasters = new HashSet(0);

    public DepartmentalBudgetAllocation() {
    }

	
    public DepartmentalBudgetAllocation(Institutionmaster institutionmaster, Subinstitutionmaster subinstitutionmaster) {
        this.institutionmaster = institutionmaster;
        this.subinstitutionmaster = subinstitutionmaster;
    }
    public DepartmentalBudgetAllocation(Departmentmaster departmentmaster, Institutionmaster institutionmaster, Subinstitutionmaster subinstitutionmaster, Budgetheadmaster budgetheadmaster, Date dbaFromDate, Date dbaToDate, Integer dbaAmount, Set erpmIndentMasters) {
       this.departmentmaster = departmentmaster;
       this.institutionmaster = institutionmaster;
       this.subinstitutionmaster = subinstitutionmaster;
       this.budgetheadmaster = budgetheadmaster;
       this.dbaFromDate = dbaFromDate;
       this.dbaToDate = dbaToDate;
       this.dbaAmount = dbaAmount;
       this.erpmIndentMasters = erpmIndentMasters;
    }
   
    public Integer getDbaId() {
        return this.dbaId;
    }
    
    public void setDbaId(Integer dbaId) {
        this.dbaId = dbaId;
    }
    public Departmentmaster getDepartmentmaster() {
        return this.departmentmaster;
    }
    
    public void setDepartmentmaster(Departmentmaster departmentmaster) {
        this.departmentmaster = departmentmaster;
    }
    public Institutionmaster getInstitutionmaster() {
        return this.institutionmaster;
    }
    
    public void setInstitutionmaster(Institutionmaster institutionmaster) {
        this.institutionmaster = institutionmaster;
    }
    public Subinstitutionmaster getSubinstitutionmaster() {
        return this.subinstitutionmaster;
    }
    
    public void setSubinstitutionmaster(Subinstitutionmaster subinstitutionmaster) {
        this.subinstitutionmaster = subinstitutionmaster;
    }
    public Budgetheadmaster getBudgetheadmaster() {
        return this.budgetheadmaster;
    }
    
    public void setBudgetheadmaster(Budgetheadmaster budgetheadmaster) {
        this.budgetheadmaster = budgetheadmaster;
    }
    public Date getDbaFromDate() {
        return this.dbaFromDate;
    }
    
    public void setDbaFromDate(Date dbaFromDate) {
        this.dbaFromDate = dbaFromDate;
    }
    public Date getDbaToDate() {
        return this.dbaToDate;
    }
    
    public void setDbaToDate(Date dbaToDate) {
        this.dbaToDate = dbaToDate;
    }
    public Integer getDbaAmount() {
        return this.dbaAmount;
    }
    
    public void setDbaAmount(Integer dbaAmount) {
        this.dbaAmount = dbaAmount;
    }
    public Set getErpmIndentMasters() {
        return this.erpmIndentMasters;
    }
    
    public void setErpmIndentMasters(Set erpmIndentMasters) {
        this.erpmIndentMasters = erpmIndentMasters;
    }




}


