package pojo.hibernate;
// Generated May 29, 2011 11:33:37 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ErpmItemRateTaxes generated by hbm2java
 */
public class ErpmItemRateTaxes  implements java.io.Serializable {


     private Integer irtItemRateTaxesId;
     private ErpmItemRateDetails erpmItemRateDetails;
     private String irtTaxName;
     private BigDecimal irtTaxPercent;
     private BigDecimal irtTaxOnValuePercent;
     private BigDecimal irtSurchargePercent;

    public ErpmItemRateTaxes() {
    }

	
    public ErpmItemRateTaxes(ErpmItemRateDetails erpmItemRateDetails) {
        this.erpmItemRateDetails = erpmItemRateDetails;
    }
    public ErpmItemRateTaxes(ErpmItemRateDetails erpmItemRateDetails, String irtTaxName, BigDecimal irtTaxPercent, BigDecimal irtTaxOnValuePercent, BigDecimal irtSurchargePercent) {
       this.erpmItemRateDetails = erpmItemRateDetails;
       this.irtTaxName = irtTaxName;
       this.irtTaxPercent = irtTaxPercent;
       this.irtTaxOnValuePercent = irtTaxOnValuePercent;
       this.irtSurchargePercent = irtSurchargePercent;
    }
   
    public Integer getIrtItemRateTaxesId() {
        return this.irtItemRateTaxesId;
    }
    
    public void setIrtItemRateTaxesId(Integer irtItemRateTaxesId) {
        this.irtItemRateTaxesId = irtItemRateTaxesId;
    }
    public ErpmItemRateDetails getErpmItemRateDetails() {
        return this.erpmItemRateDetails;
    }
    
    public void setErpmItemRateDetails(ErpmItemRateDetails erpmItemRateDetails) {
        this.erpmItemRateDetails = erpmItemRateDetails;
    }
    public String getIrtTaxName() {
        return this.irtTaxName;
    }
    
    public void setIrtTaxName(String irtTaxName) {
        this.irtTaxName = irtTaxName;
    }
    public BigDecimal getIrtTaxPercent() {
        return this.irtTaxPercent;
    }
    
    public void setIrtTaxPercent(BigDecimal irtTaxPercent) {
        this.irtTaxPercent = irtTaxPercent;
    }
    public BigDecimal getIrtTaxOnValuePercent() {
        return this.irtTaxOnValuePercent;
    }
    
    public void setIrtTaxOnValuePercent(BigDecimal irtTaxOnValuePercent) {
        this.irtTaxOnValuePercent = irtTaxOnValuePercent;
    }
    public BigDecimal getIrtSurchargePercent() {
        return this.irtSurchargePercent;
    }
    
    public void setIrtSurchargePercent(BigDecimal irtSurchargePercent) {
        this.irtSurchargePercent = irtSurchargePercent;
    }




}


