package pojo.hibernate;
// Generated May 29, 2011 11:33:37 PM by Hibernate Tools 3.2.1.GA



/**
 * LanguageMaster generated by hbm2java
 */
public class LanguageMaster  implements java.io.Serializable {


     private Integer langId;
     private String langName;

    public LanguageMaster() {
    }

    public LanguageMaster(String langName) {
       this.langName = langName;
    }
   
    public Integer getLangId() {
        return this.langId;
    }
    
    public void setLangId(Integer langId) {
        this.langId = langId;
    }
    public String getLangName() {
        return this.langName;
    }
    
    public void setLangName(String langName) {
        this.langName = langName;
    }




}


