/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.edrp.pms.member;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="projassignform"
 */
@SuppressWarnings("serial")
public class ProjAssignForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	private String userId; //For holding User Id
	private String projectName; //For holding project name
	//private String orgName; //For holding organisation name
	private String roleName; //For holding role name
	//private String myradio;

	/*
	 * Generated Methods
	 */

	

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

/*The method getUserId return the User Id */
	public String getUserId() {
		return userId;
	}

/*The method setUserId is used for setting the User Id */
	public void setUserId(String userId) {
		this.userId = userId;
	}
	
/*The method getProjectName return the project name of a project */
	public String getProjectName() {
		return projectName;
	}
	
/*The method setProjectName is used for setting the project name of a project */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}
	

	/*The method getRoleName return the role name */
	public String getRoleName() {
		return roleName;
	}
	
/*The method setRoleName is used for setting the role name */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	

}