package org.IGNOU.ePortfolio.Model;
// Generated Jun 7, 2012 1:23:38 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ActivitiesAnnounce generated by hbm2java
 */
public class ActivitiesAnnounce implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int evidenceId;
    private GradeValue gradeValue;
    private UserList user;
    private Course course;
    private String evTitle;
    private Date openDate;
    private Date closeDate;
    private Date lastAcceptDate;
    private String instruction;
    private Boolean addDateSchedule;
    private Boolean addAnnoOdate;
    private Boolean addtoGradebook;
    private String assAttach;
    private Integer instituteId;
    private Integer programmeId;
    private Boolean saveEvid;
    private Boolean cancel;
    private String cancelReason;
    private Set evidenceSubmissions = new HashSet(0);
    private Set activitiesCommentses = new HashSet(0);

    public ActivitiesAnnounce(int evidenceId, GradeValue gradeValue, UserList user, Course course, String evTitle, Date openDate, Date closeDate, Date lastAcceptDate, String instruction, Boolean addDateSchedule, Boolean addAnnoOdate, Boolean addtoGradebook, String assAttach, Integer instituteId, Integer programmeId, Boolean saveEvid, Boolean cancel, String cancelReason, Set evidenceSubmissions, Set activitiesCommentses) {
        this.evidenceId = evidenceId;
        this.gradeValue = gradeValue;
        this.user = user;
        this.course = course;
        this.evTitle = evTitle;
        this.openDate = openDate;
        this.closeDate = closeDate;
        this.lastAcceptDate = lastAcceptDate;
        this.instruction = instruction;
        this.addDateSchedule = addDateSchedule;
        this.addAnnoOdate = addAnnoOdate;
        this.addtoGradebook = addtoGradebook;
        this.assAttach = assAttach;
        this.instituteId = instituteId;
        this.programmeId = programmeId;
        this.saveEvid = saveEvid;
        this.cancel = cancel;
        this.cancelReason = cancelReason;
        this.evidenceSubmissions = evidenceSubmissions;
        this.activitiesCommentses = activitiesCommentses;
    }

    public ActivitiesAnnounce() {
    }

    public int getEvidenceId() {
        return this.evidenceId;
    }

    public void setEvidenceId(int evidenceId) {
        this.evidenceId = evidenceId;
    }

    public GradeValue getGradeValue() {
        return this.gradeValue;
    }

    public void setGradeValue(GradeValue gradeValue) {
        this.gradeValue = gradeValue;
    }

    public UserList getUser() {
        return this.user;
    }

    public void setUser(UserList user) {
        this.user = user;
    }

    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public String getEvTitle() {
        return this.evTitle;
    }

    public void setEvTitle(String evTitle) {
        this.evTitle = evTitle;
    }

    public Date getOpenDate() {
        return this.openDate;
    }

    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    public Date getCloseDate() {
        return this.closeDate;
    }

    public void setCloseDate(Date closeDate) {
        this.closeDate = closeDate;
    }

    public Date getLastAcceptDate() {
        return this.lastAcceptDate;
    }

    public void setLastAcceptDate(Date lastAcceptDate) {
        this.lastAcceptDate = lastAcceptDate;
    }

    public String getInstruction() {
        return this.instruction;
    }

    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }

    public Boolean getAddDateSchedule() {
        return this.addDateSchedule;
    }

    public void setAddDateSchedule(Boolean addDateSchedule) {
        this.addDateSchedule = addDateSchedule;
    }

    public Boolean getAddAnnoOdate() {
        return this.addAnnoOdate;
    }

    public void setAddAnnoOdate(Boolean addAnnoOdate) {
        this.addAnnoOdate = addAnnoOdate;
    }

    public Boolean getAddtoGradebook() {
        return this.addtoGradebook;
    }

    public void setAddtoGradebook(Boolean addtoGradebook) {
        this.addtoGradebook = addtoGradebook;
    }

    public String getAssAttach() {
        return this.assAttach;
    }

    public void setAssAttach(String assAttach) {
        this.assAttach = assAttach;
    }

    public Integer getInstituteId() {
        return this.instituteId;
    }

    public void setInstituteId(Integer instituteId) {
        this.instituteId = instituteId;
    }

    public Integer getProgrammeId() {
        return this.programmeId;
    }

    public void setProgrammeId(Integer programmeId) {
        this.programmeId = programmeId;
    }

    public Boolean getSaveEvid() {
        return this.saveEvid;
    }

    public void setSaveEvid(Boolean saveEvid) {
        this.saveEvid = saveEvid;
    }

    public Boolean getCancel() {
        return this.cancel;
    }

    public void setCancel(Boolean cancel) {
        this.cancel = cancel;
    }

    public String getCancelReason() {
        return this.cancelReason;
    }

    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    public Set getEvidenceSubmissions() {
        return this.evidenceSubmissions;
    }

    public void setEvidenceSubmissions(Set evidenceSubmissions) {
        this.evidenceSubmissions = evidenceSubmissions;
    }

    public Set getActivitiesCommentses() {
        return this.activitiesCommentses;
    }

    public void setActivitiesCommentses(Set activitiesCommentses) {
        this.activitiesCommentses = activitiesCommentses;
    }
}