package org.IGNOU.ePortfolio.Model;
// Generated Aug 6, 2012 1:22:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Events generated by hbm2java
 */
public class Events  implements java.io.Serializable {


     private Long eventsId;
     private String eventTitle;
     private Date eventDateFrom;
     private Date eventDateTo;
     private Date createDate;
     private Date eventDisplayDate;
     private String venue;
     private String address;
     private String city;
     private String state;
     private String country;
     private Integer pincode;
     private Long phone;
     private String emailId;
     private String website;
     private String description;
     private Boolean postponed;
     private String postponedReason;
     private String creator;

    public Events() {
    }

    public Events(String eventTitle, Date eventDateFrom, Date eventDateTo, Date createDate, Date eventDisplayDate, String venue, String address, String city, String state, String country, Integer pincode, Long phone, String emailId, String website, String description, Boolean postponed, String postponedReason, String creator) {
       this.eventTitle = eventTitle;
       this.eventDateFrom = eventDateFrom;
       this.eventDateTo = eventDateTo;
       this.createDate = createDate;
       this.eventDisplayDate = eventDisplayDate;
       this.venue = venue;
       this.address = address;
       this.city = city;
       this.state = state;
       this.country = country;
       this.pincode = pincode;
       this.phone = phone;
       this.emailId = emailId;
       this.website = website;
       this.description = description;
       this.postponed = postponed;
       this.postponedReason = postponedReason;
       this.creator = creator;
    }
   
    public Long getEventsId() {
        return this.eventsId;
    }
    
    public void setEventsId(Long eventsId) {
        this.eventsId = eventsId;
    }
    public String getEventTitle() {
        return this.eventTitle;
    }
    
    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }
    public Date getEventDateFrom() {
        return this.eventDateFrom;
    }
    
    public void setEventDateFrom(Date eventDateFrom) {
        this.eventDateFrom = eventDateFrom;
    }
    public Date getEventDateTo() {
        return this.eventDateTo;
    }
    
    public void setEventDateTo(Date eventDateTo) {
        this.eventDateTo = eventDateTo;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getEventDisplayDate() {
        return this.eventDisplayDate;
    }
    
    public void setEventDisplayDate(Date eventDisplayDate) {
        this.eventDisplayDate = eventDisplayDate;
    }
    public String getVenue() {
        return this.venue;
    }
    
    public void setVenue(String venue) {
        this.venue = venue;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }
    public Long getPhone() {
        return this.phone;
    }
    
    public void setPhone(Long phone) {
        this.phone = phone;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getPostponed() {
        return this.postponed;
    }
    
    public void setPostponed(Boolean postponed) {
        this.postponed = postponed;
    }
    public String getPostponedReason() {
        return this.postponedReason;
    }
    
    public void setPostponedReason(String postponedReason) {
        this.postponedReason = postponedReason;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }




}


