package org.IGNOU.ePortfolio.Model;
// Generated Feb 27, 2012 12:35:22 PM by Hibernate Tools 3.2.1.GA

/**
 * JournalAuthor generated by hbm2java
 *
 * @author IGNOU Team
 * @version 1
 * @since 27-02-2012
 */
public class JournalAuthor implements java.io.Serializable {

    private Long journalAuthorId;
    private Journal journal;
    private String fname;
    private String lname;

    public JournalAuthor() {
    }

    public JournalAuthor(Journal journal, String fname, String lname) {
        this.journal = journal;
        this.fname = fname;
        this.lname = lname;
    }

    public Long getJournalAuthorId() {
        return this.journalAuthorId;
    }

    public void setJournalAuthorId(Long journalAuthorId) {
        this.journalAuthorId = journalAuthorId;
    }

    public Journal getJournal() {
        return this.journal;
    }

    public void setJournal(Journal journal) {
        this.journal = journal;
    }

    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }
}
