package org.IGNOU.ePortfolio.Model;
// Generated Feb 16, 2012 2:59:44 PM by Hibernate Tools 3.2.1.GA

/**
 * MediaPublication generated by hbm2java
 *
 * @author IGNOU Team
 * @version 1
 * @since 16 February 2012
 */
public class MediaPublication implements java.io.Serializable {

    private long mpId;
    private String userId;
    private String typeOfMedia;
    private String titleOfMedia;
    private String titleOfArticle;
    private String pubDate;
    private String url;
    private String summary;
    private Integer api;

    public MediaPublication() {
    }

    public MediaPublication(long mpId) {
        this.mpId = mpId;
    }

    public MediaPublication(long mpId, String userId, String typeOfMedia, String titleOfMedia, String titleOfArticle, String pubDate, String url, String summary, Integer api) {
        this.mpId = mpId;
        this.userId = userId;
        this.typeOfMedia = typeOfMedia;
        this.titleOfMedia = titleOfMedia;
        this.titleOfArticle = titleOfArticle;
        this.pubDate = pubDate;
        this.url = url;
        this.summary = summary;
        this.api = api;
    }

    public long getMpId() {
        return this.mpId;
    }

    public void setMpId(long mpId) {
        this.mpId = mpId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getTypeOfMedia() {
        return this.typeOfMedia;
    }

    public void setTypeOfMedia(String typeOfMedia) {
        this.typeOfMedia = typeOfMedia;
    }

    public String getTitleOfMedia() {
        return this.titleOfMedia;
    }

    public void setTitleOfMedia(String titleOfMedia) {
        this.titleOfMedia = titleOfMedia;
    }

    public String getTitleOfArticle() {
        return this.titleOfArticle;
    }

    public void setTitleOfArticle(String titleOfArticle) {
        this.titleOfArticle = titleOfArticle;
    }

    public String getPubDate() {
        return this.pubDate;
    }

    public void setPubDate(String pubDate) {
        this.pubDate = pubDate;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Integer getApi() {
        return this.api;
    }

    public void setApi(Integer api) {
        this.api = api;
    }
}
