package org.IGNOU.ePortfolio.Model;
// Generated Feb 3, 2012 2:27:31 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Patent generated by hbm2java
 *
 * @author IGNOU Team
 * @version 1
 */
public class Patent implements java.io.Serializable {

    private Long patentId;
    private String userId;
    private String patentType;
    private String country;
    private String patentTitle;
    private String assignee;
    private Integer applNo;
    private String field;
    private String patentDate;
    private Integer patentNo;
    private String affiliation;
    private String language;
    private String url;
    private String abstract_;
    private Integer api;
    private ArrayList<String> fname;
    private ArrayList<String> lname;
    private ArrayList<String> address;
    private Set<Inventor> inventors = new HashSet<Inventor>(0);

    public Patent() {
    }
//
//    public Patent(ArrayList<String> fname, ArrayList<String> lname, ArrayList<String> address) {
//        this.fname = fname;
//        this.lname = lname;
//        this.address = address;
//    }

//    public Patent(String userId, String patentType, String country, String patentTitle, String assignee, Integer applNo, String field, String patentDate, Integer patentNo, String affiliation, String language, String url, String abstract_, Integer api) {
//       this.userId = userId;
//       this.patentType = patentType;
//       this.country = country;
//       this.patentTitle = patentTitle;
//       this.assignee = assignee;
//       this.applNo = applNo;
//       this.field = field;
//       this.patentDate = patentDate;
//       this.patentNo = patentNo;
//       this.affiliation = affiliation;
//       this.language = language;
//       this.url = url;
//       this.abstract_ = abstract_;
//       this.api = api;
//    }
    public Patent(Long patentId, String userId, String patentType, String country, String patentTitle, String assignee, Integer applNo, String field, String patentDate, Integer patentNo, String affiliation, String language, String url, String abstract_, Integer api, ArrayList<String> fname, ArrayList<String> lname, ArrayList<String> address, Set<Inventor> inventors) {
        this.patentId = patentId;
        this.userId = userId;
        this.patentType = patentType;
        this.country = country;
        this.patentTitle = patentTitle;
        this.assignee = assignee;
        this.applNo = applNo;
        this.field = field;
        this.patentDate = patentDate;
        this.patentNo = patentNo;
        this.affiliation = affiliation;
        this.language = language;
        this.url = url;
        this.abstract_ = abstract_;
        this.api = api;
        this.fname = fname;
        this.lname = lname;
        this.address = address;
        this.inventors = inventors;
    }

    public Long getPatentId() {
        return this.patentId;
    }

    public void setPatentId(Long patentId) {
        this.patentId = patentId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getPatentType() {
        return this.patentType;
    }

    public void setPatentType(String patentType) {
        this.patentType = patentType;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPatentTitle() {
        return this.patentTitle;
    }

    public void setPatentTitle(String patentTitle) {
        this.patentTitle = patentTitle;
    }

    public String getAssignee() {
        return this.assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    public Integer getApplNo() {
        return this.applNo;
    }

    public void setApplNo(Integer applNo) {
        this.applNo = applNo;
    }

    public String getField() {
        return this.field;
    }

    public void setField(String field) {
        this.field = field;
    }

    public String getPatentDate() {
        return this.patentDate;
    }

    public void setPatentDate(String patentDate) {
        this.patentDate = patentDate;
    }

    public Integer getPatentNo() {
        return this.patentNo;
    }

    public void setPatentNo(Integer patentNo) {
        this.patentNo = patentNo;
    }

    public String getAffiliation() {
        return this.affiliation;
    }

    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getAbstract_() {
        return this.abstract_;
    }

    public void setAbstract_(String abstract_) {
        this.abstract_ = abstract_;
    }

    public Integer getApi() {
        return this.api;
    }

    public void setApi(Integer api) {
        this.api = api;
    }

    public ArrayList<String> getAddress() {
        return address;
    }

    public void setAddress(ArrayList<String> address) {
        this.address = address;
    }

    public ArrayList<String> getFname() {
        return fname;
    }

    public void setFname(ArrayList<String> fname) {
        this.fname = fname;
    }

    public Set<Inventor> getInventors() {
        return inventors;
    }

    public void setInventors(Set<Inventor> inventors) {
        this.inventors = inventors;
    }

    public ArrayList<String> getLname() {
        return lname;
    }

    public void setLname(ArrayList<String> lname) {
        this.lname = lname;
    }
}
