/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.Model;
// Generated Oct 17, 2011 2:52:59 PM by Hibernate Tools 3.2.1.GA

/**
 * ProfileProAffiliation generated by hbm2java
 * @author IGNOU Team
 * @since 14-Oct-2011
 * @version 1.1
 * proAffiliationId's data type is Modified by IGNOU Team on 17-Oct-2011.
 */
public class ProfileProAffiliation implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long proAffiliationId;
    private String userId;
    private String role;
    private String orgBody;
    private String vfrom;
    private String vupto;
    private String place;
    private String country;
    private String summary;

    public ProfileProAffiliation() {
    }

    public ProfileProAffiliation(long proAffiliationId) {
        this.proAffiliationId = proAffiliationId;
    }

    public ProfileProAffiliation(long proAffiliationId, String userId, String role, String orgBody, String vfrom, String vupto, String place, String country, String summary) {
        this.proAffiliationId = proAffiliationId;
        this.userId = userId;
        this.role = role;
        this.orgBody = orgBody;
        this.vfrom = vfrom;
        this.vupto = vupto;
        this.place = place;
        this.country = country;
        this.summary = summary;
    }

    public long getProAffiliationId() {
        return this.proAffiliationId;
    }

    public void setProAffiliationId(long proAffiliationId) {
        this.proAffiliationId = proAffiliationId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getOrgBody() {
        return this.orgBody;
    }

    public void setOrgBody(String orgBody) {
        this.orgBody = orgBody;
    }

    public String getVfrom() {
        return this.vfrom;
    }

    public void setVfrom(String vfrom) {
        this.vfrom = vfrom;
    }

    public String getVupto() {
        return this.vupto;
    }

    public void setVupto(String vupto) {
        this.vupto = vupto;
    }

    public String getPlace() {
        return this.place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }
}
