/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.Model;
// Generated Oct 11, 2011 11:42:23 AM by Hibernate Tools 3.2.1.GA



/**
 * ProfileCertification generated by hbm2java
 */
public class ProfileCertification  implements java.io.Serializable {


     private long certificationId;
     private String userId;
     private String certificationName;
     private String certificationAuthority;
     private String license;
     private String certificationDate;
     private String validDate;

    public ProfileCertification() {
    }

	
    public ProfileCertification(long certificationId) {
        this.certificationId = certificationId;
    }
    public ProfileCertification(long certificationId, String userId, String certificationName, String certificationAuthority, String license, String certificationDate, String validDate) {
       this.certificationId = certificationId;
       this.userId = userId;
       this.certificationName = certificationName;
       this.certificationAuthority = certificationAuthority;
       this.license = license;
       this.certificationDate = certificationDate;
       this.validDate = validDate;
    }
   
    public long getCertificationId() {
        return this.certificationId;
    }
    
    public void setCertificationId(long certificationId) {
        this.certificationId = certificationId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getCertificationName() {
        return this.certificationName;
    }
    
    public void setCertificationName(String certificationName) {
        this.certificationName = certificationName;
    }
    public String getCertificationAuthority() {
        return this.certificationAuthority;
    }
    
    public void setCertificationAuthority(String certificationAuthority) {
        this.certificationAuthority = certificationAuthority;
    }
    public String getLicense() {
        return this.license;
    }
    
    public void setLicense(String license) {
        this.license = license;
    }
    public String getCertificationDate() {
        return this.certificationDate;
    }
    
    public void setCertificationDate(String certificationDate) {
        this.certificationDate = certificationDate;
    }
    public String getValidDate() {
        return this.validDate;
    }
    
    public void setValidDate(String validDate) {
        this.validDate = validDate;
    }




}


