/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.Model;
// Generated Sep 13, 2011 12:18:08 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Id;

/**
 * ProfileEmployment generated by hbm2java
 * @author IGNOU Team 
 * Created on 13-Sep-2011
 */
public class ProfileEmployment implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    private long employmentInfoId;
    @Column(name = "user_id")
    private String userId;
    @Column(name = "jTitle")
    private String jtitle;
    @Column(name = "orgName")
    private String orgName;
    @Column(name = "oAddress")
    private String oaddress;
    @Column(name = "oCity")
    private String ocity;
    @Column(name = "oState")
    private String ostate;
    @Column(name = "oCountry")
    private String ocountry;
    @Column(name = "jDate")
    private String jdate;
    @Column(name = "lDate")
    private String ldate;
    @Column(name = "description")
    private String description;
   

    public ProfileEmployment() {
    }

    public ProfileEmployment(long employmentInfoId) {
        this.employmentInfoId = employmentInfoId;
    }

    public ProfileEmployment(long employmentInfoId, String userId, String jtitle, String orgName, String oaddress, String ocity, String ostate, String ocountry, String jdate, String ldate, String description) {
        this.employmentInfoId = employmentInfoId;
        this.userId = userId;
        this.jtitle = jtitle;
        this.orgName = orgName;
        this.oaddress = oaddress;
        this.ocity = ocity;
        this.ostate = ostate;
        this.ocountry = ocountry;
        this.jdate = jdate;
        this.ldate = ldate;
        this.description = description;
    }

    public long getEmploymentInfoId() {
        return this.employmentInfoId;
    }

    public void setEmploymentInfoId(long employmentInfoId) {
        this.employmentInfoId = employmentInfoId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getJtitle() {
        return this.jtitle;
    }

    public void setJtitle(String jtitle) {
        this.jtitle = jtitle;
    }

    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOaddress() {
        return this.oaddress;
    }

    public void setOaddress(String oaddress) {
        this.oaddress = oaddress;
    }

    public String getOcity() {
        return this.ocity;
    }

    public void setOcity(String ocity) {
        this.ocity = ocity;
    }

    public String getOstate() {
        return this.ostate;
    }

    public void setOstate(String ostate) {
        this.ostate = ostate;
    }

    public String getOcountry() {
        return this.ocountry;
    }

    public void setOcountry(String ocountry) {
        this.ocountry = ocountry;
    }

    public String getJdate() {
        return this.jdate;
    }

    public void setJdate(String jdate) {
        this.jdate = jdate;
    }

    public String getLdate() {
        return this.ldate;
    }

    public void setLdate(String ldate) {
        this.ldate = ldate;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
