package org.IGNOU.ePortfolio.Model;
// Generated Feb 23, 2012 11:35:18 AM by Hibernate Tools 3.2.1.GA


import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Resume generated by hbm2java
 */
public class Resume  implements java.io.Serializable {


     private long idResume;
     private String userId;
     private byte[] resume;
     private String resumeName;
     private Long resumeSize;
     private String resumeType;
     private Date uploadDate;
     private File userResume;
     private String userResumeFileName;
     Calendar c_Date = Calendar.getInstance();
     SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
     private String upload_date = f.format(c_Date.getTime());
   
    
     
    public Resume() {
    }

	
    public Resume(long idResume) {
        this.idResume = idResume;
    }
    public Resume(long idResume, String userId, byte[] resume, String resumeName, Long resumeSize, String resumeType, Date uploadDate) {
       this.idResume = idResume;
       this.userId = userId;
       this.resume = resume;
       this.resumeName = resumeName;
       this.resumeSize = resumeSize;
       this.resumeType = resumeType;
       this.uploadDate = uploadDate;
    }
   
    public long getIdResume() {
        return this.idResume;
    }
    
    public void setIdResume(long idResume) {
        this.idResume = idResume;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public byte[] getResume() throws FileNotFoundException {
         
            FileInputStream fis = new FileInputStream(getUserResume());
            ByteArrayOutputStream bs = new ByteArrayOutputStream();
            byte[] bf = new byte[1024];
        try {

            for (int readNum; (readNum = fis.read(bf)) != -1;) {
                    bs.write(bf, 0, readNum);
             
            }
        }
        catch (IOException ex) {
            Logger.getLogger(Resume.class.getName()).log(Level.SEVERE, null, ex);
        }
        resume=bs.toByteArray();
       return this.resume;
    }
    
    
    public void setResume(byte[] resume) {
        this.resume = resume;
    }
    public String getResumeName() {
        resumeName=getUserResumeFileName();
        return this.resumeName;
    }
    
    public void setResumeName(String resumeName) {
        this.resumeName = resumeName;
    }
    public Long getResumeSize() {
        resumeSize=userResume.length()/1024;
        return this.resumeSize;
    }
    
    public void setResumeSize(Long resumeSize) {
        this.resumeSize = resumeSize;
    }
    public String getResumeType() {
        resumeType=getUserResumeFileName().substring(getUserResumeFileName().indexOf(".", 4));
        return this.resumeType;
    }
    
    public void setResumeType(String resumeType) {
        this.resumeType = resumeType;
    }
    public Date getUploadDate() {
        try {
            uploadDate= (Date)f.parse(upload_date);
        } catch (ParseException ex) {
            Logger.getLogger(Resume.class.getName()).log(Level.SEVERE, null, ex);
        }
        return this.uploadDate;
    }
    
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    
    /**
     * @return the userResumeFileName
     */
    public String getUserResumeFileName() {
        return userResumeFileName;
    }

    /**
     * @param userResumeFileName the userResumeFileName to set
     */
    public void setUserResumeFileName(String userResumeFileName) {
        this.userResumeFileName = userResumeFileName;
    }

    
    /**
     * @return the userResume
     */
    public File getUserResume() {
        return userResume;
    }

    /**
     * @param userResume the userResume to set
     */
    public void setUserResume(File userResume) {
        this.userResume = userResume;
    }

    

}


