package org.IGNOU.ePortfolio.Model;
// Generated Feb 24, 2012 12:39:12 PM by Hibernate Tools 3.2.1.GA

/**
 * SeminarsWorkshopsAuthor generated by hbm2java
 *
 * @author IGNOU Team
 * @version 1
 * @since 24-02-2012
 */
public class SeminarsWorkshopsAuthor implements java.io.Serializable {

    private Long swAuthorId;
    private SeminarsWorkshops seminarsWorkshops;
    private String fname;
    private String lname;

    public SeminarsWorkshopsAuthor() {
    }

    public SeminarsWorkshopsAuthor(SeminarsWorkshops seminarsWorkshops, String fname, String lname) {
        this.seminarsWorkshops = seminarsWorkshops;
        this.fname = fname;
        this.lname = lname;
    }

    public Long getSwAuthorId() {
        return this.swAuthorId;
    }

    public void setSwAuthorId(Long swAuthorId) {
        this.swAuthorId = swAuthorId;
    }

    public SeminarsWorkshops getSeminarsWorkshops() {
        return this.seminarsWorkshops;
    }

    public void setSeminarsWorkshops(SeminarsWorkshops seminarsWorkshops) {
        this.seminarsWorkshops = seminarsWorkshops;
    }

    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }
}
