package org.IGNOU.ePortfolio.Model;
// Generated Oct 19, 2012 1:12:28 PM by Hibernate Tools 3.2.1.GA



/**
 * Vistingcard generated by hbm2java
 */
public class Vistingcard  implements java.io.Serializable {


     private Integer visitcardId;
     private String userId;
     private String displayName;
     private String designation;
     private String company;
     private Long mobile;
     private Long officePh;
     private Integer fax;
     private String email;
     private String websiteOff;
     private String websitePer;

    public Vistingcard() {
    }

    public Vistingcard(String userId, String displayName, String designation, String company, Long mobile, Long officePh, Integer fax, String email, String websiteOff, String websitePer) {
       this.userId = userId;
       this.displayName = displayName;
       this.designation = designation;
       this.company = company;
       this.mobile = mobile;
       this.officePh = officePh;
       this.fax = fax;
       this.email = email;
       this.websiteOff = websiteOff;
       this.websitePer = websitePer;
    }
   
    public Integer getVisitcardId() {
        return this.visitcardId;
    }
    
    public void setVisitcardId(Integer visitcardId) {
        this.visitcardId = visitcardId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public Long getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }
    public Long getOfficePh() {
        return this.officePh;
    }
    
    public void setOfficePh(Long officePh) {
        this.officePh = officePh;
    }
    public Integer getFax() {
        return this.fax;
    }
    
    public void setFax(Integer fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsiteOff() {
        return this.websiteOff;
    }
    
    public void setWebsiteOff(String websiteOff) {
        this.websiteOff = websiteOff;
    }
    public String getWebsitePer() {
        return this.websitePer;
    }
    
    public void setWebsitePer(String websitePer) {
        this.websitePer = websitePer;
    }




}


