package org.iitk.livetv.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Sat Dec 22 02:32:10 IST 2012]
  *
  */
public class ChannelMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.iitk.livetv.om.map.ChannelMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("livetv");

        dbMap.addTable("CHANNEL");
        TableMap tMap = dbMap.getTable("CHANNEL");

        tMap.setPrimaryKeyMethod(TableMap.ID_BROKER);

        tMap.setPrimaryKeyMethodInfo(tMap.getName());

              tMap.addPrimaryKey("CHANNEL.CHANNEL_ID", new Integer(0));
                    tMap.addColumn("CHANNEL.CHANNEL_NAME", new String());
                    tMap.addColumn("CHANNEL.CHANNEL_DESC", new String());
                    tMap.addColumn("CHANNEL.CHANNEL_IP_ADDRESS", new String());
                    tMap.addColumn("CHANNEL.CHANNEL_PORT", new Integer(0));
                    tMap.addColumn("CHANNEL.CHANNEL_ICON", new String());
          }
}
