/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.edrp.pms.organization;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-29-2009
 * 
 * XDoclet definition:
 * @struts.form name="searchorgform"
 */

/**
 * This class is used at the time of searching organisation
 * It contains the getter and setter of search value and search option 
 */
@SuppressWarnings("serial")
public class SearchOrgForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private String keysearch;	//for holding searching element.
	private String searchOption="Organisation Name";	//for holding searching searchOption.
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * The method getKeysearch return searching element.
	 * */
	public String getKeysearch() {
		return keysearch;
	}
	
	/**
	 * The method setKeysearch is used for setting the search element in variable keysearch. 
	 * */
	
	public void setKeysearch(String keysearch) {
		this.keysearch = keysearch;
	}
	
	/**
	 * The method getSearchOptionreturn searching option.
	 * */
	public String getSearchOption() {
		return searchOption;
	}
	
	/**
	 * The method setSearchOption is used for setting the search element in variable searchOption. 
	 * */
	
	public void setSearchOption(String searchOption) {
		this.searchOption = searchOption;
	}
}