/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.Registration
.Model;
// Generated Oct 3, 2011 12:32:07 PM by Hibernate Tools 3.2.1.GA



/**
 * FacultyRegistration generated by hbm2java
 */
public class FacultyRegistration  implements java.io.Serializable {


     private long facultyRegId;
     private String instituteName;
     private String department;
     private String emailId;
     private String password;
     private String rePassword;
     private String fname;
     private String mname;
     private String lname;
     private String organization;

    public FacultyRegistration() {
    }

	
    public FacultyRegistration(long facultyRegId) {
        this.facultyRegId = facultyRegId;
    }
    public FacultyRegistration(long facultyRegId, String instituteName, String department, String emailId, String password, String rePassword, String fname, String mname, String lname, String organization) {
       this.facultyRegId = facultyRegId;
       this.instituteName = instituteName;
       this.department = department;
       this.emailId = emailId;
       this.password = password;
       this.rePassword = rePassword;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.organization = organization;
    }
   
    public long getFacultyRegId() {
        return this.facultyRegId;
    }
    
    public void setFacultyRegId(long facultyRegId) {
        this.facultyRegId = facultyRegId;
    }
    public String getInstituteName() {
        return this.instituteName;
    }
    
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRePassword() {
        return this.rePassword;
    }
    
    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }




}


