/*
 * 
 *  Copyright (c) 2011 eGyankosh, IGNOU, New Delhi.
 *  All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or
 *  without modification, are permitted provided that the following
 *  conditions are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this  list of conditions and the following disclaimer.
 *
 *  Redistribution in binary form must reproducuce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *
 *  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED.  IN NO EVENT SHALL eGyankosh, IGNOU OR ITS CONTRIBUTORS BE LIABLE
 *  FOR ANY DIRECT, INDIRECT, INCIDENTAL,SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 *  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 *  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 *  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *
 *  Contributors: Members of eGyankosh, IGNOU, New Delhi.
 *
 */
package org.IGNOU.ePortfolio.Registration
.Model;
// Generated Oct 3, 2011 12:32:07 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Id;




/**
 * StudentRegistration generated by hbm2java
 */
public class StudentRegistration  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     @Id
     private long studentRegId;
     private String emailId;
     private String password;
     private String rePassword;
     private String fname;
     private String mname;
     private String lname;
     private String occupation;
     private String role;
     private String univName;
     private String univRegNo;
     private String programe;

    public StudentRegistration() {
    }

	
    public StudentRegistration(long studentRegId) {
        this.studentRegId = studentRegId;
    }
    public StudentRegistration(long studentRegId, String emailId, String password, String rePassword, String fname, String mname, String lname, String occupation, String role, String univName, String univRegNo, String programe) {
       this.studentRegId = studentRegId;
       this.emailId = emailId;
       this.password = password;
       this.rePassword = rePassword;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.occupation = occupation;
       this.role = role;
       this.univName = univName;
       this.univRegNo = univRegNo;
       this.programe = programe;
    }
   
    public long getStudentRegId() {
        return this.studentRegId;
    }
    
    public void setStudentRegId(long studentRegId) {
        this.studentRegId = studentRegId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRePassword() {
        return this.rePassword;
    }
    
    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getUnivName() {
        return this.univName;
    }
    
    public void setUnivName(String univName) {
        this.univName = univName;
    }
    public String getUnivRegNo() {
        return this.univRegNo;
    }
    
    public void setUnivRegNo(String univRegNo) {
        this.univRegNo = univRegNo;
    }
    public String getPrograme() {
        return this.programe;
    }
    
    public void setPrograme(String programe) {
        this.programe = programe;
    }
}


