/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package in.ac.dei.edrp.pms.changePassword;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;


/** 
 * MyEclipse Struts
 * Creation date: 01-01-2010
 * 
 * XDoclet definition:
 * @struts.form name="userpasswordform"
 */
public class UserPasswordForm extends ValidatorForm {
	/*
	 * Generated fields
	 */
	private static final long serialVersionUID = 1L;

	
	/** newpassword property */
	private String newpassworduser;

	/** repassword property */
	private String repassworduser;
	private String userid;
	/*
	 * Generated Methods
	 */

	
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	

	/** 
	 * Returns the newpassword.
	 * @return String
	 */
	public String getNewpassworduser() {
		return newpassworduser;
	}

	/** 
	 * Set the newpassword.
	 * @param newpassword The newpassword to set
	 */
	public void setNewpassworduser(String newpassworduser) {
		this.newpassworduser = newpassworduser;
	}

	/** 
	 * Returns the repassword.
	 * @return String
	 */
	public String getRepassworduser() {
		return repassworduser;
	}

	/** 
	 * Set the repassword.
	 * @param repassword The repassword to set
	 */
	public void setRepassworduser(String repassworduser) {
		this.repassworduser = repassworduser;
	}
}