package org.dei.edrp.pms.task;

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="taskform"
 */
public class TaskForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** fields property */
	private String taskName;//for holding task name
	private String resourceName;//for holding resource name
	private String darea;//for holding description of a task
	private String input_field;//for holding gantt chart colour of a task 
	private String sdate;//for holding start date of a task
	private String fdate;//for holding finish date of a task
	private String projectName;//for holding project name
	private String orgName;//for holding organisation name 
	private String taskDependency;//for holding the old task dependency
	private String pcom;//for holding % completion of the desired task
	private String prosdate;
	private String profdate;
	
	/*
	 * Generated Methods
	 */


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.orgName="";
		this.resourceName="--Select--";
		this.projectName="";
	}
	public String getProsdate() {
		return prosdate;
	}
	public void setProsdate(String prosdate) {
		this.prosdate = prosdate;
	}
	public String getProfdate() {
		return profdate;
	}
	public void setProfdate(String profdate) {
		this.profdate = profdate;
	}

	public String getResourceName() {
		return resourceName;
	}
	public void setResourceName(String rname) {
		this.resourceName = rname;
	}
	public String getDarea() {
		return darea;
	}
	public void setDarea(String darea) {
		this.darea = darea;
	}
	
	public String getInput_field() {
		return input_field;
	}
	public void setInput_field(String input_field) {
		this.input_field = input_field;
	}
	public String getSdate() {
		return sdate;
	}
	public void setSdate(String sdate) {
		this.sdate = sdate;
	}
	public String getFdate() {
		return fdate;
	}
	public void setFdate(String fdate) {
		this.fdate = fdate;
	}

	public String getPcom() {
		return pcom;
	}
	public void setPcom(String pcom) {
		this.pcom = pcom;
	}
	public String getProjectName() {
		return projectName;
	}
	public void setProjectName(String pname) {
		this.projectName = pname;
	}
	public String getOrgName() {
		return orgName;
	}
	public void setOrgName(String institute) {
		this.orgName = institute;
	}
	
	public String getTaskDependency() {
		return taskDependency;
	}
	public void setTaskDependency(String pdependency) {
		this.taskDependency= pdependency;
	}
	

	/** 
	 * Returns the taskname.
	 * @return String
	 */
	public String getTaskName() {
		return taskName;
	}

	/** 
	 * Set the tname.
	 * @param tname The tname to set
	 */
	public void setTaskName(String tname) {
		this.taskName = tname;
	}
}